# Databricks notebook source
# MAGIC %md
# MAGIC ## Loads By Billing
# MAGIC * **Description:** Load from Bronze to Silver as delta file
# MAGIC * **Created Date:** 03/07/2025
# MAGIC * **Created By:** Uday
# MAGIC * **Modified Date:** 06/10/2025
# MAGIC * **Modified By:** Uday
# MAGIC * **Changes Made:** Logic Update

# COMMAND ----------

# MAGIC %md
# MAGIC ####Update Metadata Pipeline Start Time

# COMMAND ----------

# MAGIC %sql
# MAGIC UPDATE metadata.mastermetadata 
# MAGIC SET PipelineStartTime = current_timestamp()
# MAGIC WHERE TableID = 'GL1'

# COMMAND ----------

# MAGIC %md
# MAGIC #### Load the Target Data

# COMMAND ----------

# MAGIC %sql
# MAGIC MERGE INTO Gold.Fact_Loads_By_Billing AS TARGET
# MAGIC USING Gold.VW_Fact_Loads_By_Billing_Full_Load AS SOURCE
# MAGIC ON TARGET.DW_Load_ID = SOURCE.DW_Load_ID
# MAGIC
# MAGIC WHEN MATCHED AND Target.Hashkey != Source.Hashkey THEN 
# MAGIC UPDATE SET
# MAGIC     Load_Number = SOURCE.Load_Number,
# MAGIC     Admin_Fees_Carrier_USD = SOURCE.Admin_Fees_Carrier_USD,
# MAGIC     Admin_Fees_Carrier_CAD = SOURCE.Admin_Fees_Carrier_CAD,
# MAGIC     Admin_Fees_Customer_USD = SOURCE.Admin_Fees_Customer_USD,
# MAGIC     Admin_Fees_Customer_CAD = SOURCE.Admin_Fees_Customer_CAD,
# MAGIC     Billing_Status = SOURCE.Billing_Status,
# MAGIC     Actual_Delivered_Date = SOURCE.Actual_Delivered_Date,
# MAGIC     Booking_Type = SOURCE.Booking_Type,
# MAGIC     Booked_Date = SOURCE.Booked_Date,
# MAGIC     Carrier_Fuel_Surcharge_CAD = SOURCE.Carrier_Fuel_Surcharge_CAD,
# MAGIC     Carrier_Fuel_Surcharge_USD = SOURCE.Carrier_Fuel_Surcharge_USD,
# MAGIC     Carrier_Linehaul_CAD = SOURCE.Carrier_Linehaul_CAD,
# MAGIC     Carrier_Linehaul_USD = SOURCE.Carrier_Linehaul_USD,
# MAGIC     Carrier_ID = SOURCE.Carrier_ID,
# MAGIC     Carrier_Name = SOURCE.Carrier_Name,
# MAGIC     Carrier_New_Office = SOURCE.Carrier_New_Office,
# MAGIC     Carrier_Old_Office = SOURCE.Carrier_Old_Office,
# MAGIC     Carrier_Other_Fees_CAD = SOURCE.Carrier_Other_Fees_CAD,
# MAGIC     Carrier_Other_Fees_USD = SOURCE.Carrier_Other_Fees_USD,
# MAGIC     Carrier_Rep_ID = SOURCE.Carrier_Rep_ID,
# MAGIC     Carrier_Rep = SOURCE.Carrier_Rep,
# MAGIC     Combined_Load = SOURCE.Combined_Load,
# MAGIC     Consignee_Delivery_Address = SOURCE.Consignee_Delivery_Address,
# MAGIC     Consignee_Name = SOURCE.Consignee_Name,
# MAGIC     Consignee_Pickup_Address = SOURCE.Consignee_Pickup_Address,
# MAGIC     Customer_Fuel_Surcharge_USD = SOURCE.Customer_Fuel_Surcharge_USD,
# MAGIC     Customer_Fule_Surcharge_CAD = SOURCE.Customer_Fule_Surcharge_CAD,
# MAGIC     Customer_Linehaul_CAD = SOURCE.Customer_Linehaul_CAD,
# MAGIC     Customer_Linehaul_USD = SOURCE.Customer_Linehaul_USD,
# MAGIC     Customer_Master = SOURCE.Customer_Master,
# MAGIC     Customer_ID = SOURCE.Customer_ID,
# MAGIC     Customer_Name = SOURCE.Customer_Name,
# MAGIC     Customer_New_Office = SOURCE.Customer_New_Office,
# MAGIC     Customer_Old_Office = SOURCE.Customer_Old_Office,
# MAGIC     Customer_Other_Fees_CAD = SOURCE.Customer_Other_Fees_CAD,
# MAGIC     Customer_Other_Fees_USD = SOURCE.Customer_Other_Fees_USD,
# MAGIC     Customer_Rep_ID = SOURCE.Customer_Rep_ID,
# MAGIC     Customer_Rep = SOURCE.Customer_Rep,
# MAGIC     Days_Ahead = SOURCE.Days_Ahead,
# MAGIC     Bounced_Date = SOURCE.Bounced_Date,
# MAGIC     Cancelled_Date = SOURCE.Cancelled_Date,
# MAGIC     Delivery_Pickup_Charges_Carrier_CAD = SOURCE.Delivery_Pickup_Charges_Carrier_CAD,
# MAGIC     Delivery_Pickup_Charges_Carrier_USD = SOURCE.Delivery_Pickup_Charges_Carrier_USD,
# MAGIC     Delivery_Pickup_Charges_Customer_CAD = SOURCE.Delivery_Pickup_Charges_Customer_CAD,
# MAGIC     Delivery_Pickup_Charges_Customer_USD = SOURCE.Delivery_Pickup_Charges_Customer_USD,
# MAGIC     Delivery_Appointment_Date = SOURCE.Delivery_Appointment_Date,
# MAGIC     Delivery_EndDate = SOURCE.Delivery_EndDate,
# MAGIC     Destination_City = SOURCE.Destination_City,
# MAGIC     Destination_State = SOURCE.Destination_State,
# MAGIC     Destination_Zip = SOURCE.Destination_Zip,
# MAGIC     DOT_Number = SOURCE.DOT_Number,
# MAGIC     Delivery_StartDate = SOURCE.Delivery_StartDate,
# MAGIC     Equipment = SOURCE.Equipment,
# MAGIC     Equipment_Vehicle_Charges_Carrier_CAD = SOURCE.Equipment_Vehicle_Charges_Carrier_CAD,
# MAGIC     Equipment_Vehicle_Charges_Carrier_USD = SOURCE.Equipment_Vehicle_Charges_Carrier_USD,
# MAGIC     Equipment_Vehicle_Charges_Customer_CAD = SOURCE.Equipment_Vehicle_Charges_Customer_CAD,
# MAGIC     Equipment_Vehicle_Charges_Customer_USD = SOURCE.Equipment_Vehicle_Charges_Customer_USD,
# MAGIC     Expense_CAD = SOURCE.Expense_CAD,
# MAGIC     Expense_USD = SOURCE.Expense_USD,
# MAGIC     Financial_Period_Year = SOURCE.Financial_Period_Year,
# MAGIC     GreenScreen_Rate_CAD = SOURCE.GreenScreen_Rate_CAD,
# MAGIC     GreenScreen_Rate_USD = SOURCE.GreenScreen_Rate_USD,
# MAGIC     Invoice_Amount_CAD = SOURCE.Invoice_Amount_CAD,
# MAGIC     Invoice_Amount_USD = SOURCE.Invoice_Amount_USD,
# MAGIC     Invoiced_Date = SOURCE.Invoiced_Date,
# MAGIC     Lawson_ID = SOURCE.Lawson_ID,
# MAGIC     Load_Currency = SOURCE.Load_Currency,
# MAGIC     Load_Flag = SOURCE.Load_Flag,
# MAGIC     Load_Lane = SOURCE.Load_Lane,
# MAGIC     Load_Status = SOURCE.Load_Status,
# MAGIC     Load_Unload_Charges_Carrier_CAD = SOURCE.Load_Unload_Charges_Carrier_CAD,
# MAGIC     Load_Unload_Charges_Carrier_USD = SOURCE.Load_Unload_Charges_Carrier_USD,
# MAGIC     Load_Unload_Charges_Customer_CAD = SOURCE.Load_Unload_Charges_Customer_CAD,
# MAGIC     Load_Unload_Charges_Customer_USD = SOURCE.Load_Unload_Charges_Customer_USD,
# MAGIC     Margin_CAD = SOURCE.Margin_CAD,
# MAGIC     Margin_USD = SOURCE.Margin_USD,
# MAGIC     Market_Buy_Rate_CAD = SOURCE.Market_Buy_Rate_CAD,
# MAGIC     Market_Buy_Rate_USD = SOURCE.Market_Buy_Rate_USD,
# MAGIC     Market_Destination = SOURCE.Market_Destination,
# MAGIC     Market_Lane = SOURCE.Market_Lane,
# MAGIC     Market_Origin = SOURCE.Market_Origin,
# MAGIC     MC_Number = SOURCE.MC_Number,
# MAGIC     Miles = SOURCE.Miles,
# MAGIC     Miscellaneous_Chargers_Carrier_CAD = SOURCE.Miscellaneous_Chargers_Carrier_CAD,
# MAGIC     Miscellaneous_Chargers_Carrier_USD = SOURCE.Miscellaneous_Chargers_Carrier_USD,
# MAGIC     Miscellaneous_Chargers_Customers_CAD = SOURCE.Miscellaneous_Chargers_Customers_CAD,
# MAGIC     Miscellaneous_Chargers_Customers_USD = SOURCE.Miscellaneous_Chargers_Customers_USD,
# MAGIC     Mode = SOURCE.Mode,
# MAGIC     On_Time_Delivery = SOURCE.On_Time_Delivery,
# MAGIC     On_Time_Pickup = SOURCE.On_Time_Pickup,
# MAGIC     Origin_City = SOURCE.Origin_City,
# MAGIC     Origin_State = SOURCE.Origin_State,
# MAGIC     Origin_Zip = SOURCE.Origin_Zip,
# MAGIC     Permits_Compliance_Charges_Carrier_CAD = SOURCE.Permits_Compliance_Charges_Carrier_CAD,
# MAGIC     Permits_Compliance_Charges_Carrier_USD = SOURCE.Permits_Compliance_Charges_Carrier_USD,
# MAGIC     Permits_Compliance_Charges_Customer_CAD = SOURCE.Permits_Compliance_Charges_Customer_CAD,
# MAGIC     Permits_Compliance_Charges_Customer_USD = SOURCE.Permits_Compliance_Charges_Customer_USD,
# MAGIC     Pickup_Appointment_Date = SOURCE.Pickup_Appointment_Date,
# MAGIC     Actual_Pickup_Date = SOURCE.Actual_Pickup_Date,
# MAGIC     Pickup_EndDate = SOURCE.Pickup_EndDate,
# MAGIC     Pickup_StartDate = SOURCE.Pickup_StartDate,
# MAGIC     PO_Number = SOURCE.PO_Number,
# MAGIC     PreBookStatus = SOURCE.PreBookStatus,
# MAGIC     Revenue_CAD = SOURCE.Revenue_CAD,
# MAGIC     Revenue_USD = SOURCE.Revenue_USD,
# MAGIC     Rolled_Date = SOURCE.Rolled_Date,
# MAGIC     Sales_Rep_ID = SOURCE.Sales_Rep_ID,
# MAGIC     Sales_Rep = SOURCE.Sales_Rep,
# MAGIC     Ship_Date = SOURCE.Ship_Date,
# MAGIC     Spot_Margin = SOURCE.Spot_Margin,
# MAGIC     Spot_Revenue = SOURCE.Spot_Revenue,
# MAGIC     Tender_Source_Type = SOURCE.Tender_Source_Type,
# MAGIC     Tendered_Date = SOURCE.Tendered_Date,
# MAGIC     TMS_System = SOURCE.TMS_System,
# MAGIC     Trailer_Number = SOURCE.Trailer_Number,
# MAGIC     Transit_Routing_Chargers_Carrier_CAD = SOURCE.Transit_Routing_Chargers_Carrier_CAD,
# MAGIC     Transit_Routing_Chargers_Carrier_USD = SOURCE.Transit_Routing_Chargers_Carrier_USD,
# MAGIC     Transit_Routing_Chargers_Customer_CAD = SOURCE.Transit_Routing_Chargers_Customer_CAD,
# MAGIC     Transit_Routing_Chargers_Customer_USD = SOURCE.Transit_Routing_Chargers_Customer_USD,
# MAGIC     Week_Number = SOURCE.Week_Number,
# MAGIC     Hashkey = Source.Hashkey,
# MAGIC     Last_Modified_Date = current_timestamp(),
# MAGIC     Last_Modified_By = 'Databricks',
# MAGIC     Is_Deleted = 0
# MAGIC
# MAGIC WHEN NOT MATCHED THEN 
# MAGIC INSERT (
# MAGIC     DW_Load_ID,
# MAGIC     Load_Number,
# MAGIC     Admin_Fees_Carrier_USD,
# MAGIC     Admin_Fees_Carrier_CAD,
# MAGIC     Admin_Fees_Customer_USD,
# MAGIC     Admin_Fees_Customer_CAD,
# MAGIC     Billing_Status,
# MAGIC     Actual_Delivered_Date,
# MAGIC     Booking_Type,
# MAGIC     Booked_Date,
# MAGIC     Carrier_Fuel_Surcharge_CAD,
# MAGIC     Carrier_Fuel_Surcharge_USD,
# MAGIC     Carrier_Linehaul_CAD,
# MAGIC     Carrier_Linehaul_USD,
# MAGIC     Carrier_ID,
# MAGIC     Carrier_Name,
# MAGIC     Carrier_New_Office,
# MAGIC     Carrier_Old_Office,
# MAGIC     Carrier_Other_Fees_CAD,
# MAGIC     Carrier_Other_Fees_USD,
# MAGIC     Carrier_Rep_ID,
# MAGIC     Carrier_Rep,
# MAGIC     Combined_Load,
# MAGIC     Consignee_Delivery_Address,
# MAGIC     Consignee_Name,
# MAGIC     Consignee_Pickup_Address,
# MAGIC     Customer_Fuel_Surcharge_USD,
# MAGIC     Customer_Fule_Surcharge_CAD,
# MAGIC     Customer_Linehaul_CAD,
# MAGIC     Customer_Linehaul_USD,
# MAGIC     Customer_Master,
# MAGIC     Customer_ID,
# MAGIC     Customer_Name,
# MAGIC     Customer_New_Office,
# MAGIC     Customer_Old_Office,
# MAGIC     Customer_Other_Fees_CAD,
# MAGIC     Customer_Other_Fees_USD,
# MAGIC     Customer_Rep_ID,
# MAGIC     Customer_Rep,
# MAGIC     Days_Ahead,
# MAGIC     Bounced_Date,
# MAGIC     Cancelled_Date,
# MAGIC     Delivery_Pickup_Charges_Carrier_CAD,
# MAGIC     Delivery_Pickup_Charges_Carrier_USD,
# MAGIC     Delivery_Pickup_Charges_Customer_CAD,
# MAGIC     Delivery_Pickup_Charges_Customer_USD,
# MAGIC     Delivery_Appointment_Date,
# MAGIC     Delivery_EndDate,
# MAGIC     Destination_City,
# MAGIC     Destination_State,
# MAGIC     Destination_Zip,
# MAGIC     DOT_Number,
# MAGIC     Delivery_StartDate,
# MAGIC     Equipment,
# MAGIC     Equipment_Vehicle_Charges_Carrier_CAD,
# MAGIC     Equipment_Vehicle_Charges_Carrier_USD,
# MAGIC     Equipment_Vehicle_Charges_Customer_CAD,
# MAGIC     Equipment_Vehicle_Charges_Customer_USD,
# MAGIC     Expense_CAD,
# MAGIC     Expense_USD,
# MAGIC     Financial_Period_Year,
# MAGIC     GreenScreen_Rate_CAD,
# MAGIC     GreenScreen_Rate_USD,
# MAGIC     Invoice_Amount_CAD,
# MAGIC     Invoice_Amount_USD,
# MAGIC     Invoiced_Date,
# MAGIC     Lawson_ID,
# MAGIC     Load_Currency,
# MAGIC     Load_Flag,
# MAGIC     Load_Lane,
# MAGIC     Load_Status,
# MAGIC     Load_Unload_Charges_Carrier_CAD,
# MAGIC     Load_Unload_Charges_Carrier_USD,
# MAGIC     Load_Unload_Charges_Customer_CAD,
# MAGIC     Load_Unload_Charges_Customer_USD,
# MAGIC     Margin_CAD,
# MAGIC     Margin_USD,
# MAGIC     Market_Buy_Rate_CAD,
# MAGIC     Market_Buy_Rate_USD,
# MAGIC     Market_Destination,
# MAGIC     Market_Lane,
# MAGIC     Market_Origin,
# MAGIC     MC_Number,
# MAGIC     Miles,
# MAGIC     Miscellaneous_Chargers_Carrier_CAD,
# MAGIC     Miscellaneous_Chargers_Carrier_USD,
# MAGIC     Miscellaneous_Chargers_Customers_CAD,
# MAGIC     Miscellaneous_Chargers_Customers_USD,
# MAGIC     Mode,
# MAGIC     On_Time_Delivery,
# MAGIC     On_Time_Pickup,
# MAGIC     Origin_City,
# MAGIC     Origin_State,
# MAGIC     Origin_Zip,
# MAGIC     Permits_Compliance_Charges_Carrier_CAD,
# MAGIC     Permits_Compliance_Charges_Carrier_USD,
# MAGIC     Permits_Compliance_Charges_Customer_CAD,
# MAGIC     Permits_Compliance_Charges_Customer_USD,
# MAGIC     Pickup_Appointment_Date,
# MAGIC     Actual_Pickup_Date,
# MAGIC     Pickup_EndDate,
# MAGIC     Pickup_StartDate,
# MAGIC     PO_Number,
# MAGIC     PreBookStatus,
# MAGIC     Revenue_CAD,
# MAGIC     Revenue_USD,
# MAGIC     Rolled_Date,
# MAGIC     Sales_Rep_ID,
# MAGIC     Sales_Rep,
# MAGIC     Ship_Date,
# MAGIC     Spot_Margin,
# MAGIC     Spot_Revenue,
# MAGIC     Tender_Source_Type,
# MAGIC     Tendered_Date,
# MAGIC     TMS_System,
# MAGIC     Trailer_Number,
# MAGIC     Transit_Routing_Chargers_Carrier_CAD,
# MAGIC     Transit_Routing_Chargers_Carrier_USD,
# MAGIC     Transit_Routing_Chargers_Customer_CAD,
# MAGIC     Transit_Routing_Chargers_Customer_USD,
# MAGIC     Week_Number,
# MAGIC     hashkey,
# MAGIC     Created_Date,
# MAGIC     Created_By,
# MAGIC     Last_Modified_Date,
# MAGIC     Last_Modified_By,
# MAGIC     Is_Deleted
# MAGIC )
# MAGIC VALUES (
# MAGIC     SOURCE.DW_Load_ID,
# MAGIC     SOURCE.Load_Number,
# MAGIC     SOURCE.Admin_Fees_Carrier_USD,
# MAGIC     SOURCE.Admin_Fees_Carrier_CAD,
# MAGIC     SOURCE.Admin_Fees_Customer_USD,
# MAGIC     SOURCE.Admin_Fees_Customer_CAD,
# MAGIC     SOURCE.Billing_Status,
# MAGIC     SOURCE.Actual_Delivered_Date,
# MAGIC     SOURCE.Booking_Type,
# MAGIC     SOURCE.Booked_Date,
# MAGIC     SOURCE.Carrier_Fuel_Surcharge_CAD,
# MAGIC     SOURCE.Carrier_Fuel_Surcharge_USD,
# MAGIC     SOURCE.Carrier_Linehaul_CAD,
# MAGIC     SOURCE.Carrier_Linehaul_USD,
# MAGIC     SOURCE.Carrier_ID,
# MAGIC     SOURCE.Carrier_Name,
# MAGIC     SOURCE.Carrier_New_Office,
# MAGIC     SOURCE.Carrier_Old_Office,
# MAGIC     SOURCE.Carrier_Other_Fees_CAD,
# MAGIC     SOURCE.Carrier_Other_Fees_USD,
# MAGIC     SOURCE.Carrier_Rep_ID,
# MAGIC     SOURCE.Carrier_Rep,
# MAGIC     SOURCE.Combined_Load,
# MAGIC     SOURCE.Consignee_Delivery_Address,
# MAGIC     SOURCE.Consignee_Name,
# MAGIC     SOURCE.Consignee_Pickup_Address,
# MAGIC     SOURCE.Customer_Fuel_Surcharge_USD,
# MAGIC     SOURCE.Customer_Fule_Surcharge_CAD,
# MAGIC     SOURCE.Customer_Linehaul_CAD,
# MAGIC     SOURCE.Customer_Linehaul_USD,
# MAGIC     SOURCE.Customer_Master,
# MAGIC     SOURCE.Customer_ID,
# MAGIC     SOURCE.Customer_Name,
# MAGIC     SOURCE.Customer_New_Office,
# MAGIC     SOURCE.Customer_Old_Office,
# MAGIC     SOURCE.Customer_Other_Fees_CAD,
# MAGIC     SOURCE.Customer_Other_Fees_USD,
# MAGIC     SOURCE.Customer_Rep_ID,
# MAGIC     SOURCE.Customer_Rep,
# MAGIC     SOURCE.Days_Ahead,
# MAGIC     SOURCE.Bounced_Date,
# MAGIC     SOURCE.Cancelled_Date,
# MAGIC     SOURCE.Delivery_Pickup_Charges_Carrier_CAD,
# MAGIC     SOURCE.Delivery_Pickup_Charges_Carrier_USD,
# MAGIC     SOURCE.Delivery_Pickup_Charges_Customer_CAD,
# MAGIC     SOURCE.Delivery_Pickup_Charges_Customer_USD,
# MAGIC     SOURCE.Delivery_Appointment_Date,
# MAGIC     SOURCE.Delivery_EndDate,
# MAGIC     SOURCE.Destination_City,
# MAGIC     SOURCE.Destination_State,
# MAGIC     SOURCE.Destination_Zip,
# MAGIC     SOURCE.DOT_Number,
# MAGIC     SOURCE.Delivery_StartDate,
# MAGIC     SOURCE.Equipment,
# MAGIC     SOURCE.Equipment_Vehicle_Charges_Carrier_CAD,
# MAGIC     SOURCE.Equipment_Vehicle_Charges_Carrier_USD,
# MAGIC     SOURCE.Equipment_Vehicle_Charges_Customer_CAD,
# MAGIC     SOURCE.Equipment_Vehicle_Charges_Customer_USD,
# MAGIC     SOURCE.Expense_CAD,
# MAGIC     SOURCE.Expense_USD,
# MAGIC     SOURCE.Financial_Period_Year,
# MAGIC     SOURCE.GreenScreen_Rate_CAD,
# MAGIC     SOURCE.GreenScreen_Rate_USD,
# MAGIC     SOURCE.Invoice_Amount_CAD,
# MAGIC     SOURCE.Invoice_Amount_USD,
# MAGIC     SOURCE.Invoiced_Date,
# MAGIC     SOURCE.Lawson_ID,
# MAGIC     SOURCE.Load_Currency,
# MAGIC     SOURCE.Load_Flag,
# MAGIC     SOURCE.Load_Lane,
# MAGIC     SOURCE.Load_Status,
# MAGIC     SOURCE.Load_Unload_Charges_Carrier_CAD,
# MAGIC     SOURCE.Load_Unload_Charges_Carrier_USD,
# MAGIC     SOURCE.Load_Unload_Charges_Customer_CAD,
# MAGIC     SOURCE.Load_Unload_Charges_Customer_USD,
# MAGIC     SOURCE.Margin_CAD,
# MAGIC     SOURCE.Margin_USD,
# MAGIC     SOURCE.Market_Buy_Rate_CAD,
# MAGIC     SOURCE.Market_Buy_Rate_USD,
# MAGIC     SOURCE.Market_Destination,
# MAGIC     SOURCE.Market_Lane,
# MAGIC     SOURCE.Market_Origin,
# MAGIC     SOURCE.MC_Number,
# MAGIC     SOURCE.Miles,
# MAGIC     SOURCE.Miscellaneous_Chargers_Carrier_CAD,
# MAGIC     SOURCE.Miscellaneous_Chargers_Carrier_USD,
# MAGIC     SOURCE.Miscellaneous_Chargers_Customers_CAD,
# MAGIC     SOURCE.Miscellaneous_Chargers_Customers_USD,
# MAGIC     SOURCE.Mode,
# MAGIC     SOURCE.On_Time_Delivery,
# MAGIC     SOURCE.On_Time_Pickup,
# MAGIC     SOURCE.Origin_City,
# MAGIC     SOURCE.Origin_State,
# MAGIC     SOURCE.Origin_Zip,
# MAGIC     SOURCE.Permits_Compliance_Charges_Carrier_CAD,
# MAGIC     SOURCE.Permits_Compliance_Charges_Carrier_USD,
# MAGIC     SOURCE.Permits_Compliance_Charges_Customer_CAD,
# MAGIC     SOURCE.Permits_Compliance_Charges_Customer_USD,
# MAGIC     SOURCE.Pickup_Appointment_Date,
# MAGIC     SOURCE.Actual_Pickup_Date,
# MAGIC     SOURCE.Pickup_EndDate,
# MAGIC     SOURCE.Pickup_StartDate,
# MAGIC     SOURCE.PO_Number,
# MAGIC     SOURCE.PreBookStatus,
# MAGIC     SOURCE.Revenue_CAD,
# MAGIC     SOURCE.Revenue_USD,
# MAGIC     SOURCE.Rolled_Date,
# MAGIC     SOURCE.Sales_Rep_ID,
# MAGIC     SOURCE.Sales_Rep,
# MAGIC     SOURCE.Ship_Date,
# MAGIC     SOURCE.Spot_Margin,
# MAGIC     SOURCE.Spot_Revenue,
# MAGIC     SOURCE.Tender_Source_Type,
# MAGIC     SOURCE.Tendered_Date,
# MAGIC     SOURCE.TMS_System,
# MAGIC     SOURCE.Trailer_Number,
# MAGIC     SOURCE.Transit_Routing_Chargers_Carrier_CAD,
# MAGIC     SOURCE.Transit_Routing_Chargers_Carrier_USD,
# MAGIC     SOURCE.Transit_Routing_Chargers_Customer_CAD,
# MAGIC     SOURCE.Transit_Routing_Chargers_Customer_USD,
# MAGIC     SOURCE.Week_Number,
# MAGIC     Source.Hashkey,
# MAGIC     current_timestamp(),
# MAGIC     'Databricks',
# MAGIC     current_timestamp(),
# MAGIC     'Databricks',
# MAGIC     0
# MAGIC );
# MAGIC

# COMMAND ----------

# MAGIC %md
# MAGIC ####Update Is_Deleted 

# COMMAND ----------

# MAGIC %sql
# MAGIC UPDATE Gold.fact_loads_by_billing SET Is_Deleted = 1, Last_Modified_Date = current_timestamp() WHERE Is_Deleted = 0 AND DW_Load_ID NOT IN (SELECT DW_Load_ID FROM Gold.vw_fact_loads_by_billing_full_load);

# COMMAND ----------

# MAGIC %md
# MAGIC ####Update theRun Status

# COMMAND ----------

# MAGIC %sql
# MAGIC UPDATE metadata.mastermetadata 
# MAGIC SET PipelineEndTime = current_timestamp(),
# MAGIC LastLoadDateValue = (SELECT MAX(Last_Modified_Date) FROM Gold.Fact_Loads_By_Billing WHERE Is_Deleted=0),
# MAGIC PipelineRunStatus = 'Success'
# MAGIC WHERE TableID = 'GL1'