# Databricks notebook source
# MAGIC %md
# MAGIC ## Loads Split
# MAGIC * **Description:** Full Load from Bronze to Silver as delta file
# MAGIC * **Created Date:** 03/07/2025
# MAGIC * **Created By:** Uday
# MAGIC * **Modified Date:** 06/10/2025
# MAGIC * **Modified By:** Uday
# MAGIC * **Changes Made:** Logic Update

# COMMAND ----------

# MAGIC %md
# MAGIC ####Update Pipeline Update

# COMMAND ----------

# MAGIC %sql
# MAGIC UPDATE metadata.mastermetadata 
# MAGIC SET PipelineEndTime = current_timestamp()
# MAGIC WHERE TableID = 'GL2'

# COMMAND ----------

# MAGIC %md
# MAGIC ####Load the Data

# COMMAND ----------

# MAGIC %sql
# MAGIC MERGE INTO Gold.Fact_Loads_Split AS target
# MAGIC USING Gold.VW_Fact_Loads_Split_Full_Load AS source
# MAGIC ON target.DW_Load_ID = source.DW_Load_ID
# MAGIC
# MAGIC WHEN MATCHED AND target.Hashkey <> source.Hashkey THEN
# MAGIC     UPDATE SET
# MAGIC         Load_Counter = source.Load_Counter,
# MAGIC         Load_Number = source.Load_Number,
# MAGIC         Admin_Fees_Carrier = source.Admin_Fees_Carrier,
# MAGIC         Admin_Fees_Customer = source.Admin_Fees_Customer,
# MAGIC         Billing_Status = source.Billing_Status,
# MAGIC         Actual_Delivered_Date = source.Actual_Delivered_Date,
# MAGIC         Booking_Type = source.Booking_Type,
# MAGIC         Booked_Date = source.Booked_Date,
# MAGIC         Carrier_Fuel_Surcharge = source.Carrier_Fuel_Surcharge,
# MAGIC         Carrier_linehaul = source.Carrier_linehaul,
# MAGIC         Office_Type = source.Office_Type,
# MAGIC         Office = Source.Office,
# MAGIC         Carrier_ID = source.Carrier_ID,
# MAGIC         Carrier_Name = source.Carrier_Name,
# MAGIC         Carrier_Other_Fees = source.Carrier_Other_Fees,
# MAGIC         Carrier_Rep_ID = source.Carrier_Rep_ID,
# MAGIC         Carrier_Rep = source.Carrier_Rep,
# MAGIC         Combined_Load = source.Combined_Load,
# MAGIC         Consignee_Delivery_Address = source.Consignee_Delivery_Address,
# MAGIC         Consignee_Name = source.Consignee_Name,
# MAGIC         Consignee_Pickup_Address = source.Consignee_Pickup_Address,
# MAGIC         Customer_Fuel_Surcharge = source.Customer_Fuel_Surcharge,
# MAGIC         Customer_linehaul = source.Customer_linehaul,
# MAGIC         Customer_Master = source.Customer_Master,
# MAGIC         Customer_ID = source.Customer_ID,
# MAGIC         Customer_Name = source.Customer_Name,
# MAGIC         Customer_Other_Fees = source.Customer_Other_Fees,
# MAGIC         Customer_Rep_ID = source.Customer_Rep_ID,
# MAGIC         Customer_Rep = source.Customer_Rep,
# MAGIC         Days_Ahead = source.Days_Ahead,
# MAGIC         Bounced_Date = source.Bounced_Date,
# MAGIC         Cancelled_Date = source.Cancelled_Date,
# MAGIC         Delivery_Pickup_Charges_Carrier = source.Delivery_Pickup_Charges_Carrier,
# MAGIC         Delivery_Pickup_Charges_Customer = source.Delivery_Pickup_Charges_Customer,
# MAGIC         Delivery_Appointment_Date = source.Delivery_Appointment_Date,
# MAGIC         Delivery_EndDate = source.Delivery_EndDate,
# MAGIC         Destination_City = source.Destination_City,
# MAGIC         Destination_State = source.Destination_State,
# MAGIC         Destination_Zip = source.Destination_Zip,
# MAGIC         DOT_Number = source.DOT_Number,
# MAGIC         Delivery_StartDate = source.Delivery_StartDate,
# MAGIC         Equipment = source.Equipment,
# MAGIC         Equipment_Vehicle_Charges_Carrier = source.Equipment_Vehicle_Charges_Carrier,
# MAGIC         Equipment_Vehicle_Charges_Customer = source.Equipment_Vehicle_Charges_Customer,
# MAGIC         Expense = source.Expense,
# MAGIC         Financial_Period_Year = source.Financial_Period_Year,
# MAGIC         GreenScreen_Rate = source.GreenScreen_Rate,
# MAGIC         Invoice_Amount = source.Invoice_Amount,
# MAGIC         Invoiced_Date = source.Invoiced_Date,
# MAGIC         Lawson_ID = source.Lawson_ID,
# MAGIC         Load_Currency = source.Load_Currency,
# MAGIC         Load_Flag = source.Load_Flag,
# MAGIC         Load_Lane = source.Load_Lane,
# MAGIC         Load_Status = source.Load_Status,
# MAGIC         Load_Unload_Charges_Carrier = source.Load_Unload_Charges_Carrier,
# MAGIC         Load_Unload_Charges_Customer = source.Load_Unload_Charges_Customer,
# MAGIC         Margin = source.Margin,
# MAGIC         Market_Buy_Rate = source.Market_Buy_Rate,
# MAGIC         Market_Destination = source.Market_Destination,
# MAGIC         Market_Lane = source.Market_Lane,
# MAGIC         Market_Origin = source.Market_Origin,
# MAGIC         MC_Number = source.MC_Number,
# MAGIC         Miles = source.Miles,
# MAGIC         Miscellaneous_Chargers_Carrier = source.Miscellaneous_Chargers_Carrier,
# MAGIC         Miscellaneous_Chargers_Customers = source.Miscellaneous_Chargers_Customers,
# MAGIC         Mode = source.Mode,
# MAGIC         On_Time_Delivery = source.On_Time_Delivery,
# MAGIC         On_Time_Pickup = source.On_Time_Pickup,
# MAGIC         Origin_City = source.Origin_City,
# MAGIC         Origin_State = source.Origin_State,
# MAGIC         Origin_Zip = source.Origin_Zip,
# MAGIC         Permits_Compliance_Charges_Carrier = source.Permits_Compliance_Charges_Carrier,
# MAGIC         Permits_Compliance_Charges_Customer = source.Permits_Compliance_Charges_Customer,
# MAGIC         Pickup_Appointment_Date = source.Pickup_Appointment_Date,
# MAGIC         Actual_Pickup_Date = source.Actual_Pickup_Date,
# MAGIC         Pickup_EndDate = source.Pickup_EndDate,
# MAGIC         Pickup_StartDate = source.Pickup_StartDate,
# MAGIC         PO_Number = source.PO_Number,
# MAGIC         PreBookStatus = source.PreBookStatus,
# MAGIC         Revenue = source.Revenue,
# MAGIC         Rolled_Date = source.Rolled_Date,
# MAGIC         Sales_Rep_ID = source.Sales_Rep_ID,
# MAGIC         Sales_Rep = source.Sales_Rep,
# MAGIC         Ship_Date = source.Ship_Date,
# MAGIC         Spot_Margin = source.Spot_Margin,
# MAGIC         Spot_Revenue = source.Spot_Revenue,
# MAGIC         Tender_Source_Type = source.Tender_Source_Type,
# MAGIC         Tendered_Date = source.Tendered_Date,
# MAGIC         TMS_System = source.TMS_System,
# MAGIC         Trailer_Number = source.Trailer_Number,
# MAGIC         Transit_Routing_Chargers_Carrier = source.Transit_Routing_Chargers_Carrier,
# MAGIC         Transit_Routing_Chargers_Customer = source.Transit_Routing_Chargers_Customer,
# MAGIC         Week_Number = source.Week_Number,
# MAGIC         Hashkey = source.Hashkey,
# MAGIC         Last_Modified_Date = CURRENT_TIMESTAMP,
# MAGIC         Last_Modified_By = 'Databricks',
# MAGIC         Is_Deleted = 0
# MAGIC
# MAGIC WHEN NOT MATCHED THEN
# MAGIC     INSERT (
# MAGIC         DW_Load_ID,
# MAGIC         Load_Counter,
# MAGIC         Load_Number,
# MAGIC         Admin_Fees_Carrier,
# MAGIC         Admin_Fees_Customer,
# MAGIC         Billing_Status,
# MAGIC         Actual_Delivered_Date,
# MAGIC         Booking_Type,
# MAGIC         Booked_Date,
# MAGIC         Carrier_Fuel_Surcharge,
# MAGIC         Carrier_linehaul,
# MAGIC         Office_Type,
# MAGIC         Office,
# MAGIC         Carrier_ID,
# MAGIC         Carrier_Name,
# MAGIC         Carrier_Other_Fees,
# MAGIC         Carrier_Rep_ID,
# MAGIC         Carrier_Rep,
# MAGIC         Combined_Load,
# MAGIC         Consignee_Delivery_Address,
# MAGIC         Consignee_Name,
# MAGIC         Consignee_Pickup_Address,
# MAGIC         Customer_Fuel_Surcharge,
# MAGIC         Customer_linehaul,
# MAGIC         Customer_Master,
# MAGIC         Customer_ID,
# MAGIC         Customer_Name,
# MAGIC         Customer_Other_Fees,
# MAGIC         Customer_Rep_ID,
# MAGIC         Customer_Rep,
# MAGIC         Days_Ahead,
# MAGIC         Bounced_Date,
# MAGIC         Cancelled_Date,
# MAGIC         Delivery_Pickup_Charges_Carrier,
# MAGIC         Delivery_Pickup_Charges_Customer,
# MAGIC         Delivery_Appointment_Date,
# MAGIC         Delivery_EndDate,
# MAGIC         Destination_City,
# MAGIC         Destination_State,
# MAGIC         Destination_Zip,
# MAGIC         DOT_Number,
# MAGIC         Delivery_StartDate,
# MAGIC         Equipment,
# MAGIC         Equipment_Vehicle_Charges_Carrier,
# MAGIC         Equipment_Vehicle_Charges_Customer,
# MAGIC         Expense,
# MAGIC         Financial_Period_Year,
# MAGIC         GreenScreen_Rate,
# MAGIC         Invoice_Amount,
# MAGIC         Invoiced_Date,
# MAGIC         Lawson_ID,
# MAGIC         Load_Currency,
# MAGIC         Load_Flag,
# MAGIC         Load_Lane,
# MAGIC         Load_Status,
# MAGIC         Load_Unload_Charges_Carrier,
# MAGIC         Load_Unload_Charges_Customer,
# MAGIC         Margin,
# MAGIC         Market_Buy_Rate,
# MAGIC         Market_Destination,
# MAGIC         Market_Lane,
# MAGIC         Market_Origin,
# MAGIC         MC_Number,
# MAGIC         Miles,
# MAGIC         Miscellaneous_Chargers_Carrier,
# MAGIC         Miscellaneous_Chargers_Customers,
# MAGIC         Mode,
# MAGIC         On_Time_Delivery,
# MAGIC         On_Time_Pickup,
# MAGIC         Origin_City,
# MAGIC         Origin_State,
# MAGIC         Origin_Zip,
# MAGIC         Permits_Compliance_Charges_Carrier,
# MAGIC         Permits_Compliance_Charges_Customer,
# MAGIC         Pickup_Appointment_Date,
# MAGIC         Actual_Pickup_Date,
# MAGIC         Pickup_EndDate,
# MAGIC         Pickup_StartDate,
# MAGIC         PO_Number,
# MAGIC         PreBookStatus,
# MAGIC         Revenue,
# MAGIC         Rolled_Date,
# MAGIC         Sales_Rep_ID,
# MAGIC         Sales_Rep,
# MAGIC         Ship_Date,
# MAGIC         Spot_Margin,
# MAGIC         Spot_Revenue,
# MAGIC         Tender_Source_Type,
# MAGIC         Tendered_Date,
# MAGIC         TMS_System,
# MAGIC         Trailer_Number,
# MAGIC         Transit_Routing_Chargers_Carrier,
# MAGIC         Transit_Routing_Chargers_Customer,
# MAGIC         Week_Number,
# MAGIC         Hashkey,
# MAGIC         Created_Date,
# MAGIC         Created_By,
# MAGIC         Last_Modified_Date,
# MAGIC         Last_Modified_By,
# MAGIC         Is_Deleted
# MAGIC     )
# MAGIC     VALUES (
# MAGIC         source.DW_Load_ID,
# MAGIC         source.Load_Counter,
# MAGIC         source.Load_Number,
# MAGIC         source.Admin_Fees_Carrier,
# MAGIC         source.Admin_Fees_Customer,
# MAGIC         source.Billing_Status,
# MAGIC         source.Actual_Delivered_Date,
# MAGIC         source.Booking_Type,
# MAGIC         source.Booked_Date,
# MAGIC         source.Carrier_Fuel_Surcharge,
# MAGIC         source.Carrier_linehaul,
# MAGIC         source.Office_Type,
# MAGIC         source.Office,
# MAGIC         source.Carrier_ID,
# MAGIC         source.Carrier_Name,
# MAGIC         source.Carrier_Other_Fees,
# MAGIC         source.Carrier_Rep_ID,
# MAGIC         source.Carrier_Rep,
# MAGIC         source.Combined_Load,
# MAGIC         source.Consignee_Delivery_Address,
# MAGIC         source.Consignee_Name,
# MAGIC         source.Consignee_Pickup_Address,
# MAGIC         source.Customer_Fuel_Surcharge,
# MAGIC         source.Customer_linehaul,
# MAGIC         source.Customer_Master,
# MAGIC         source.Customer_ID,
# MAGIC         source.Customer_Name,
# MAGIC         source.Customer_Other_Fees,
# MAGIC         source.Customer_Rep_ID,
# MAGIC         source.Customer_Rep,
# MAGIC         source.Days_Ahead,
# MAGIC         source.Bounced_Date,
# MAGIC         source.Cancelled_Date,
# MAGIC         source.Delivery_Pickup_Charges_Carrier,
# MAGIC         source.Delivery_Pickup_Charges_Customer,
# MAGIC         source.Delivery_Appointment_Date,
# MAGIC         source.Delivery_EndDate,
# MAGIC         source.Destination_City,
# MAGIC         source.Destination_State,
# MAGIC         source.Destination_Zip,
# MAGIC         source.DOT_Number,
# MAGIC         source.Delivery_StartDate,
# MAGIC         source.Equipment,
# MAGIC         source.Equipment_Vehicle_Charges_Carrier,
# MAGIC         source.Equipment_Vehicle_Charges_Customer,
# MAGIC         source.Expense,
# MAGIC         source.Financial_Period_Year,
# MAGIC         source.GreenScreen_Rate,
# MAGIC         source.Invoice_Amount,
# MAGIC         source.Invoiced_Date,
# MAGIC         source.Lawson_ID,
# MAGIC         source.Load_Currency,
# MAGIC         source.Load_Flag,
# MAGIC         source.Load_Lane,
# MAGIC         source.Load_Status,
# MAGIC         source.Load_Unload_Charges_Carrier,
# MAGIC         source.Load_Unload_Charges_Customer,
# MAGIC         source.Margin,
# MAGIC         source.Market_Buy_Rate,
# MAGIC         source.Market_Destination,
# MAGIC         source.Market_Lane,
# MAGIC         source.Market_Origin,
# MAGIC         source.MC_Number,
# MAGIC         source.Miles,
# MAGIC         source.Miscellaneous_Chargers_Carrier,
# MAGIC         source.Miscellaneous_Chargers_Customers,
# MAGIC         source.Mode,
# MAGIC         source.On_Time_Delivery,
# MAGIC         source.On_Time_Pickup,
# MAGIC         source.Origin_City,
# MAGIC         source.Origin_State,
# MAGIC         source.Origin_Zip,
# MAGIC         source.Permits_Compliance_Charges_Carrier,
# MAGIC         source.Permits_Compliance_Charges_Customer,
# MAGIC         source.Pickup_Appointment_Date,
# MAGIC         source.Actual_Pickup_Date,
# MAGIC         source.Pickup_EndDate,
# MAGIC         source.Pickup_StartDate,
# MAGIC         source.PO_Number,
# MAGIC         source.PreBookStatus,
# MAGIC         source.Revenue,
# MAGIC         source.Rolled_Date,
# MAGIC         source.Sales_Rep_ID,
# MAGIC         source.Sales_Rep,
# MAGIC         source.Ship_Date,
# MAGIC         source.Spot_Margin,
# MAGIC         source.Spot_Revenue,
# MAGIC         source.Tender_Source_Type,
# MAGIC         source.Tendered_Date,
# MAGIC         source.TMS_System,
# MAGIC         source.Trailer_Number,
# MAGIC         source.Transit_Routing_Chargers_Carrier,
# MAGIC         source.Transit_Routing_Chargers_Customer,
# MAGIC         source.Week_Number,
# MAGIC         source.Hashkey,
# MAGIC         CURRENT_TIMESTAMP,
# MAGIC         'Databricks',
# MAGIC         CURRENT_TIMESTAMP,
# MAGIC         'Databricks',
# MAGIC         0
# MAGIC     );
# MAGIC

# COMMAND ----------

# MAGIC %md
# MAGIC ####Update Is_Deleted

# COMMAND ----------

# MAGIC %sql
# MAGIC UPDATE Gold.fact_loads_split 
# MAGIC SET Is_Deleted = 1, Last_Modified_Date = current_timestamp(), Last_Modified_By = 'Databricks'
# MAGIC WHERE Is_Deleted = 0 AND DW_Load_ID not in (SELECT DW_Load_ID FROM Gold.vw_fact_loads_split_full_load)

# COMMAND ----------

# MAGIC %md
# MAGIC #### Update Run Status

# COMMAND ----------

# MAGIC %sql
# MAGIC UPDATE metadata.mastermetadata 
# MAGIC SET PipelineEndTime = current_timestamp(),
# MAGIC LastLoadDateValue = (SELECT MAX(Last_Modified_Date) FROM Gold.fact_loads_split WHERE Is_Deleted=0),
# MAGIC PipelineRunStatus = 'Success'
# MAGIC WHERE TableID = 'GL2'