# Databricks notebook source
# MAGIC %sql
# MAGIC INSERT INTO
# MAGIC     metadata.MasterMetadata (
# MAGIC     SourceSystem,
# MAGIC     TableID,
# MAGIC     SubjectArea,
# MAGIC     SourceSchema,
# MAGIC     SourceTableName,
# MAGIC     LoadType,
# MAGIC     IsActive,
# MAGIC     Frequency,
# MAGIC     SourceSelectQuery,
# MAGIC     LastLoadDateColumn,
# MAGIC     LastLoadDateValue,
# MAGIC     MergeKey
# MAGIC   )
# MAGIC VALUES
# MAGIC   (
# MAGIC     "Postgres sql",
# MAGIC     "SQ-1",
# MAGIC     "Loads and Quotes",
# MAGIC     "public",
# MAGIC     "spot_quotes",
# MAGIC     "incremental load",
# MAGIC     "1",
# MAGIC     "20 mins once",
# MAGIC     "SELECT
# MAGIC     quote_id,
# MAGIC     shipper_ref_number,
# MAGIC     status,
# MAGIC     status_str,
# MAGIC     created_at,
# MAGIC     quoted_price,
# MAGIC     quote_type,
# MAGIC     load_number,
# MAGIC     last_updated_at,
# MAGIC     margin,
# MAGIC     quote_source_str,
# MAGIC     customer_slug,
# MAGIC     customer_name,
# MAGIC     equipment_name,
# MAGIC     created_by,
# MAGIC     low_buy_predicted,
# MAGIC     target_buy_predicted,
# MAGIC     high_buy_predicted,
# MAGIC     fuel_rate_predicted,
# MAGIC     weight,
# MAGIC     confidence_level,
# MAGIC     miles,
# MAGIC     pc_miler_miles,
# MAGIC     multistop,
# MAGIC     shipper_city,
# MAGIC     shipper_state,
# MAGIC     shipper_zip,
# MAGIC     shipper_country,
# MAGIC     shipper_quote_id,
# MAGIC     intermediate_stop_one_activity_type_str,
# MAGIC     intermediate_stop_one_city,
# MAGIC     intermediate_stop_one_state,
# MAGIC     intermediate_stop_one_postal_code,
# MAGIC     intermediate_stop_one_country,
# MAGIC     intermediate_stop_two_activity_type_str,
# MAGIC     intermediate_stop_two_city,
# MAGIC     intermediate_stop_two_state,
# MAGIC     intermediate_stop_two_postal_code,
# MAGIC     intermediate_stop_two_country,
# MAGIC     receiver_city,
# MAGIC     receiver_state,
# MAGIC     receiver_zip,
# MAGIC     receiver_country,
# MAGIC     receiver_order,
# MAGIC     origin_date,
# MAGIC     dest_date,
# MAGIC     responded_at,
# MAGIC     responded_by,
# MAGIC     profit_center,
# MAGIC     live_handling,
# MAGIC     notes,
# MAGIC     inbound_market_strength,
# MAGIC     outbound_market_strength,
# MAGIC     combined_market_strength,
# MAGIC     request_source,
# MAGIC     commodity,
# MAGIC     team,
# MAGIC     effective_date,
# MAGIC     expiration_date,
# MAGIC     lost_reason,
# MAGIC     is_deleted,
# MAGIC     prediction_rate,
# MAGIC     winning_bid,
# MAGIC     declared_value,
# MAGIC     hazmat,
# MAGIC     ruleset_price_prediction,
# MAGIC     currency,
# MAGIC     transit_time,
# MAGIC     origin_time,
# MAGIC     destination_time,
# MAGIC     customer_tms,
# MAGIC     notifying_channel_id,
# MAGIC     marked_won_by,
# MAGIC     nfi_pricing_contact
# MAGIC FROM
# MAGIC     public.spot_quotes 
# MAGIC WHERE  ""{0}"" >= ",
# MAGIC     "last_updated_at",
# MAGIC     "2000-10-01T10:00:00.000",
# MAGIC     "quote_id");

# COMMAND ----------

# MAGIC %sql
# MAGIC -- # %sql
# MAGIC -- DELETE from metadata.MasterMetadata where TableID = "SQ-1"; 
# MAGIC select * from metadata.MasterMetadata where TableID = "SQ-1";
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE
# MAGIC or replace TABLE Bronze.spot_quotes (
# MAGIC   quote_id BIGINT,
# MAGIC   shipper_ref_number STRING,
# MAGIC   status BIGINT,
# MAGIC   status_str STRING,
# MAGIC   created_at TIMESTAMP,
# MAGIC   quoted_price DOUBLE,
# MAGIC   quote_type STRING,
# MAGIC   load_number STRING,
# MAGIC   last_updated_at TIMESTAMP,
# MAGIC   margin DOUBLE,
# MAGIC   quote_source_str STRING,
# MAGIC   customer_slug STRING,
# MAGIC   customer_name STRING,
# MAGIC   equipment_name STRING,
# MAGIC   created_by STRING,
# MAGIC   low_buy_predicted DOUBLE,
# MAGIC   target_buy_predicted DOUBLE,
# MAGIC   high_buy_predicted DOUBLE,
# MAGIC   fuel_rate_predicted DOUBLE,
# MAGIC   weight DOUBLE,
# MAGIC   confidence_level DOUBLE,
# MAGIC   miles DOUBLE,
# MAGIC   pc_miler_miles DOUBLE,
# MAGIC   multistop STRING,
# MAGIC   shipper_city STRING,
# MAGIC   shipper_state STRING,
# MAGIC   shipper_zip STRING,
# MAGIC   shipper_country STRING,
# MAGIC   shipper_quote_id STRING,
# MAGIC   intermediate_stop_one_activity_type_str STRING,
# MAGIC   intermediate_stop_one_city STRING,
# MAGIC   intermediate_stop_one_state STRING,
# MAGIC   intermediate_stop_one_postal_code STRING,
# MAGIC   intermediate_stop_one_country STRING,
# MAGIC   intermediate_stop_two_activity_type_str STRING,
# MAGIC   intermediate_stop_two_city STRING,
# MAGIC   intermediate_stop_two_state STRING,
# MAGIC   intermediate_stop_two_postal_code STRING,
# MAGIC   intermediate_stop_two_country STRING,
# MAGIC   receiver_city STRING,
# MAGIC   receiver_state STRING,
# MAGIC   receiver_zip STRING,
# MAGIC   receiver_country STRING,
# MAGIC   receiver_order DOUBLE,
# MAGIC   origin_date DATE,
# MAGIC   dest_date DATE,
# MAGIC   responded_at TIMESTAMP,
# MAGIC   responded_by STRING,
# MAGIC   profit_center STRING,
# MAGIC   live_handling BOOLEAN,
# MAGIC   notes STRING,
# MAGIC   inbound_market_strength DOUBLE,
# MAGIC   outbound_market_strength DOUBLE,
# MAGIC   combined_market_strength DOUBLE,
# MAGIC   request_source STRING,
# MAGIC   commodity STRING,
# MAGIC   team BOOLEAN,
# MAGIC   effective_date TIMESTAMP,
# MAGIC   expiration_date TIMESTAMP,
# MAGIC   lost_reason STRING,
# MAGIC   is_deleted BOOLEAN,
# MAGIC   prediction_rate STRING,
# MAGIC   winning_bid DECIMAL(12, 2),
# MAGIC   declared_value DECIMAL(12, 2),
# MAGIC   hazmat BOOLEAN,
# MAGIC   ruleset_price_prediction DECIMAL(12, 2),
# MAGIC   currency VARCHAR(3),
# MAGIC   transit_time INT,
# MAGIC   origin_time TIMESTAMP_NTZ,
# MAGIC   destination_time TIMESTAMP_NTZ,
# MAGIC   customer_tms STRING,
# MAGIC   notifying_channel_id VARCHAR(255),
# MAGIC   marked_won_by STRING,
# MAGIC   nfi_pricing_contact STRING,
# MAGIC   Sourcesystem_ID Int not null,
# MAGIC   Sourcesystem_Name STRING not null,
# MAGIC   CONSTRAINT pk_quote_id PRIMARY KEY (quote_id)
# MAGIC )

# COMMAND ----------

