-- Databricks notebook source
-- MAGIC %python
-- MAGIC ## Mention the catalog used, getting the catalog name from key vault
-- MAGIC CatalogName = dbutils.secrets.get(scope = "Brokerage-Catalog", key = "CatalogName")
-- MAGIC spark.sql(f"USE CATALOG {CatalogName}")

-- COMMAND ----------

INSERT INTO metadata.MasterMetadata (SourceSystem	,
TableID	,
SubjectArea	,
SourceDBName	,
SourceSchema	,
SourceTableName	,
LoadType	,
IsActive	,
Frequency	,
LastLoadDateColumn,
LastLoadDateValue,
MergeKey,
SourceSelectQuery
)
VALUES ("Finance"	,
"F1"	,
"General Ledger"	,
"LSLMDB"	,
"ls_apps"	,
"FINANCE_GLSYSTEM"	,
"incremental load"	,
"1"	,
"24 hrs"	,
"LAST_UPDT_DATE",
"2020-01-01",
"COMPANY",
"select COMPANY,	NAME,	BS_ACCT_UNIT,	NBR_ACCT_PERS,	ACCT_PERIOD,	FISCAL_YEAR,	LST_YR_CLOSED,	PER_END_DATE_01,	PER_END_DATE_02,	PER_END_DATE_03,	PER_END_DATE_04,	PER_END_DATE_05,	PER_END_DATE_06,	PER_END_DATE_07,	PER_END_DATE_08,	PER_END_DATE_09,	PER_END_DATE_10,	PER_END_DATE_11,	PER_END_DATE_12,	PER_END_DATE_13,	PER_END_DATE_14,	PER_END_DATE_15,	PER_END_DATE_16,	PER_END_DATE_17,	PER_END_DATE_18,	PER_END_DATE_19,	PER_END_DATE_20,	PER_END_DATE_21,	PER_END_DATE_22,	PER_END_DATE_23,	PER_END_DATE_24,	PER_END_DATE_25,	PER_END_DATE_26,	PER_END_DATE_27,	PER_END_DATE_28,	PER_END_DATE_29,	PER_END_DATE_30,	PER_END_DATE_31,	PER_END_DATE_32,	PER_END_DATE_33,	PER_END_DATE_34,	PER_END_DATE_35,	PER_END_DATE_36,	PER_END_DATE_37,	PER_END_DATE_38,	PER_END_DATE_39,	PER_END_CODE_01,	PER_END_CODE_02,	PER_END_CODE_03,	PER_END_CODE_04,	PER_END_CODE_05,	PER_END_CODE_06,	PER_END_CODE_07,	PER_END_CODE_08,	PER_END_CODE_09,	PER_END_CODE_10,	PER_END_CODE_11,	PER_END_CODE_12,	PER_END_CODE_13,	PER_END_CODE_14,	PER_END_CODE_15,	PER_END_CODE_16,	PER_END_CODE_17,	PER_END_CODE_18,	PER_END_CODE_19,	PER_END_CODE_20,	PER_END_CODE_21,	PER_END_CODE_22,	PER_END_CODE_23,	PER_END_CODE_24,	PER_END_CODE_25,	PER_END_CODE_26,	PER_END_CODE_27,	PER_END_CODE_28,	PER_END_CODE_29,	PER_END_CODE_30,	PER_END_CODE_31,	PER_END_CODE_32,	PER_END_CODE_33,	PER_END_CODE_34,	PER_END_CODE_35,	PER_END_CODE_36,	PER_END_CODE_37,	PER_END_CODE_38,	PER_END_CODE_39,	CONTROL_CODE,	INTLV_BAL_FLG,	CURRENCY_TABLE,	CURR_CONV_FLG,	CURR_TRAN_FLG,	CURRENCY_CODE,	COMPANY_ND,	IS_ACCT_UNIT,	ACTIVE_STATUS,	AVG_DAILY_BAL,	AUTO_JE_NBR,	LEVEL_DESC_01,	LEVEL_DESC_02,	LEVEL_DESC_03,	LEVEL_DESC_04,	LEVEL_DESC_05,	NBR_DIGITS_01,	NBR_DIGITS_02,	NBR_DIGITS_03,	NBR_DIGITS_04,	NBR_DIGITS_05,	GL190_RUN_DT,	GL190_RUN_TM,	POSTED_TH_DT,	PROJ_ACCT_FLG,	BASE_ZONE,	BACKPOST_01,	BACKPOST_02,	BACKPOST_03,	BACKPOST_04,	BACKPOST_05,	BACKPOST_06,	BACKPOST_07,	BACKPOST_08,	BACKPOST_09,	BACKPOST_10,	BACKPOST_11,	BACKPOST_12,	BACKPOST_13,	BACKPOST_14,	BACKPOST_15,	BACKPOST_16,	BACKPOST_17,	BACKPOST_18,	BACKPOST_19,	BACKPOST_20,	BACKPOST_21,	BACKPOST_22,	BACKPOST_23,	BACKPOST_24,	BACKPOST_25,	BACKPOST_26,	GL150_RUN_DTE,	CHART_NAME,	DEFAULT_PERIOD,	JOURNAL_BY_DOC,	UPDATING,	CLOSE_SEQ_01,	CLOSE_SEQ_02,	CLOSE_SEQ_03,	CLOSE_SEQ_04,	CLOSE_SEQ_05,	CLOSE_SEQ_06,	CLOSE_SEQ_07,	CLOSE_SEQ_08,	CLOSE_SEQ_09,	CLOSE_SEQ_10,	CLOSE_SEQ_11,	CLOSE_SEQ_12,	CLOSE_SEQ_13,	CLOSE_SEQ_14,	CLOSE_SEQ_15,	CLOSE_SEQ_16,	CLOSE_SEQ_17,	CLOSE_SEQ_18,	CLOSE_SEQ_19,	CLOSE_SEQ_20,	CLOSE_SEQ_21,	CLOSE_SEQ_22,	CLOSE_SEQ_23,	CLOSE_SEQ_24,	CLOSE_SEQ_25,	CLOSE_SEQ_26,	CLOSE_SEQ_27,	CLOSE_SEQ_28,	CLOSE_SEQ_29,	CLOSE_SEQ_30,	CLOSE_SEQ_31,	CLOSE_SEQ_32,	CLOSE_SEQ_33,	CLOSE_SEQ_34,	CLOSE_SEQ_35,	CLOSE_SEQ_36,	CLOSE_SEQ_37,	CLOSE_SEQ_38,	CLOSE_SEQ_39,	LEVEL_DEPTH,	JRNL_BOOK_REQ,	SEQ_TRNS_CD,	RESET_SEQ_NBR,	CHG_POST_TRAN,	CHG_REL_TRAN,	ERROR_SP_JBOOK,	YEAR_END_JBOOK,	AUTO_JBK_SEQ,	JE_APPROVE_AMT,	WORKFLOW_FLAG,	CURR_NAME_1,	CURR_CODE_1,	CURR_CODE_ND_1,	CURR_NAME_2,	CURR_CODE_2,	CURR_CODE_ND_2,	AUTO_BASE_BAL,	CURR_RE_FLAG,	BUD_EDIT_RANGE,	BUD_EDIT_TYPE,	FB_UPDATING,	ML_UPDATING,	BUD_TOLERANCE,	BUD_ACT,	CREATED_BY,	LAST_UPDT_DATE,	LAST_UPDT_TIME,	LAST_UPDATE_BY,	Z4_RPT_FLAG,	Z4_MIN_AMT,	TRANS_NBR_LOC from LSLMDB.ls_apps.GLSYSTEM where {0} >=");

-- COMMAND ----------

INSERT INTO metadata.MasterMetadata (SourceSystem	,
TableID	,
SubjectArea	,
SourceDBName	,
SourceSchema	,
SourceTableName	,
LoadType	,
IsActive	,
Frequency	,
LastLoadDateColumn,
LastLoadDateValue,
MergeKey,
SourceSelectQuery
)
VALUES ("Finance"	,
"F2"	,
"General Ledger"	,
"LSLMDB"	,
"ls_apps"	,
"FINANCE_GLCHARTDTL"	,
"incremental load"	,
"1"	,
"24 hrs"	,
"LAST_UPDT_DATE",
"1753-01-01",
"CHART_NAME,SUMRY_ACCT_ID,ACCOUNT,SUB_ACCOUNT",
"select CHART_NAME,SUMRY_ACCT_ID,CHART_SECTION,ACCOUNT,SUB_ACCOUNT,ACCOUNT_DESC,SPACE_CODE,SIGN_CODE,UNITS_CODE,ACTIVITY_REQ,POSTING_LEVEL,CURRENCY_CODE,CURR_CONTROL,TRANSL_CODE,REVALUE,ACTIVE_STATUS,DYNAMIC_LIST,RESTRICT_SYS,ACCT_CATEGORY,DAILY_BALANCE,RELATION,UNARY_OPER,NAT_BALANCE,SL_ACCT_FLAG,OBJ_ID,LEDGER_GROUP,GL_BUD_FL,GL_ACCT_TYPE,XBRL_TAG_ID,CREATED_BY,LAST_UPDT_DATE,LAST_UPDT_TIME,LAST_UPDATE_BY,GDTSET6_SS_SW,GDTSET7_SS_SW from LSLMDB.ls_apps.GLCHARTDTL where {0} >=");

-- COMMAND ----------

INSERT INTO metadata.MasterMetadata (SourceSystem	,
TableID	,
SubjectArea	,
SourceDBName	,
SourceSchema	,
SourceTableName	,
LoadType	,
IsActive	,
Frequency	,
LastLoadDateColumn,
LastLoadDateValue,
MergeKey,
SourceSelectQuery
)
VALUES ("Finance"	,
"F3"	,
"General Ledger"	,
"LSLMDB"	,
"ls_apps"	,
"FINANCE_GLAMOUNTS"	,
"incremental load"	,
"1"	,
"24 hrs"	,
"MAINT_DATE",
"2015-01-01",
"COMPANY,FISCAL_YEAR,ACCT_UNIT,ACCOUNT,SUB_ACCOUNT",
"select COMPANY,FISCAL_YEAR,ACCT_UNIT,ACCOUNT,SUB_ACCOUNT,VAR_LEVELS,CHART_NAME,DB_BEG_BAL,CR_BEG_BAL,DB_AMOUNT_01,DB_AMOUNT_02,DB_AMOUNT_03,DB_AMOUNT_04,DB_AMOUNT_05,DB_AMOUNT_06,DB_AMOUNT_07,DB_AMOUNT_08,DB_AMOUNT_09,DB_AMOUNT_10,DB_AMOUNT_11,DB_AMOUNT_12,DB_AMOUNT_13,CR_AMOUNT_01,CR_AMOUNT_02,CR_AMOUNT_03,CR_AMOUNT_04,CR_AMOUNT_05,CR_AMOUNT_06,CR_AMOUNT_07,CR_AMOUNT_08,CR_AMOUNT_09,CR_AMOUNT_10,CR_AMOUNT_11,CR_AMOUNT_12,CR_AMOUNT_13,ACTIVITY_FLAG_01,ACTIVITY_FLAG_02,ACTIVITY_FLAG_03,ACTIVITY_FLAG_04,ACTIVITY_FLAG_05,ACTIVITY_FLAG_06,ACTIVITY_FLAG_07,ACTIVITY_FLAG_08,ACTIVITY_FLAG_09,ACTIVITY_FLAG_10,ACTIVITY_FLAG_11,ACTIVITY_FLAG_12,ACTIVITY_FLAG_13,MAINT_DATE,MAINT_TIME,PARENT_VAR_LEV from LSLMDB.ls_apps.GLAMOUNTS where {0} >=");

-- COMMAND ----------

INSERT INTO metadata.MasterMetadata (SourceSystem	,
TableID	,
SubjectArea	,
SourceDBName	,
SourceSchema	,
SourceTableName	,
LoadType	,
IsActive	,
Frequency	,
LastLoadDateColumn,
LastLoadDateValue,
MergeKey,
SourceSelectQuery
)
VALUES ("Finance"	,
"F4"	,
"General Ledger"	,
"LSLMDB"	,
"ls_apps"	,
"FINANCE_GLUNITS"	,
"incremental load"	,
"1"	,
"24 hrs"	,
"MAINT_DATE",
"1753-01-01",
"COMPANY,FISCAL_YEAR,ACCT_UNIT,ACCOUNT,SUB_ACCOUNT",
"select COMPANY,FISCAL_YEAR,ACCT_UNIT,ACCOUNT,SUB_ACCOUNT,VAR_LEVELS,CHART_NAME,DB_BEG_BAL,CR_BEG_BAL,DB_UNITS_01,DB_UNITS_02,DB_UNITS_03,DB_UNITS_04,DB_UNITS_05,DB_UNITS_06,DB_UNITS_07,DB_UNITS_08,DB_UNITS_09,DB_UNITS_10,DB_UNITS_11,DB_UNITS_12,DB_UNITS_13,CR_UNITS_01,CR_UNITS_02,CR_UNITS_03,CR_UNITS_04,CR_UNITS_05,CR_UNITS_06,CR_UNITS_07,CR_UNITS_08,CR_UNITS_09,CR_UNITS_10,CR_UNITS_11,CR_UNITS_12,CR_UNITS_13,ACTIVITY_FLAG_01,ACTIVITY_FLAG_02,ACTIVITY_FLAG_03,ACTIVITY_FLAG_04,ACTIVITY_FLAG_05,ACTIVITY_FLAG_06,ACTIVITY_FLAG_07,ACTIVITY_FLAG_08,ACTIVITY_FLAG_09,ACTIVITY_FLAG_10,ACTIVITY_FLAG_11,ACTIVITY_FLAG_12,ACTIVITY_FLAG_13,MAINT_DATE,MAINT_TIME,PARENT_VAR_LEV from LSLMDB.ls_apps.GLUNITS where {0} >=");

-- COMMAND ----------

INSERT INTO metadata.MasterMetadata (SourceSystem	,
TableID	,
SubjectArea	,
SourceDBName	,
SourceSchema	,
SourceTableName	,
LoadType	,
IsActive	,
Frequency	,
LastLoadDateColumn,
LastLoadDateValue,
MergeKey,
SourceSelectQuery
)
VALUES ("Finance"	,
"F5"	,
"General Ledger"	,
"LSLMDB"	,
"ls_apps"	,
"FINANCE_GLNAMES"	,
"incremental load"	,
"1"	,
"24 hrs"	,
"LAST_UPDT_DATE",
"1753-01-01",
"COMPANY,ACCT_UNIT",
"select COMPANY,ACCT_UNIT,VAR_LEVELS,DESCRIPTION,CHART_SECTION,CURRENCY_CODE,PERSON_RESP,ACTIVE_STATUS,ACCT_GENERATE,POSTING_FLAG,VAR_LEVEL_DISP,LEVEL_DEPTH,LEVEL_DETAIL_01,LEVEL_DETAIL_02,LEVEL_DETAIL_03,LEVEL_DETAIL_04,LEVEL_DETAIL_05,OBJ_ID,PARENT_OBJ_ID,CREATED_BY,LAST_UPDT_DATE,LAST_UPDT_TIME,LAST_UPDATE_BY,L_INDEX,GLNSET3_SS_SW,L_ATGLN_SS_SW from LSLMDB.ls_apps.GLNAMES where {0} >=");

-- COMMAND ----------

INSERT INTO metadata.MasterMetadata (SourceSystem	,
TableID	,
SubjectArea	,
SourceDBName	,
SourceSchema	,
SourceTableName	,
LoadType	,
IsActive	,
Frequency	,
LastLoadDateColumn,
LastLoadDateValue,
MergeKey,
SourceSelectQuery
)
VALUES ("Finance"	,
"F6"	,
"General Ledger"	,
"LSLMDB"	,
"ls_apps"	,
"FINANCE_GLTRANS"	,
"incremental load"	,
"1"	,
"24 hrs"	,
"LAST_UPDT_DATE",
"1753-01-01",
"COMPANY,FISCAL_YEAR,ACCT_PERIOD,CONTROL_GROUP,SYSTEM,JE_TYPE,JE_SEQUENCE,LINE_NBR",
"select COMPANY,FISCAL_YEAR,ACCT_PERIOD,CONTROL_GROUP,SYSTEM,JE_TYPE,JE_SEQUENCE,LINE_NBR,OBJ_ID,STATUS,VAR_LEVELS,ACCT_UNIT,ACCOUNT,SUB_ACCOUNT,SOURCE_CODE,R_DATE,REFERENCE,DESCRIPTION,BASE_AMOUNT,BASE_ND,UNITS_AMOUNT,AUTO_REV,TO_COMPANY,BASE_ZONE,POSTING_DATE,ACTIVITY,ACCT_CATEGORY,CURRENCY_CODE,BASERATE,TRAN_AMOUNT,TRAN_ND,ACCT_CURRENCY,ACCT_RATE,ACCT_AMOUNT,ACCT_ND,ORIG_COMPANY,ORIG_PROGRAM,OPERATOR,TO_BASE_AMT,TO_BASE_ND,TO_BASERATE,TO_BASE_CURR,RECONCILE,NEGATIVE_ADJ,EFFECT_DATE,UPDATE_DATE,SEQ_TRNS_NBR,JBK_TRNS_NBR,CONSOL_AC_FLAG,CT_FR_COMPANY,RPT_AMOUNT_1,RPT_RATE_1,RPT_ND_1,RPT_AMOUNT_2,RPT_RATE_2,RPT_ND_2,CREATED_BY,LAST_UPDT_DATE,LAST_UPDT_TIME,LAST_UPDATE_BY,L_INDEX,GLTSET2_SS_SW,GLTSET3_SS_SW,GLTSET6_SS_SW,GLTSET8_SS_SW,L_ATGLT_SS_SW from LSLMDB.ls_apps.GLTRANS where {0} >=");

-- COMMAND ----------

INSERT INTO metadata.MasterMetadata (SourceSystem	,
TableID	,
SubjectArea	,
SourceDBName	,
SourceSchema	,
SourceTableName	,
LoadType	,
IsActive	,
Frequency	,
LastLoadDateColumn,
LastLoadDateValue,
MergeKey,
SourceSelectQuery
)
VALUES ("Finance"	,
"F8"	,
"Accounts Payable"	,
"LSLMDB"	,
"ls_apps"	,
"FINANCE_APDISTRIB"	,
"incremental load"	,
"1"	,
"24 hrs"	,
"LAST_UPDT_DATE	",
"1753-01-01",
"API_OBJ_ID,DIST_SEQ_NBR",
"select COMPANY, API_OBJ_ID,VENDOR,INVOICE,SUFFIX,CANCEL_SEQ,ORIG_DIST_SEQ,DIST_SEQ_NBR,DIST_TYPE,PROC_LEVEL,POST_OPTION,INVOICE_TYPE,REC_STATUS,INV_CURRENCY,TAX_RATE,CURR_RATE,ORIG_BASE_AMT,BASE_ND,ORIG_TRAN_AMT,TRAN_ND,TO_BASE_AMT,TO_BASE_ND,TAXABLE_AMT,UNT_AMOUNT,DIST_COMPANY,DIS_ACCT_UNIT,DIS_ACCOUNT,DIS_SUB_ACCT,DISTRIB_DATE,TAX_INDICATOR,TAX_SEQ_NBR,TAX_CODE,TAX_TYPE,DESCRIPTION,DST_REFERENCE,ACTIVITY,ACCT_CATEGORY,BILL_CATEGORY,ACCR_CODE,PO_NUMBER,PO_RELEASE,PO_CODE,PO_LINE_NBR,PO_AOC_CODE,GLT_OBJ_ID,ATN_OBJ_ID,ASSET_FLAG,DIST_CODE,TAX_POINT,VAT_REVERSE_FL,DST_OBJ_ID,MA_CREATE_FL,TAX_USAGE_CD,TRAN_DIST_FLAG,PULL_FOR_FR_FL,AC_UPD_STATUS,AC_UPD_DATE,AC_UPD_TIME,DIVERSE_CODE,DISTRIB_ADJ,TAX_FLAG,ICN_CODE,WEIGHT,SUPLMNTARY_QTY,LINE_TYPE,STATEMENT,TXN_NBR,RETAINAGE,PROD_TAX_CAT,CREATED_BY,LAST_UPDT_DATE,LAST_UPDT_TIME,LAST_UPDATE_BY,LTR_OF_GUARAN,L_INDEX,APDSET10_SS_SW,APDSET11_SS_SW,APDSET12_SS_SW,APDSET5_SS_SW,APDSET6_SS_SW,APDSET8_SS_SW,APDSET9_SS_SW,L_ATAPD_SS_SW from LSLMDB.ls_apps.APDISTRIB where {0} >=");

-- COMMAND ----------

INSERT INTO metadata.MasterMetadata (SourceSystem	,
TableID	,
SubjectArea	,
SourceDBName	,
SourceSchema	,
SourceTableName	,
LoadType	,
IsActive	,
Frequency	,
LastLoadDateColumn,
LastLoadDateValue,
MergeKey,
SourceSelectQuery
)
VALUES ("Finance"	,
"F9"	,
"Accounts Payable"	,
"LSLMDB"	,
"ls_apps"	,
"FINANCE_APVENMAST"	,
"incremental load"	,
"1"	,
"24 hrs"	,
"LAST_UPDT_DATE	",
"2020-01-01",
"VENDOR_GROUP,VENDOR",
"select VENDOR_GROUP,VENDOR,VEN_CLASS,VENDOR_VNAME,VENDOR_SNAME,VENDOR_CONTCT,REMIT_TO_CODE,PURCH_FR_LOC,PAY_VENDOR,VENDOR_STATUS,VEN_PRIORITY,PHONE_PREFIX,PHONE_NUM,PHONE_EXT,FAX_PREFIX,FAX_NUM,FAX_EXT,TELEX_NUM,TERM_CODE,INV_CURRENCY,BAL_CURRENCY,CURR_RECALC,SEP_CHK_FLAG,TAX_ID,TAX_EXEMPT_CD,TAX_CODE,HOLD_FLAG,DIST_CODE,ACCR_CODE,BANK_INST_CODE,CASH_CODE,BANK_ENTITY,BANK_CURRENCY,VBANK_ACCT_NO,VBANK_ACCT_TP,VBANK_IDENT,CROSS_IDENT,INCOME_CODE,INCOME_WH_FLG,EDI_NBR,ACH_PRENOT,MAX_INV_AMT,CREATE_DATE,ORIGIN_DATE,OPERATOR,USER_NAME_01,USER_NAME_02,USER_NAME_03,USER_NAME_04,USER_NAME_05,USER_NAME_06,CUST_GROUP,CUSTOMER,LEGAL_NAME,PRIME_RATE,INVOICE_GROUP,DISCOUNT_CODE,ERS_CAPABLE,INVC_REF_TYPE,EDI_AUTO_REL,AUTH_CODE,APPRVL_EXISTS,ACTIVITY,ACCT_CATEGORY,CHARGE_CODE,PMT_CAT_CODE,NORM_EXP_CODE,PMT_FORM,SWIFT_ID,PROC_GRP,MATCH_TABLE,DISC_CALC_DATE,CREATE_POD_FL,HANDLING_CODE,ENCLOSURE,REQ_MATCH_REF,POOL_OPTION,HOLD_INSP_FLAG,WRITE_OFF_AMT,VEN_CLAIM_TYPE,CLAIM_HOLD_CD,CB_HOLD_CODE,CB_MINIMUM_AMT,REPLACE_GOODS,SHIP_OR_HOLD,ERS_HANDLING,E_MAIL_ADDRESS,URL_ADDR,VEND_ACCT,LANGUAGE_CODE,TAX_USAGE_CD,VAT_REG_CTRY,VAT_REG_NBR,VALIDATE_PO,REQUIRE_PO,WORKFLOW_GROUP,MBL_INT_PREFIX,MOBILE_NUM,MOBILE_EXT,PAY_IMM_FLAG,DIVERSE_CODE,INTM_BANK_ENT,INTM_BANK_ACCT,INTM_BANK_IDNT,INTM_BANK_CURR,INTM_PRENOT,INTM_SWIFT_ID,INTM_PMT_CAT,INTM_NORM_EXP,INTM_PMT_FORM,INTM_CHRG_CD,INTM_CRS_IDENT,RULE_GROUP,FLOAT_DAYS,MTCH_PREPAY_FL,MTCH_PREPAY_MT,BUILD_SOC_REF,BUILD_ACCT_NM,XREF_FLAG,GIRO_NUMBER,CR_CARD_NUMBER,BANK_INSTRUCT1,BANK_INSTRUCT2,BANK_INSTRUCT3,BANK_INSTRUCT4,AP_OBJ_ID,P_CARD_FLAG,PCARD_NBR,VAL_DIV_DATE,RET_ACCR_CODE,GLN_NBR,TIN_TYPE,TIN_NOT,TIN_VERIFIED,SEC_WTH_EXEMPT,SEC_WTH_CODE1,SEC_WTH_CODE2,SEC_WTH_CODE3,CREATED_BY,LAST_UPDT_DATE,LAST_UPDT_TIME,LAST_UPDATE_BY,VALID_CERT_DT,FOR_ECON_CODE,SOCIAL_ID1,SOCIAL_ID2,SOCIAL_ID3,SOCIAL_ID4,SOCIAL_ID5,CARRIER_FLAG,BANK_CODE,BANK_ID,ASSIGNMENT_NBR,DEBITING_SIGN,INTM_BANK_CODE,INTM_BANK_ID,INTM_ASSIGN_NO,INTM_DEBITING,CHK_DIG_TYPE,SEPA_FLAG,W8_VERIFIED,FATCA_ID,FIN_INST_TYPE,GIIN_CAT_CODE,ISO_CTRY_NBR,FATCA_WITHOLD,FATCA_INC_CODE,FATCA_AU,FATCA_ACCOUNT,FATCA_SUB_ACCT,OPEN_ZERO_COST,ENABLE_ASN_BOD,EXTERNAL_KEY,EXT_ACCT_ENT,EXT_LOCATION,L_INDEX,VENSET11_SS_SW,VENSET8_SS_SW,L_ATVEN_SS_SW from LSLMDB.ls_apps.APVENMAST where {0} >=");

-- COMMAND ----------

INSERT INTO metadata.MasterMetadata (SourceSystem	,
TableID	,
SubjectArea	,
SourceDBName	,
SourceSchema	,
SourceTableName	,
LoadType	,
IsActive	,
Frequency	,
LastLoadDateColumn,
LastLoadDateValue,
MergeKey,
SourceSelectQuery
)
VALUES ("Finance"	,
"F11"	,
"Accounts Receivable"	,
"LSLMDB"	,
"ls_apps"	,
"FINANCE_ARDISTRIB"	,
"incremental load"	,
"1"	,
"24 hrs"	,
"CREATE_DATE",
"2003-01-01",
"GL_COMPANY,ACCT_UNIT,ACCOUNT,SUB_ACCT,GL_DATE,CREATE_DATE,CREATE_TIME,PROG_SEQ_NBR",
"select GL_COMPANY,ACCT_UNIT,ACCOUNT,SUB_ACCT,GL_DATE,CREATE_DATE,CREATE_TIME,PROG_SEQ_NBR,COMPANY,BATCH_NBR,CUSTOMER,PROCESS_LEVEL,TRANS_TYPE,INVOICE,TRANS_DATE,DIST_SEQ,DST_TYPE,PAYMENT_SEQ,ACCUM_TYPE,TRAN_AMT,TO_COMP_AMT,UNITS,R_DESC,ACTIVITY,ACCT_CATEGORY,STATUS,ORIG_CURRENCY,ORIG_RATE,ORIG_AMT,CAT_TYPE,AR_CATEGORY,TAX_CODE,TRAN_TAXABLE,UPDATE_SUM,ORIG_ND,AUTO_REV,ORIG_COMPANY,ORIG_TAXABLE,DOCUMENT_NBR,DST_SOURCE,BASE_ACCTUNIT,JRNL_BOOK_NBR,MX_VALUE_01,MX_VALUE_02,MX_VALUE_03,GLT_OBJ_ID,DRAFT_SOURCE,ATN_OBJ_ID,TAX_POINT,JBK_SEQ_NBR,LINE_TYPE,WEIGHT,ICN_CODE,SUPLMNTARY_QTY,BAL_DATE,ARA_OBJ_ID,AMDSET10_SS_SW,AMDSET2_SS_SW,AMDSET3_SS_SW,AMDSET4_SS_SW,AMDSET6_SS_SW,AMDSET7_SS_SW,AMDSET8_SS_SW,AMDSET9_SS_SW from LSLMDB.ls_apps.ARDISTRIB where {0} >=");

-- COMMAND ----------

INSERT INTO metadata.MasterMetadata (SourceSystem	,
TableID	,
SubjectArea	,
SourceDBName	,
SourceSchema	,
SourceTableName	,
LoadType	,
IsActive	,
Frequency	,
LastLoadDateColumn,
LastLoadDateValue,
MergeKey,
SourceSelectQuery
)
VALUES ("Pricing"	,
"P1"	,
"Pricing"	,
"nfi"	,
"public"	,
"Pricing_nfi_load_predictions"	,
"incremental load"	,
"1"	,
"24 hrs"	,
"last_updated_date",
"2022-01-01T00:00:56.465Z",
"external_load_id,last_updated_date",
"select external_load_id, tms_type,	high_buy_rate_predicted,	low_buy_rate_predicted,	start_buy_rate_predicted,	target_buy_rate_predicted,	confidence_predicted,	miles_predicted,	rate_predicted_checked,	created_date,	last_updated_date,	rate_predicted_request_date,	high_buy_rate_gsn,	low_buy_rate_gsn,	start_buy_rate_gsn,	target_buy_rate_gsn,	confidence_level_gsn,	gsn_request_date,	gsn_predicted_checked from nfi.public.nfi_load_predictions where '{0}' >=");

-- COMMAND ----------

INSERT INTO metadata.MasterMetadata (SourceSystem	,
TableID	,
SubjectArea	,
SourceDBName	,
SourceSchema	,
SourceTableName	,
LoadType	,
IsActive	,
Frequency	,
LastLoadDateColumn,
LastLoadDateValue,
MergeKey,
SourceSelectQuery
)
VALUES ("Pricing"	,
"P2"	,
"Pricing"	,
"nfi"	,
"public"	,
"Pricing_nfi_loads"	,
"incremental load"	,
"1"	,
"24 hrs"	,
"last_updated_date",
"2020-01-01T01:42:56.465Z",
"id,last_updated_date",
"select id,	external_carrier_company_id,	driver_name,	driver_phone,	trailer_number,	truck_number,	commodity,	height,	length,	quantity,	ref_numbers,	special_instruction,	status,	temperature_low,	temperature_high,	tord_flag,	weight,	width,	external_load_id,	external_shipper_id,	shipper_name,	booked_date,	miles,	pickup_date,	accessorials,	total_carrier_cost,	total_carrier_rate,	total_fuel_cost,	total_linehaul_cost,	total_shipper_cost,	transport_mode,	origin_city,	origin_state,	origin_kma,	origin_zip,	origin_country,	destination_city,	destination_state,	destination_kma,	destination_zip,	destination_country,	created_date,	last_updated_date,	carrier_name,	carrier_phone,	carrier_account_manager,	covered_date,	shipper_account_manager,	with_extra_stops,	stop_count,	tms_type,	delivered_date,	office,	transport_type_customer,	transport_type,	valid,	currency,	exchange_rate,	valid_rate,	valid_distance,	exist_kma,	not_tord,	valid_weight,	valid_distance_with_rate,	valid_price,	meets_customer_filter,	valid_transport_type,	valid_country_and_zips,	valid_status,	valid_pickup_date,	with_out_extra_stop,	valid_min_rate,	valid_max_rate from nfi.public.nfi_loads where '{0}' >=");

-- COMMAND ----------

-- MAGIC %md ##Truncate and load

-- COMMAND ----------

INSERT INTO metadata.MasterMetadata (SourceSystem	,
TableID	,
SubjectArea	,
SourceDBName	,
SourceSchema	,
SourceTableName	,
LoadType	,
IsActive	,
Frequency	,
SourceSelectQuery
)
VALUES ("Finance"	,
"F7"	,
"General Ledger"	,
"LSLMDB"	,
"ls_apps"	,
"FINANCE_GLSRCCODE"	,
"truncate and load"	,
"1",
"24 hrs"	,
"select SOURCE_CODE,DESCRIPTION,SOURCE_TYPE,EDIT_TYPE,USED_FLAG,LAST_SEQ,LAST_FIELD_NBR,PRIMARY_SYSTEM,SOURCE_GROUP from LSLMDB.ls_apps.GLSRCCODE");

-- COMMAND ----------

INSERT INTO metadata.MasterMetadata (SourceSystem	,
TableID	,
SubjectArea	,
SourceDBName	,
SourceSchema	,
SourceTableName	,
LoadType	,
IsActive	,
Frequency	,
SourceSelectQuery
)
VALUES ("Finance"	,
"F10"	,
"Accounts Payable"	,
"LSLMDB"	,
"ls_apps"	,
"FINANCE_APVENCLASS"	,
"truncate and load"	,
"1",
"24 hrs"	,
"select VENDOR_GROUP,	VEN_CLASS,	VEN_PRIORITY,	DESCRIPTION,	ZERO_CHECK,	POST_OPTION,	DIST_CODE,	MAX_PMT_AMT,	MAX_PMT_HOLD,	INCOME_CODE,	CURRENCY_CODE,	TAX_EXEMPT_CD,	TAX_CODE,	CASH_CODE,	BANK_INST_CODE,	ZERO_PMT_CODE,	ENCLOSURE,	TAX_USAGE_CD,	HANDLING_CODE,	VALIDATE_PO,	REQUIRE_PO,	MTCH_PREPAY_FL,	MTCH_PREPAY_MT,	MATCH_TABLE,	RULE_GROUP,	RETAIL_FLAG,	EAM_VEN_FL,	MIN_PMT_HOLD,	MIN_PMT_AMT,	TAX_OVERRIDE from LSLMDB.ls_apps.APVENCLASS");

-- COMMAND ----------

INSERT INTO metadata.MasterMetadata (SourceSystem	,
TableID	,
SubjectArea	,
SourceDBName	,
SourceSchema	,
SourceTableName	,
LoadType	,
IsActive	,
Frequency	,
SourceSelectQuery
)
VALUES ("Finance"	,
"F12"	,
"Accounts Receivable"	,
"LSLMDB"	,
"ls_apps"	,
"FINANCE_ARCUSTOMER"	,
"truncate and load"	,
"1",
"24 hrs"	,
"select COMPANY,	CUSTOMER,	ACTIVE_STATUS,	NAT_FLAG,	SEARCH_NAME,	HOLD_CODE,	CONTACT,	INT_PREFIX,	PHONE_NMBR,	PHONE_EXT,	TELEX_NBR,	EDI_NBR,	ALT_EDI_NBR,	ALT_EDI_TYPE,	FAX_NMBR,	FAX_EXT,	START_DATE,	CREDIT_ANLYST,	CURRENCY_CD,	SALESMAN,	RISK_CD,	DEFAULT_CODE,	MAJ_CLASS,	MIN_CLASS,	CURR_BAL,	DRAFT_BAL,	OPEN_ORDS,	ORDER_LIM,	CREDIT_LIM,	CREDIT_LIM_DAT,	CREDIT_REVDAYS,	LAST_PMT_AMT,	LAST_PMT_DATE,	LAST_INV_DATE,	LAST_INV_AMT,	LAST_STA_DATE,	LAST_STA_BAL,	REVIEW_DATE,	REVIEW_CODE,	HIGH_BAL_01,	HIGH_BAL_02,	HIGH_BAL_03,	HIGH_BAL_04,	HIGH_BAL_05,	HIGH_BAL_06,	HIGH_BAL_07,	HIGH_BAL_08,	HIGH_BAL_09,	HIGH_BAL_10,	HIGH_BAL_11,	HIGH_BAL_12,	HIGH_BAL_13,	PER_RTMS_01,	PER_RTMS_02,	PER_RTMS_03,	PER_RTMS_04,	PER_RTMS_05,	PER_RTMS_06,	PER_RTMS_07,	PER_RTMS_08,	PER_RTMS_09,	PER_RTMS_10,	PER_RTMS_11,	PER_RTMS_12,	PER_RTMS_13,	PAID_PRMPT_01,	PAID_PRMPT_02,	PAID_PRMPT_03,	PAID_PRMPT_04,	PAID_PRMPT_05,	PAID_PRMPT_06,	PAID_PRMPT_07,	PAID_PRMPT_08,	PAID_PRMPT_09,	PAID_PRMPT_10,	PAID_PRMPT_11,	PAID_PRMPT_12,	INV_PAID_01,	INV_PAID_02,	INV_PAID_03,	INV_PAID_04,	INV_PAID_05,	INV_PAID_06,	INV_PAID_07,	INV_PAID_08,	INV_PAID_09,	INV_PAID_10,	INV_PAID_11,	INV_PAID_12,	COLLECT_DAYS_01,	COLLECT_DAYS_02,	COLLECT_DAYS_03,	COLLECT_DAYS_04,	COLLECT_DAYS_05,	COLLECT_DAYS_06,	COLLECT_DAYS_07,	COLLECT_DAYS_08,	COLLECT_DAYS_09,	COLLECT_DAYS_10,	COLLECT_DAYS_11,	CURR_CASH,	CURR_CSH_DAYS,	YTD_CASH,	YTD_CSH_DAYS,	YEAR_2_DAYS,	STATIC_CUR,	AGING_01,	AGING_02,	AGING_03,	AGING_04,	AGING_05,	LAST_COMMENT,	DISP_NBR,	DISP_AMT,	PL_EXCL_FL,	AGE_DISPUTES,	DISPUTES_FIN,	AUTO_APP_FL,	AUTO_DUNN_FL,	DISC_GRACE_PD,	CR_VAR_PCT,	MEMO_TERM,	CHRGBK_PRT_FL,	OPEN_BAL_FWD,	STATEMENT_REQ,	STMNT_CYCLE,	LOCK_BOX,	ZERO_STMNT_FL,	CRED_STMNT_FL,	PAST_STMNT_FL,	OVER_STMNT_FL,	MAX_AUTO_AMT_01,	MAX_AUTO_AMT_02,	MAX_AUTO_AMT_03,	MAX_AUTO_PCT_01,	MAX_AUTO_PCT_02,	MAX_AUTO_PCT_03,	AUTO_REAS_CD_01,	AUTO_REAS_CD_02,	AUTO_REAS_CD_03,	DISC_REAS_CD,	BANK_INST_CODE,	DRAFT_FLAG,	AR_CODE,	TERMS_CD,	TERMS_CASH,	TERMS_CSH_DAYS,	DBT_RATIO_01,	DBT_RATIO_02,	DBT_RATIO_03,	DBT_RATIO_04,	DBT_RATIO_05,	DBT_RATIO_06,	DBT_RATIO_07,	DBT_RATIO_08,	DBT_RATIO_09,	DBT_RATIO_10,	DBT_RATIO_11,	DBT_PR_YR,	DBT_YTD_CASH,	DBT_YTD_DAYS,	LATE_PAY_FL,	FIN_CALC_TYPE,	FIN_CHRG_CD,	FIN_GRAC_DAYS,	FIN_MIN_CHRG,	FIN_DOC_PRNT,	LAST_DUNN,	LAST_DUN_DATE,	LAST_DUN_AMT,	TAX_EXEMPT_CD,	TAX_CODE,	TERRITORY,	AGING_CODE,	REVALUE_FL,	DISHONORED,	DISHONORED_AMT,	RECONCILE_CASH,	RECONCILE_RNEG,	RECONCILE_WO,	MINIMUM,	FIN_CYCLE,	DUN_CYCLE,	AUTO_METHOD,	AUTO_REMOVE,	I_FIN_MIN_CHRG,	CB_DTL_DATE,	VAT_CUST_TYPE,	VAT_REG_NBR,	VAT_REG_CTRY,	DUN_LTR_IND,	DUN_PROCESS_CD,	LANGUAGE_CODE,	LST_DUNLTR_STM,	LAST_LTR_DATE,	LST_LTRTEXT_CD,	ASSESS_DUN_FEE,	CU_NAME,	CU_ADDR1,	CU_ADDR2,	CU_ADDR3,	CU_ADDR4,	CU_CITY,	CU_STATE,	CU_POSTAL_CODE,	CU_COUNTRY_CD,	CU_COUNTRY,	THIRD_PARTY,	E_MAIL_ADDRESS,	URL_ADDR,	CUST_AUDIT,	APPLY_MIXED,	OBJ_ID,	PAY_AUTO_AMT,	PAY_AUTO_PCT,	PAY_REAS_CD,	MULT_DUN_LTR,	CU_COUNTY,	AFFILIATE_FL,	FOR_ECON_CODE,	SOCIAL_ID1,	SOCIAL_ID2,	SOCIAL_ID3,	SOCIAL_ID4,	SOCIAL_ID5,	CARRIER_FLAG,	L_INDEX,	ACMSET4_SS_SW,	ACMSET9_SS_SW,	L_ATACM_SS_SW from LSLMDB.ls_apps.ARCUSTOMER");