-- Databricks notebook source
-- MAGIC %python
-- MAGIC ## Mention the catalog used, getting the catalog name from key vault
-- MAGIC CatalogName = dbutils.secrets.get(scope="Brokerage-Catalog", key="CatalogName")
-- MAGIC spark.sql(f"USE CATALOG {CatalogName}")

-- COMMAND ----------

-- MAGIC %md ##FINANCE_GLSYSTEM

-- COMMAND ----------

CREATE
OR REPLACE TABLE bronze.FINANCE_GLSYSTEM (
  HashKey VARCHAR(255),
  COMPANY smallint,
  NAME char(30),
  BS_ACCT_UNIT char(15),
  NBR_ACCT_PERS smallint,
  ACCT_PERIOD smallint,
  FISCAL_YEAR smallint,
  LST_YR_CLOSED smallint,
  PER_END_DATE_01 date,
  PER_END_DATE_02 date,
  PER_END_DATE_03 date,
  PER_END_DATE_04 date,
  PER_END_DATE_05 date,
  PER_END_DATE_06 date,
  PER_END_DATE_07 date,
  PER_END_DATE_08 date,
  PER_END_DATE_09 date,
  PER_END_DATE_10 date,
  PER_END_DATE_11 date,
  PER_END_DATE_12 date,
  PER_END_DATE_13 date,
  PER_END_DATE_14 date,
  PER_END_DATE_15 date,
  PER_END_DATE_16 date,
  PER_END_DATE_17 date,
  PER_END_DATE_18 date,
  PER_END_DATE_19 date,
  PER_END_DATE_20 date,
  PER_END_DATE_21 date,
  PER_END_DATE_22 date,
  PER_END_DATE_23 date,
  PER_END_DATE_24 date,
  PER_END_DATE_25 date,
  PER_END_DATE_26 date,
  PER_END_DATE_27 date,
  PER_END_DATE_28 date,
  PER_END_DATE_29 date,
  PER_END_DATE_30 date,
  PER_END_DATE_31 date,
  PER_END_DATE_32 date,
  PER_END_DATE_33 date,
  PER_END_DATE_34 date,
  PER_END_DATE_35 date,
  PER_END_DATE_36 date,
  PER_END_DATE_37 date,
  PER_END_DATE_38 date,
  PER_END_DATE_39 date,
  PER_END_CODE_01 char(1),
  PER_END_CODE_02 char(1),
  PER_END_CODE_03 char(1),
  PER_END_CODE_04 char(1),
  PER_END_CODE_05 char(1),
  PER_END_CODE_06 char(1),
  PER_END_CODE_07 char(1),
  PER_END_CODE_08 char(1),
  PER_END_CODE_09 char(1),
  PER_END_CODE_10 char(1),
  PER_END_CODE_11 char(1),
  PER_END_CODE_12 char(1),
  PER_END_CODE_13 char(1),
  PER_END_CODE_14 char(1),
  PER_END_CODE_15 char(1),
  PER_END_CODE_16 char(1),
  PER_END_CODE_17 char(1),
  PER_END_CODE_18 char(1),
  PER_END_CODE_19 char(1),
  PER_END_CODE_20 char(1),
  PER_END_CODE_21 char(1),
  PER_END_CODE_22 char(1),
  PER_END_CODE_23 char(1),
  PER_END_CODE_24 char(1),
  PER_END_CODE_25 char(1),
  PER_END_CODE_26 char(1),
  PER_END_CODE_27 char(1),
  PER_END_CODE_28 char(1),
  PER_END_CODE_29 char(1),
  PER_END_CODE_30 char(1),
  PER_END_CODE_31 char(1),
  PER_END_CODE_32 char(1),
  PER_END_CODE_33 char(1),
  PER_END_CODE_34 char(1),
  PER_END_CODE_35 char(1),
  PER_END_CODE_36 char(1),
  PER_END_CODE_37 char(1),
  PER_END_CODE_38 char(1),
  PER_END_CODE_39 char(1),
  CONTROL_CODE char(1),
  INTLV_BAL_FLG char(1),
  CURRENCY_TABLE char(12),
  CURR_CONV_FLG char(1),
  CURR_TRAN_FLG char(1),
  CURRENCY_CODE char(5),
  COMPANY_ND tinyint,
  IS_ACCT_UNIT char(15),
  ACTIVE_STATUS char(1),
  AVG_DAILY_BAL char(1),
  AUTO_JE_NBR char(1),
  LEVEL_DESC_01 char(12),
  LEVEL_DESC_02 char(12),
  LEVEL_DESC_03 char(12),
  LEVEL_DESC_04 char(12),
  LEVEL_DESC_05 char(12),
  NBR_DIGITS_01 smallint,
  NBR_DIGITS_02 smallint,
  NBR_DIGITS_03 smallint,
  NBR_DIGITS_04 smallint,
  NBR_DIGITS_05 smallint,
  GL190_RUN_DT date,
  GL190_RUN_TM decimal(6, 0),
  POSTED_TH_DT date,
  PROJ_ACCT_FLG char(1),
  BASE_ZONE char(15),
  BACKPOST_01 char(1),
  BACKPOST_02 char(1),
  BACKPOST_03 char(1),
  BACKPOST_04 char(1),
  BACKPOST_05 char(1),
  BACKPOST_06 char(1),
  BACKPOST_07 char(1),
  BACKPOST_08 char(1),
  BACKPOST_09 char(1),
  BACKPOST_10 char(1),
  BACKPOST_11 char(1),
  BACKPOST_12 char(1),
  BACKPOST_13 char(1),
  BACKPOST_14 char(1),
  BACKPOST_15 char(1),
  BACKPOST_16 char(1),
  BACKPOST_17 char(1),
  BACKPOST_18 char(1),
  BACKPOST_19 char(1),
  BACKPOST_20 char(1),
  BACKPOST_21 char(1),
  BACKPOST_22 char(1),
  BACKPOST_23 char(1),
  BACKPOST_24 char(1),
  BACKPOST_25 char(1),
  BACKPOST_26 char(1),
  GL150_RUN_DTE date,
  CHART_NAME char(12),
  DEFAULT_PERIOD smallint,
  JOURNAL_BY_DOC char(1),
  UPDATING smallint,
  CLOSE_SEQ_01 smallint,
  CLOSE_SEQ_02 smallint,
  CLOSE_SEQ_03 smallint,
  CLOSE_SEQ_04 smallint,
  CLOSE_SEQ_05 smallint,
  CLOSE_SEQ_06 smallint,
  CLOSE_SEQ_07 smallint,
  CLOSE_SEQ_08 smallint,
  CLOSE_SEQ_09 smallint,
  CLOSE_SEQ_10 smallint,
  CLOSE_SEQ_11 smallint,
  CLOSE_SEQ_12 smallint,
  CLOSE_SEQ_13 smallint,
  CLOSE_SEQ_14 smallint,
  CLOSE_SEQ_15 smallint,
  CLOSE_SEQ_16 smallint,
  CLOSE_SEQ_17 smallint,
  CLOSE_SEQ_18 smallint,
  CLOSE_SEQ_19 smallint,
  CLOSE_SEQ_20 smallint,
  CLOSE_SEQ_21 smallint,
  CLOSE_SEQ_22 smallint,
  CLOSE_SEQ_23 smallint,
  CLOSE_SEQ_24 smallint,
  CLOSE_SEQ_25 smallint,
  CLOSE_SEQ_26 smallint,
  CLOSE_SEQ_27 smallint,
  CLOSE_SEQ_28 smallint,
  CLOSE_SEQ_29 smallint,
  CLOSE_SEQ_30 smallint,
  CLOSE_SEQ_31 smallint,
  CLOSE_SEQ_32 smallint,
  CLOSE_SEQ_33 smallint,
  CLOSE_SEQ_34 smallint,
  CLOSE_SEQ_35 smallint,
  CLOSE_SEQ_36 smallint,
  CLOSE_SEQ_37 smallint,
  CLOSE_SEQ_38 smallint,
  CLOSE_SEQ_39 smallint,
  LEVEL_DEPTH tinyint,
  JRNL_BOOK_REQ char(1),
  SEQ_TRNS_CD char(1),
  RESET_SEQ_NBR char(1),
  CHG_POST_TRAN char(1),
  CHG_REL_TRAN char(1),
  ERROR_SP_JBOOK char(12),
  YEAR_END_JBOOK char(12),
  AUTO_JBK_SEQ char(1),
  JE_APPROVE_AMT decimal(18, 2),
  WORKFLOW_FLAG char(1),
  CURR_NAME_1 char(12),
  CURR_CODE_1 char(5),
  CURR_CODE_ND_1 tinyint,
  CURR_NAME_2 char(12),
  CURR_CODE_2 char(5),
  CURR_CODE_ND_2 tinyint,
  AUTO_BASE_BAL char(1),
  CURR_RE_FLAG char(1),
  BUD_EDIT_RANGE char(1),
  BUD_EDIT_TYPE char(1),
  FB_UPDATING smallint,
  ML_UPDATING smallint,
  BUD_TOLERANCE decimal(5, 2),
  BUD_ACT tinyint,
  CREATED_BY char(10),
  LAST_UPDT_DATE date,
  LAST_UPDT_TIME int,
  LAST_UPDATE_BY char(10),
  Z4_RPT_FLAG char(1),
  Z4_MIN_AMT decimal(18, 2),
  TRANS_NBR_LOC decimal(10, 0),
  CONSTRAINT FINANCE_GLSYSTEM_pkey PRIMARY KEY (COMPANY)
)

-- COMMAND ----------

-- MAGIC %md ##FINANCE_GLCHARTDTL

-- COMMAND ----------

CREATE OR REPLACE TABLE  bronze.FINANCE_GLCHARTDTL
(
	HashKey VARCHAR(255),
	CHART_NAME	char(12)	,
	SUMRY_ACCT_ID	int	,
	CHART_SECTION	char(1)	,
	ACCOUNT	int	,
	SUB_ACCOUNT	smallint	,
	ACCOUNT_DESC	char(60)	,
	SPACE_CODE	tinyint	,
	SIGN_CODE	char(1)	,
	UNITS_CODE	char(1)	,
	ACTIVITY_REQ	char(1)	,
	POSTING_LEVEL	char(1)	,
	CURRENCY_CODE	char(5)	,
	CURR_CONTROL	char(1)	,
	TRANSL_CODE	char(2)	,
	REVALUE	char(1)	,
	ACTIVE_STATUS	char(1)	,
	DYNAMIC_LIST	char(12)	,
	RESTRICT_SYS	char(1)	,
	ACCT_CATEGORY	char(5)	,
	DAILY_BALANCE	char(1)	,
	RELATION	char(15)	,
	UNARY_OPER	char(1)	,
	NAT_BALANCE	char(1)	,
	SL_ACCT_FLAG	char(1)	,
	OBJ_ID	decimal(12,0)	,
	LEDGER_GROUP	char(15)	,
	GL_BUD_FL	char(1)	,
	GL_ACCT_TYPE	smallint	,
	XBRL_TAG_ID	char(60)	,
	CREATED_BY	char(10)	,
	LAST_UPDT_DATE	date	,
	LAST_UPDT_TIME	int	,
	LAST_UPDATE_BY	char(10)	,
	GDTSET6_SS_SW	char(1)	,
	GDTSET7_SS_SW	char(1)	,
	CONSTRAINT FINANCE_GLCHARTDTL_pkey PRIMARY KEY (CHART_NAME, SUMRY_ACCT_ID, ACCOUNT, SUB_ACCOUNT)
)

-- COMMAND ----------

-- MAGIC %md ##FINANCE_GLAMOUNTS

-- COMMAND ----------

CREATE OR REPLACE TABLE  bronze.FINANCE_GLAMOUNTS
(
	HashKey VARCHAR(255),
	COMPANY	smallint	,
	FISCAL_YEAR	smallint	,
	ACCT_UNIT	char(15)	,
	ACCOUNT	int	,
	SUB_ACCOUNT	smallint	,
	VAR_LEVELS	char(30)	,
	CHART_NAME	char(12)	,
	DB_BEG_BAL	decimal(18,2)	,
	CR_BEG_BAL	decimal(18,2)	,
	DB_AMOUNT_01	decimal(18,2)	,
	DB_AMOUNT_02	decimal(18,2)	,
	DB_AMOUNT_03	decimal(18,2)	,
	DB_AMOUNT_04	decimal(18,2)	,
	DB_AMOUNT_05	decimal(18,2)	,
	DB_AMOUNT_06	decimal(18,2)	,
	DB_AMOUNT_07	decimal(18,2)	,
	DB_AMOUNT_08	decimal(18,2)	,
	DB_AMOUNT_09	decimal(18,2)	,
	DB_AMOUNT_10	decimal(18,2)	,
	DB_AMOUNT_11	decimal(18,2)	,
	DB_AMOUNT_12	decimal(18,2)	,
	DB_AMOUNT_13	decimal(18,2)	,
	CR_AMOUNT_01	decimal(18,2)	,
	CR_AMOUNT_02	decimal(18,2)	,
	CR_AMOUNT_03	decimal(18,2)	,
	CR_AMOUNT_04	decimal(18,2)	,
	CR_AMOUNT_05	decimal(18,2)	,
	CR_AMOUNT_06	decimal(18,2)	,
	CR_AMOUNT_07	decimal(18,2)	,
	CR_AMOUNT_08	decimal(18,2)	,
	CR_AMOUNT_09	decimal(18,2)	,
	CR_AMOUNT_10	decimal(18,2)	,
	CR_AMOUNT_11	decimal(18,2)	,
	CR_AMOUNT_12	decimal(18,2)	,
	CR_AMOUNT_13	decimal(18,2)	,
	ACTIVITY_FLAG_01	char(1)	,
	ACTIVITY_FLAG_02	char(1)	,
	ACTIVITY_FLAG_03	char(1)	,
	ACTIVITY_FLAG_04	char(1)	,
	ACTIVITY_FLAG_05	char(1)	,
	ACTIVITY_FLAG_06	char(1)	,
	ACTIVITY_FLAG_07	char(1)	,
	ACTIVITY_FLAG_08	char(1)	,
	ACTIVITY_FLAG_09	char(1)	,
	ACTIVITY_FLAG_10	char(1)	,
	ACTIVITY_FLAG_11	char(1)	,
	ACTIVITY_FLAG_12	char(1)	,
	ACTIVITY_FLAG_13	char(1)	,
	MAINT_DATE	date	,
	MAINT_TIME	decimal(6,0)	,
	PARENT_VAR_LEV	char(30)	,
	CONSTRAINT FINANCE_GLAMOUNTS_pkey PRIMARY KEY (COMPANY, FISCAL_YEAR, ACCT_UNIT, ACCOUNT, SUB_ACCOUNT)
)

-- COMMAND ----------

-- MAGIC %md ##FINANCE_GLUNITS

-- COMMAND ----------

CREATE OR REPLACE TABLE  bronze.FINANCE_GLUNITS
(
	HashKey VARCHAR(255),
	COMPANY	smallint	,
	FISCAL_YEAR	smallint	,
	ACCT_UNIT	char(15)	,
	ACCOUNT	int	,
	SUB_ACCOUNT	smallint	,
	VAR_LEVELS	char(30)	,
	CHART_NAME	char(12)	,
	DB_BEG_BAL	decimal(15,2)	,
	CR_BEG_BAL	decimal(15,2)	,
	DB_UNITS_01	decimal(15,2)	,
	DB_UNITS_02	decimal(15,2)	,
	DB_UNITS_03	decimal(15,2)	,
	DB_UNITS_04	decimal(15,2)	,
	DB_UNITS_05	decimal(15,2)	,
	DB_UNITS_06	decimal(15,2)	,
	DB_UNITS_07	decimal(15,2)	,
	DB_UNITS_08	decimal(15,2)	,
	DB_UNITS_09	decimal(15,2)	,
	DB_UNITS_10	decimal(15,2)	,
	DB_UNITS_11	decimal(15,2)	,
	DB_UNITS_12	decimal(15,2)	,
	DB_UNITS_13	decimal(15,2)	,
	CR_UNITS_01	decimal(15,2)	,
	CR_UNITS_02	decimal(15,2)	,
	CR_UNITS_03	decimal(15,2)	,
	CR_UNITS_04	decimal(15,2)	,
	CR_UNITS_05	decimal(15,2)	,
	CR_UNITS_06	decimal(15,2)	,
	CR_UNITS_07	decimal(15,2)	,
	CR_UNITS_08	decimal(15,2)	,
	CR_UNITS_09	decimal(15,2)	,
	CR_UNITS_10	decimal(15,2)	,
	CR_UNITS_11	decimal(15,2)	,
	CR_UNITS_12	decimal(15,2)	,
	CR_UNITS_13	decimal(15,2)	,
	ACTIVITY_FLAG_01	char(1)	,
	ACTIVITY_FLAG_02	char(1)	,
	ACTIVITY_FLAG_03	char(1)	,
	ACTIVITY_FLAG_04	char(1)	,
	ACTIVITY_FLAG_05	char(1)	,
	ACTIVITY_FLAG_06	char(1)	,
	ACTIVITY_FLAG_07	char(1)	,
	ACTIVITY_FLAG_08	char(1)	,
	ACTIVITY_FLAG_09	char(1)	,
	ACTIVITY_FLAG_10	char(1)	,
	ACTIVITY_FLAG_11	char(1)	,
	ACTIVITY_FLAG_12	char(1)	,
	ACTIVITY_FLAG_13	char(1)	,
	MAINT_DATE	date	,
	MAINT_TIME	decimal(6,0)	,
	PARENT_VAR_LEV	char(30)	,
	CONSTRAINT FINANCE_GLUNITS_pkey PRIMARY KEY (COMPANY, FISCAL_YEAR, ACCT_UNIT, ACCOUNT, SUB_ACCOUNT)
)

-- COMMAND ----------

-- MAGIC %md ##FINANCE_GLNAMES

-- COMMAND ----------

CREATE OR REPLACE TABLE bronze.FINANCE_GLNAMES
(
	HashKey VARCHAR(255),
	COMPANY	smallint	,
	ACCT_UNIT	char(15)	,
	VAR_LEVELS	char(30)	,
	DESCRIPTION	char(30)	,
	CHART_SECTION	char(1)	,
	CURRENCY_CODE	char(5)	,
	PERSON_RESP	char(15)	,
	ACTIVE_STATUS	char(1)	,
	ACCT_GENERATE	char(1)	,
	POSTING_FLAG	char(1)	,
	VAR_LEVEL_DISP	char(34)	,
	LEVEL_DEPTH	tinyint	,
	LEVEL_DETAIL_01	decimal(15,0)	,
	LEVEL_DETAIL_02	decimal(15,0)	,
	LEVEL_DETAIL_03	decimal(15,0)	,
	LEVEL_DETAIL_04	decimal(15,0)	,
	LEVEL_DETAIL_05	decimal(15,0)	,
	OBJ_ID	decimal(12,0)	,
	PARENT_OBJ_ID	decimal(12,0)	,
	CREATED_BY	char(10)	,
	LAST_UPDT_DATE	date	,
	LAST_UPDT_TIME	int	,
	LAST_UPDATE_BY	char(10)	,
	L_INDEX	char(4)	,
	GLNSET3_SS_SW	char(1)	,
	L_ATGLN_SS_SW	char(1)	,
	CONSTRAINT FINANCE_GLNAMES_pkey PRIMARY KEY (COMPANY, ACCT_UNIT)
)

-- COMMAND ----------

-- MAGIC %md ##FINANCE_GLTRANS

-- COMMAND ----------

CREATE OR REPLACE TABLE  bronze.FINANCE_GLTRANS
(
	HashKey VARCHAR(255),
	COMPANY	smallint	,
	FISCAL_YEAR	smallint	,
	ACCT_PERIOD	smallint	,
	CONTROL_GROUP	int	,
	SYSTEM	char(2)	,
	JE_TYPE	char(1)	,
	JE_SEQUENCE	smallint	,
	LINE_NBR	int	,
	OBJ_ID	decimal(12,0)	,
	STATUS	tinyint	,
	VAR_LEVELS	char(30)	,
	ACCT_UNIT	char(15)	,
	ACCOUNT	int	,
	SUB_ACCOUNT	smallint	,
	SOURCE_CODE	char(2)	,
	R_DATE	date	,
	REFERENCE	char(10)	,
	DESCRIPTION	char(30)	,
	BASE_AMOUNT	decimal(18,2)	,
	BASE_ND	tinyint	,
	UNITS_AMOUNT	decimal(15,2)	,
	AUTO_REV	char(1)	,
	TO_COMPANY	smallint	,
	BASE_ZONE	char(15)	,
	POSTING_DATE	date	,
	ACTIVITY	char(15)	,
	ACCT_CATEGORY	char(5)	,
	CURRENCY_CODE	char(5)	,
	BASERATE	decimal(14,7)	,
	TRAN_AMOUNT	decimal(18,2)	,
	TRAN_ND	tinyint	,
	ACCT_CURRENCY	char(5)	,
	ACCT_RATE	decimal(14,7)	,
	ACCT_AMOUNT	decimal(18,2)	,
	ACCT_ND	tinyint	,
	ORIG_COMPANY	smallint	,
	ORIG_PROGRAM	char(5)	,
	OPERATOR	char(10)	,
	TO_BASE_AMT	decimal(18,2)	,
	TO_BASE_ND	tinyint	,
	TO_BASERATE	decimal(14,7)	,
	TO_BASE_CURR	char(5)	,
	RECONCILE	char(2)	,
	NEGATIVE_ADJ	char(1)	,
	EFFECT_DATE	date	,
	UPDATE_DATE	date	,
	SEQ_TRNS_NBR	decimal(10,0)	,
	JBK_TRNS_NBR	decimal(10,0)	,
	CONSOL_AC_FLAG	char(1)	,
	CT_FR_COMPANY	smallint	,
	RPT_AMOUNT_1	decimal(18,2)	,
	RPT_RATE_1	decimal(14,7)	,
	RPT_ND_1	tinyint	,
	RPT_AMOUNT_2	decimal(18,2)	,
	RPT_RATE_2	decimal(14,7)	,
	RPT_ND_2	tinyint	,
	CREATED_BY	char(10)	,
	LAST_UPDT_DATE	date	,
	LAST_UPDT_TIME	int	,
	LAST_UPDATE_BY	char(10)	,
	L_INDEX	char(4)	,
	GLTSET2_SS_SW	char(1)	,
	GLTSET3_SS_SW	char(1)	,
	GLTSET6_SS_SW	char(1)	,
	GLTSET8_SS_SW	char(1)	,
	L_ATGLT_SS_SW	char(1)	,
	CONSTRAINT FINANCE_GLTRANS_pkey PRIMARY KEY (COMPANY, FISCAL_YEAR, ACCT_PERIOD, CONTROL_GROUP, SYSTEM, JE_TYPE, JE_SEQUENCE, LINE_NBR)
)

-- COMMAND ----------

-- MAGIC %md ##FINANCE_GLSRCCODE

-- COMMAND ----------

CREATE OR REPLACE TABLE  bronze.FINANCE_GLSRCCODE
(
	SOURCE_CODE	char(2)	,
	DESCRIPTION	char(30)	,
	SOURCE_TYPE	char(1)	,
	EDIT_TYPE	char(1)	,
	USED_FLAG	char(1)	,
	LAST_SEQ	smallint	,
	LAST_FIELD_NBR	smallint	,
	PRIMARY_SYSTEM	char(2)	,
	SOURCE_GROUP	char(5)	,
	CONSTRAINT FINANCE_GLSRCCODE_pkey PRIMARY KEY (SOURCE_CODE)
)

-- COMMAND ----------

-- MAGIC %md ##FINANCE_APDISTRIB

-- COMMAND ----------

CREATE OR REPLACE TABLE  bronze.FINANCE_APDISTRIB
(
	HashKey VARCHAR(255),
	COMPANY	smallint	,
	API_OBJ_ID	decimal(12,0)	,
	VENDOR	char(9)	,
	INVOICE	char(22)	,
	SUFFIX	smallint	,
	CANCEL_SEQ	smallint	,
	ORIG_DIST_SEQ	int	,
	DIST_SEQ_NBR	int	,
	DIST_TYPE	char(1)	,
	PROC_LEVEL	char(5)	,
	POST_OPTION	char(1)	,
	INVOICE_TYPE	char(1)	,
	REC_STATUS	tinyint	,
	INV_CURRENCY	char(5)	,
	TAX_RATE	decimal(7,7)	,
	CURR_RATE	decimal(14,7)	,
	ORIG_BASE_AMT	decimal(18,2)	,
	BASE_ND	tinyint	,
	ORIG_TRAN_AMT	decimal(18,2)	,
	TRAN_ND	tinyint	,
	TO_BASE_AMT	decimal(18,2)	,
	TO_BASE_ND	tinyint	,
	TAXABLE_AMT	decimal(18,2)	,
	UNT_AMOUNT	decimal(18,2)	,
	DIST_COMPANY	smallint	,
	DIS_ACCT_UNIT	char(15)	,
	DIS_ACCOUNT	int	,
	DIS_SUB_ACCT	smallint	,
	DISTRIB_DATE	date	,
	TAX_INDICATOR	tinyint	,
	TAX_SEQ_NBR	smallint	,
	TAX_CODE	char(10)	,
	TAX_TYPE	char(1)	,
	DESCRIPTION	char(30)	,
	DST_REFERENCE	char(10)	,
	ACTIVITY	char(15)	,
	ACCT_CATEGORY	char(5)	,
	BILL_CATEGORY	char(32)	,
	ACCR_CODE	char(4)	,
	PO_NUMBER	char(14)	,
	PO_RELEASE	smallint	,
	PO_CODE	char(4)	,
	PO_LINE_NBR	int	,
	PO_AOC_CODE	char(2)	,
	GLT_OBJ_ID	decimal(12,0)	,
	ATN_OBJ_ID	decimal(12,0)	,
	ASSET_FLAG	char(1)	,
	DIST_CODE	char(9)	,
	TAX_POINT	char(1)	,
	VAT_REVERSE_FL	char(1)	,
	DST_OBJ_ID	decimal(12,0)	,
	MA_CREATE_FL	char(1)	,
	TAX_USAGE_CD	char(10)	,
	TRAN_DIST_FLAG	char(1)	,
	PULL_FOR_FR_FL	char(1)	,
	AC_UPD_STATUS	tinyint	,
	AC_UPD_DATE	date	,
	AC_UPD_TIME	decimal(6,0)	,
	DIVERSE_CODE	char(5)	,
	DISTRIB_ADJ	tinyint	,
	TAX_FLAG	char(1)	,
	ICN_CODE	char(8)	,
	WEIGHT	decimal(9,3)	,
	SUPLMNTARY_QTY	decimal(13,4)	,
	LINE_TYPE	char(1)	,
	STATEMENT	char(22)	,
	TXN_NBR	char(22)	,
	RETAINAGE	tinyint	,
	PROD_TAX_CAT	char(15)	,
	CREATED_BY	char(10)	,
	LAST_UPDT_DATE	date	,
	LAST_UPDT_TIME	int	,
	LAST_UPDATE_BY	char(10)	,
	LTR_OF_GUARAN	char(20)	,
	L_INDEX	char(4)	,
	APDSET10_SS_SW	char(1)	,
	APDSET11_SS_SW	char(1)	,
	APDSET12_SS_SW	char(1)	,
	APDSET5_SS_SW	char(1)	,
	APDSET6_SS_SW	char(1)	,
	APDSET8_SS_SW	char(1)	,
	APDSET9_SS_SW	char(1)	,
	L_ATAPD_SS_SW	char(1)	,
	CONSTRAINT FINANCE_APDISTRIB_pkey PRIMARY KEY (API_OBJ_ID, DIST_SEQ_NBR)
)

-- COMMAND ----------

-- MAGIC %md ##FINANCE_APVENMAST

-- COMMAND ----------

CREATE OR REPLACE TABLE  bronze.FINANCE_APVENMAST
(
	HashKey VARCHAR(255),
	VENDOR_GROUP	char(4)	,
	VENDOR	char(9)	,
	VEN_CLASS	char(3)	,
	VENDOR_VNAME	char(30)	,
	VENDOR_SNAME	char(30)	,
	VENDOR_CONTCT	char(30)	,
	REMIT_TO_CODE	char(4)	,
	PURCH_FR_LOC	char(4)	,
	PAY_VENDOR	char(9)	,
	VENDOR_STATUS	char(1)	,
	VEN_PRIORITY	smallint	,
	PHONE_PREFIX	char(6)	,
	PHONE_NUM	char(15)	,
	PHONE_EXT	char(5)	,
	FAX_PREFIX	char(6)	,
	FAX_NUM	char(15)	,
	FAX_EXT	char(5)	,
	TELEX_NUM	char(15)	,
	TERM_CODE	char(5)	,
	INV_CURRENCY	char(5)	,
	BAL_CURRENCY	char(5)	,
	CURR_RECALC	char(1)	,
	SEP_CHK_FLAG	char(1)	,
	TAX_ID	char(20)	,
	TAX_EXEMPT_CD	char(1)	,
	TAX_CODE	char(10)	,
	HOLD_FLAG	char(1)	,
	DIST_CODE	char(9)	,
	ACCR_CODE	char(4)	,
	BANK_INST_CODE	char(3)	,
	CASH_CODE	char(4)	,
	BANK_ENTITY	char(15)	,
	BANK_CURRENCY	char(5)	,
	VBANK_ACCT_NO	char(35)	,
	VBANK_ACCT_TP	char(1)	,
	VBANK_IDENT	char(1)	,
	CROSS_IDENT	char(1)	,
	INCOME_CODE	char(4)	,
	INCOME_WH_FLG	char(1)	,
	EDI_NBR	char(15)	,
	ACH_PRENOT	char(1)	,
	MAX_INV_AMT	decimal(18,2)	,
	CREATE_DATE	date	,
	ORIGIN_DATE	date	,
	OPERATOR	char(10)	,
	USER_NAME_01	char(20)	,
	USER_NAME_02	char(20)	,
	USER_NAME_03	char(20)	,
	USER_NAME_04	char(20)	,
	USER_NAME_05	char(20)	,
	USER_NAME_06	char(20)	,
	CUST_GROUP	char(5)	,
	CUSTOMER	char(9)	,
	LEGAL_NAME	char(80)	,
	PRIME_RATE	decimal(7,5)	,
	INVOICE_GROUP	char(4)	,
	DISCOUNT_CODE	char(10)	,
	ERS_CAPABLE	char(1)	,
	INVC_REF_TYPE	char(2)	,
	EDI_AUTO_REL	char(1)	,
	AUTH_CODE	char(3)	,
	APPRVL_EXISTS	char(1)	,
	ACTIVITY	char(15)	,
	ACCT_CATEGORY	char(5)	,
	CHARGE_CODE	char(1)	,
	PMT_CAT_CODE	char(6)	,
	NORM_EXP_CODE	char(1)	,
	PMT_FORM	char(2)	,
	SWIFT_ID	char(12)	,
	PROC_GRP	char(4)	,
	MATCH_TABLE	char(10)	,
	DISC_CALC_DATE	char(1)	,
	CREATE_POD_FL	char(1)	,
	HANDLING_CODE	char(4)	,
	ENCLOSURE	char(1)	,
	REQ_MATCH_REF	char(1)	,
	POOL_OPTION	tinyint	,
	HOLD_INSP_FLAG	char(1)	,
	WRITE_OFF_AMT	decimal(18,2)	,
	VEN_CLAIM_TYPE	char(2)	,
	CLAIM_HOLD_CD	char(4)	,
	CB_HOLD_CODE	char(4)	,
	CB_MINIMUM_AMT	decimal(18,2)	,
	REPLACE_GOODS	char(1)	,
	SHIP_OR_HOLD	char(1)	,
	ERS_HANDLING	char(4)	,
	E_MAIL_ADDRESS	char(60)	,
	URL_ADDR	char(60)	,
	VEND_ACCT	char(30)	,
	LANGUAGE_CODE	char(10)	,
	TAX_USAGE_CD	char(10)	,
	VAT_REG_CTRY	char(2)	,
	VAT_REG_NBR	char(12)	,
	VALIDATE_PO	char(1)	,
	REQUIRE_PO	char(1)	,
	WORKFLOW_GROUP	char(20)	,
	MBL_INT_PREFIX	char(6)	,
	MOBILE_NUM	char(15)	,
	MOBILE_EXT	char(5)	,
	PAY_IMM_FLAG	char(1)	,
	DIVERSE_CODE	char(5)	,
	INTM_BANK_ENT	char(15)	,
	INTM_BANK_ACCT	char(35)	,
	INTM_BANK_IDNT	char(1)	,
	INTM_BANK_CURR	char(5)	,
	INTM_PRENOT	char(1)	,
	INTM_SWIFT_ID	char(12)	,
	INTM_PMT_CAT	char(6)	,
	INTM_NORM_EXP	char(1)	,
	INTM_PMT_FORM	char(2)	,
	INTM_CHRG_CD	char(1)	,
	INTM_CRS_IDENT	char(1)	,
	RULE_GROUP	char(10)	,
	FLOAT_DAYS	smallint	,
	MTCH_PREPAY_FL	char(1)	,
	MTCH_PREPAY_MT	tinyint	,
	BUILD_SOC_REF	char(18)	,
	BUILD_ACCT_NM	char(18)	,
	XREF_FLAG	char(1)	,
	GIRO_NUMBER	char(15)	,
	CR_CARD_NUMBER	char(16)	,
	BANK_INSTRUCT1	char(35)	,
	BANK_INSTRUCT2	char(35)	,
	BANK_INSTRUCT3	char(35)	,
	BANK_INSTRUCT4	char(35)	,
	AP_OBJ_ID	decimal(12,0)	,
	P_CARD_FLAG	tinyint	,
	PCARD_NBR	char(16)	,
	VAL_DIV_DATE	char(1)	,
	RET_ACCR_CODE	char(4)	,
	GLN_NBR	char(13)	,
	TIN_TYPE	tinyint	,
	TIN_NOT	tinyint	,
	TIN_VERIFIED	tinyint	,
	SEC_WTH_EXEMPT	char(1)	,
	SEC_WTH_CODE1	char(10)	,
	SEC_WTH_CODE2	char(10)	,
	SEC_WTH_CODE3	char(10)	,
	CREATED_BY	char(10)	,
	LAST_UPDT_DATE	date	,
	LAST_UPDT_TIME	int	,
	LAST_UPDATE_BY	char(10)	,
	VALID_CERT_DT	char(1)	,
	FOR_ECON_CODE	char(10)	,
	SOCIAL_ID1	char(80)	,
	SOCIAL_ID2	char(80)	,
	SOCIAL_ID3	char(80)	,
	SOCIAL_ID4	char(80)	,
	SOCIAL_ID5	char(80)	,
	CARRIER_FLAG	char(1)	,
	BANK_CODE	char(2)	,
	BANK_ID	char(9)	,
	ASSIGNMENT_NBR	char(14)	,
	DEBITING_SIGN	char(1)	,
	INTM_BANK_CODE	char(2)	,
	INTM_BANK_ID	char(9)	,
	INTM_ASSIGN_NO	char(14)	,
	INTM_DEBITING	char(1)	,
	CHK_DIG_TYPE	char(10)	,
	SEPA_FLAG	char(1)	,
	W8_VERIFIED	char(1)	,
	FATCA_ID	char(6)	,
	FIN_INST_TYPE	char(5)	,
	GIIN_CAT_CODE	char(2)	,
	ISO_CTRY_NBR	smallint	,
	FATCA_WITHOLD	decimal(7,4)	,
	FATCA_INC_CODE	char(4)	,
	FATCA_AU	char(15)	,
	FATCA_ACCOUNT	int	,
	FATCA_SUB_ACCT	smallint	,
	OPEN_ZERO_COST	char(1)	,
	ENABLE_ASN_BOD	tinyint	,
	EXTERNAL_KEY	char(25)	,
	EXT_ACCT_ENT	char(22)	,
	EXT_LOCATION	char(22)	,
	L_INDEX	char(4)	,
	VENSET11_SS_SW	char(1)	,
	VENSET8_SS_SW	char(1)	,
	L_ATVEN_SS_SW	char(1)	,
	CONSTRAINT FINANCE_APVENMAST_pkey PRIMARY KEY (VENDOR_GROUP, VENDOR)
)

-- COMMAND ----------

-- MAGIC %md ##FINANCE_APVENCLASS

-- COMMAND ----------

CREATE OR REPLACE TABLE  bronze.FINANCE_APVENCLASS
(
	VENDOR_GROUP	char(4)	,
	VEN_CLASS	char(3)	,
	VEN_PRIORITY	smallint	,
	DESCRIPTION	char(30)	,
	ZERO_CHECK	char(1)	,
	POST_OPTION	char(1)	,
	DIST_CODE	char(9)	,
	MAX_PMT_AMT	decimal(18,2)	,
	MAX_PMT_HOLD	char(4)	,
	INCOME_CODE	char(4)	,
	CURRENCY_CODE	char(5)	,
	TAX_EXEMPT_CD	char(1)	,
	TAX_CODE	char(10)	,
	CASH_CODE	char(4)	,
	BANK_INST_CODE	char(3)	,
	ZERO_PMT_CODE	char(3)	,
	ENCLOSURE	char(1)	,
	TAX_USAGE_CD	char(10)	,
	HANDLING_CODE	char(4)	,
	VALIDATE_PO	char(1)	,
	REQUIRE_PO	char(1)	,
	MTCH_PREPAY_FL	char(1)	,
	MTCH_PREPAY_MT	tinyint	,
	MATCH_TABLE	char(10)	,
	RULE_GROUP	char(10)	,
	RETAIL_FLAG	tinyint	,
	EAM_VEN_FL	tinyint	,
	MIN_PMT_HOLD	char(4)	,
	MIN_PMT_AMT	decimal(18,2)	,
	TAX_OVERRIDE	char(1)	,
	CONSTRAINT FINANCE_APVENCLASS_pkey PRIMARY KEY (VENDOR_GROUP, VEN_CLASS)
)

-- COMMAND ----------

-- MAGIC %md ##FINANCE_ARDISTRIB

-- COMMAND ----------

CREATE OR REPLACE TABLE  bronze.FINANCE_ARDISTRIB
(
	HashKey VARCHAR(255),
	GL_COMPANY	smallint	,
	ACCT_UNIT	char(15)	,
	ACCOUNT	int	,
	SUB_ACCT	smallint	,
	GL_DATE	date	,
	CREATE_DATE	date	,
	CREATE_TIME	decimal(6,0)	,
	PROG_SEQ_NBR	int	,
	COMPANY	smallint	,
	BATCH_NBR	int	,
	CUSTOMER	char(9)	,
	PROCESS_LEVEL	char(5)	,
	TRANS_TYPE	char(1)	,
	INVOICE	char(22)	,
	TRANS_DATE	date	,
	DIST_SEQ	smallint	,
	DST_TYPE	char(2)	,
	PAYMENT_SEQ	int	,
	ACCUM_TYPE	char(1)	,
	TRAN_AMT	decimal(18,2)	,
	TO_COMP_AMT	decimal(18,2)	,
	UNITS	decimal(15,2)	,
	R_DESC	char(30)	,
	ACTIVITY	char(15)	,
	ACCT_CATEGORY	char(5)	,
	STATUS	tinyint	,
	ORIG_CURRENCY	char(5)	,
	ORIG_RATE	decimal(14,7)	,
	ORIG_AMT	decimal(18,2)	,
	CAT_TYPE	char(1)	,
	AR_CATEGORY	char(5)	,
	TAX_CODE	char(10)	,
	TRAN_TAXABLE	decimal(18,2)	,
	UPDATE_SUM	char(2)	,
	ORIG_ND	tinyint	,
	AUTO_REV	char(1)	,
	ORIG_COMPANY	smallint	,
	ORIG_TAXABLE	decimal(18,2)	,
	DOCUMENT_NBR	char(27)	,
	DST_SOURCE	char(1)	,
	BASE_ACCTUNIT	char(15)	,
	JRNL_BOOK_NBR	char(12)	,
	MX_VALUE_01	char(32)	,
	MX_VALUE_02	char(32)	,
	MX_VALUE_03	char(32)	,
	GLT_OBJ_ID	decimal(12,0)	,
	DRAFT_SOURCE	char(1)	,
	ATN_OBJ_ID	decimal(12,0)	,
	TAX_POINT	char(1)	,
	JBK_SEQ_NBR	decimal(10,0)	,
	LINE_TYPE	char(1)	,
	WEIGHT	decimal(9,3)	,
	ICN_CODE	char(8)	,
	SUPLMNTARY_QTY	decimal(13,4)	,
	BAL_DATE	date	,
	ARA_OBJ_ID	decimal(12,0)	,
	AMDSET10_SS_SW	char(1)	,
	AMDSET2_SS_SW	char(1)	,
	AMDSET3_SS_SW	char(1)	,
	AMDSET4_SS_SW	char(1)	,
	AMDSET6_SS_SW	char(1)	,
	AMDSET7_SS_SW	char(1)	,
	AMDSET8_SS_SW	char(1)	,
	AMDSET9_SS_SW	char(1)	,
	CONSTRAINT FINANCE_ARDISTRIB_pkey PRIMARY KEY (GL_COMPANY, ACCT_UNIT, ACCOUNT, SUB_ACCT, GL_DATE, CREATE_DATE, CREATE_TIME, PROG_SEQ_NBR)
)

-- COMMAND ----------

-- MAGIC %md ##FINANCE_ARCUSTOMER

-- COMMAND ----------

CREATE OR REPLACE TABLE  bronze.FINANCE_ARCUSTOMER
(
	COMPANY	smallint	,
	CUSTOMER	char(9)	,
	ACTIVE_STATUS	char(1)	,
	NAT_FLAG	char(1)	,
	SEARCH_NAME	char(30)	,
	HOLD_CODE	char(4)	,
	CONTACT	char(20)	,
	INT_PREFIX	char(6)	,
	PHONE_NMBR	char(15)	,
	PHONE_EXT	char(5)	,
	TELEX_NBR	char(15)	,
	EDI_NBR	char(15)	,
	ALT_EDI_NBR	char(95)	,
	ALT_EDI_TYPE	char(5)	,
	FAX_NMBR	char(15)	,
	FAX_EXT	char(5)	,
	START_DATE	date	,
	CREDIT_ANLYST	char(4)	,
	CURRENCY_CD	char(5)	,
	SALESMAN	smallint	,
	RISK_CD	char(1)	,
	DEFAULT_CODE	char(5)	,
	MAJ_CLASS	char(4)	,
	MIN_CLASS	char(4)	,
	CURR_BAL	decimal(18,2)	,
	DRAFT_BAL	decimal(18,2)	,
	OPEN_ORDS	decimal(18,2)	,
	ORDER_LIM	decimal(15,0)	,
	CREDIT_LIM	decimal(15,0)	,
	CREDIT_LIM_DAT	date	,
	CREDIT_REVDAYS	decimal(3,0)	,
	LAST_PMT_AMT	decimal(18,2)	,
	LAST_PMT_DATE	date	,
	LAST_INV_DATE	date	,
	LAST_INV_AMT	decimal(18,2)	,
	LAST_STA_DATE	date	,
	LAST_STA_BAL	decimal(18,2)	,
	REVIEW_DATE	date	,
	REVIEW_CODE	char(1)	,
	HIGH_BAL_01	decimal(15,0)	,
	HIGH_BAL_02	decimal(15,0)	,
	HIGH_BAL_03	decimal(15,0)	,
	HIGH_BAL_04	decimal(15,0)	,
	HIGH_BAL_05	decimal(15,0)	,
	HIGH_BAL_06	decimal(15,0)	,
	HIGH_BAL_07	decimal(15,0)	,
	HIGH_BAL_08	decimal(15,0)	,
	HIGH_BAL_09	decimal(15,0)	,
	HIGH_BAL_10	decimal(15,0)	,
	HIGH_BAL_11	decimal(15,0)	,
	HIGH_BAL_12	decimal(15,0)	,
	HIGH_BAL_13	decimal(15,0)	,
	PER_RTMS_01	decimal(3,0)	,
	PER_RTMS_02	decimal(3,0)	,
	PER_RTMS_03	decimal(3,0)	,
	PER_RTMS_04	decimal(3,0)	,
	PER_RTMS_05	decimal(3,0)	,
	PER_RTMS_06	decimal(3,0)	,
	PER_RTMS_07	decimal(3,0)	,
	PER_RTMS_08	decimal(3,0)	,
	PER_RTMS_09	decimal(3,0)	,
	PER_RTMS_10	decimal(3,0)	,
	PER_RTMS_11	decimal(3,0)	,
	PER_RTMS_12	decimal(3,0)	,
	PER_RTMS_13	decimal(3,0)	,
	PAID_PRMPT_01	decimal(5,0)	,
	PAID_PRMPT_02	decimal(5,0)	,
	PAID_PRMPT_03	decimal(5,0)	,
	PAID_PRMPT_04	decimal(5,0)	,
	PAID_PRMPT_05	decimal(5,0)	,
	PAID_PRMPT_06	decimal(5,0)	,
	PAID_PRMPT_07	decimal(5,0)	,
	PAID_PRMPT_08	decimal(5,0)	,
	PAID_PRMPT_09	decimal(5,0)	,
	PAID_PRMPT_10	decimal(5,0)	,
	PAID_PRMPT_11	decimal(5,0)	,
	PAID_PRMPT_12	decimal(5,0)	,
	INV_PAID_01	decimal(5,0)	,
	INV_PAID_02	decimal(5,0)	,
	INV_PAID_03	decimal(5,0)	,
	INV_PAID_04	decimal(5,0)	,
	INV_PAID_05	decimal(5,0)	,
	INV_PAID_06	decimal(5,0)	,
	INV_PAID_07	decimal(5,0)	,
	INV_PAID_08	decimal(5,0)	,
	INV_PAID_09	decimal(5,0)	,
	INV_PAID_10	decimal(5,0)	,
	INV_PAID_11	decimal(5,0)	,
	INV_PAID_12	decimal(5,0)	,
	COLLECT_DAYS_01	decimal(3,0)	,
	COLLECT_DAYS_02	decimal(3,0)	,
	COLLECT_DAYS_03	decimal(3,0)	,
	COLLECT_DAYS_04	decimal(3,0)	,
	COLLECT_DAYS_05	decimal(3,0)	,
	COLLECT_DAYS_06	decimal(3,0)	,
	COLLECT_DAYS_07	decimal(3,0)	,
	COLLECT_DAYS_08	decimal(3,0)	,
	COLLECT_DAYS_09	decimal(3,0)	,
	COLLECT_DAYS_10	decimal(3,0)	,
	COLLECT_DAYS_11	decimal(3,0)	,
	CURR_CASH	decimal(18,2)	,
	CURR_CSH_DAYS	decimal(18,2)	,
	YTD_CASH	decimal(18,2)	,
	YTD_CSH_DAYS	decimal(18,2)	,
	YEAR_2_DAYS	decimal(3,0)	,
	STATIC_CUR	decimal(18,2)	,
	AGING_01	decimal(18,2)	,
	AGING_02	decimal(18,2)	,
	AGING_03	decimal(18,2)	,
	AGING_04	decimal(18,2)	,
	AGING_05	decimal(18,2)	,
	LAST_COMMENT	int	,
	DISP_NBR	decimal(3,0)	,
	DISP_AMT	decimal(18,2)	,
	PL_EXCL_FL	char(1)	,
	AGE_DISPUTES	char(1)	,
	DISPUTES_FIN	char(1)	,
	AUTO_APP_FL	char(1)	,
	AUTO_DUNN_FL	char(1)	,
	DISC_GRACE_PD	smallint	,
	CR_VAR_PCT	smallint	,
	MEMO_TERM	char(5)	,
	CHRGBK_PRT_FL	char(1)	,
	OPEN_BAL_FWD	char(1)	,
	STATEMENT_REQ	char(1)	,
	STMNT_CYCLE	char(2)	,
	LOCK_BOX	char(2)	,
	ZERO_STMNT_FL	char(1)	,
	CRED_STMNT_FL	char(1)	,
	PAST_STMNT_FL	char(1)	,
	OVER_STMNT_FL	char(1)	,
	MAX_AUTO_AMT_01	decimal(18,2)	,
	MAX_AUTO_AMT_02	decimal(18,2)	,
	MAX_AUTO_AMT_03	decimal(18,2)	,
	MAX_AUTO_PCT_01	decimal(5,5)	,
	MAX_AUTO_PCT_02	decimal(5,5)	,
	MAX_AUTO_PCT_03	decimal(5,5)	,
	AUTO_REAS_CD_01	char(4)	,
	AUTO_REAS_CD_02	char(4)	,
	AUTO_REAS_CD_03	char(4)	,
	DISC_REAS_CD	char(4)	,
	BANK_INST_CODE	char(3)	,
	DRAFT_FLAG	char(1)	,
	AR_CODE	char(4)	,
	TERMS_CD	char(5)	,
	TERMS_CASH	decimal(18,2)	,
	TERMS_CSH_DAYS	decimal(18,2)	,
	DBT_RATIO_01	decimal(3,0)	,
	DBT_RATIO_02	decimal(3,0)	,
	DBT_RATIO_03	decimal(3,0)	,
	DBT_RATIO_04	decimal(3,0)	,
	DBT_RATIO_05	decimal(3,0)	,
	DBT_RATIO_06	decimal(3,0)	,
	DBT_RATIO_07	decimal(3,0)	,
	DBT_RATIO_08	decimal(3,0)	,
	DBT_RATIO_09	decimal(3,0)	,
	DBT_RATIO_10	decimal(3,0)	,
	DBT_RATIO_11	decimal(3,0)	,
	DBT_PR_YR	decimal(3,0)	,
	DBT_YTD_CASH	decimal(18,2)	,
	DBT_YTD_DAYS	decimal(18,2)	,
	LATE_PAY_FL	char(1)	,
	FIN_CALC_TYPE	char(1)	,
	FIN_CHRG_CD	char(2)	,
	FIN_GRAC_DAYS	smallint	,
	FIN_MIN_CHRG	decimal(7,2)	,
	FIN_DOC_PRNT	char(1)	,
	LAST_DUNN	smallint	,
	LAST_DUN_DATE	date	,
	LAST_DUN_AMT	decimal(18,2)	,
	TAX_EXEMPT_CD	char(1)	,
	TAX_CODE	char(10)	,
	TERRITORY	char(4)	,
	AGING_CODE	smallint	,
	REVALUE_FL	char(1)	,
	DISHONORED	decimal(5,0)	,
	DISHONORED_AMT	decimal(18,2)	,
	RECONCILE_CASH	decimal(5,0)	,
	RECONCILE_RNEG	decimal(5,0)	,
	RECONCILE_WO	decimal(5,0)	,
	MINIMUM	char(1)	,
	FIN_CYCLE	char(2)	,
	DUN_CYCLE	char(2)	,
	AUTO_METHOD	char(1)	,
	AUTO_REMOVE	char(1)	,
	I_FIN_MIN_CHRG	decimal(7,2)	,
	CB_DTL_DATE	char(1)	,
	VAT_CUST_TYPE	char(2)	,
	VAT_REG_NBR	char(12)	,
	VAT_REG_CTRY	char(2)	,
	DUN_LTR_IND	char(1)	,
	DUN_PROCESS_CD	char(6)	,
	LANGUAGE_CODE	char(10)	,
	LST_DUNLTR_STM	smallint	,
	LAST_LTR_DATE	date	,
	LST_LTRTEXT_CD	char(6)	,
	ASSESS_DUN_FEE	char(1)	,
	CU_NAME	char(30)	,
	CU_ADDR1	char(30)	,
	CU_ADDR2	char(30)	,
	CU_ADDR3	char(30)	,
	CU_ADDR4	char(30)	,
	CU_CITY	char(18)	,
	CU_STATE	char(2)	,
	CU_POSTAL_CODE	char(12)	,
	CU_COUNTRY_CD	char(2)	,
	CU_COUNTRY	char(30)	,
	THIRD_PARTY	char(1)	,
	E_MAIL_ADDRESS	char(60)	,
	URL_ADDR	char(60)	,
	CUST_AUDIT	char(1)	,
	APPLY_MIXED	char(1)	,
	OBJ_ID	decimal(12,0)	,
	PAY_AUTO_AMT	decimal(18,2)	,
	PAY_AUTO_PCT	decimal(5,5)	,
	PAY_REAS_CD	char(4)	,
	MULT_DUN_LTR	char(1)	,
	CU_COUNTY	char(25)	,
	AFFILIATE_FL	char(1)	,
	FOR_ECON_CODE	char(10)	,
	SOCIAL_ID1	char(80)	,
	SOCIAL_ID2	char(80)	,
	SOCIAL_ID3	char(80)	,
	SOCIAL_ID4	char(80)	,
	SOCIAL_ID5	char(80)	,
	CARRIER_FLAG	char(1)	,
	L_INDEX	char(4)	,
	ACMSET4_SS_SW	char(1)	,
	ACMSET9_SS_SW	char(1)	,
	L_ATACM_SS_SW	char(1)	,
	CONSTRAINT FINANCE_ARCUSTOMER_pkey PRIMARY KEY (COMPANY, CUSTOMER)
)

-- COMMAND ----------

-- MAGIC %md ##Pricing_nfi_load_predictions

-- COMMAND ----------

CREATE OR REPLACE TABLE  bronze.Pricing_nfi_load_predictions
        (
                HashKey VARCHAR(255),
                external_load_id string,
                tms_type string,
                high_buy_rate_predicted   decimal(12,5),
                low_buy_rate_predicted    decimal(12,5),
                start_buy_rate_predicted  decimal(12,5),
                target_buy_rate_predicted decimal(12,5),
                confidence_predicted double,
                miles_predicted double,
                rate_predicted_checked      boolean,
                created_date                timestamp,
                last_updated_date           timestamp,
                rate_predicted_request_date timestamp,
                high_buy_rate_gsn           decimal(12,5),
                low_buy_rate_gsn            decimal(12,5),
                start_buy_rate_gsn          decimal(12,5),
                target_buy_rate_gsn         decimal(12,5),
                confidence_level_gsn double,
                gsn_request_date      timestamp,
                gsn_predicted_checked boolean,
                Active SMALLINT
        )

-- COMMAND ----------

-- MAGIC %md ##Pricing_nfi_loads

-- COMMAND ----------

CREATE OR REPLACE TABLE  bronze.Pricing_nfi_loads
(
	HashKey VARCHAR(255),
	id	bigint,
	external_carrier_company_id	string,
	driver_name	string,
	driver_phone	string,
	trailer_number	varchar(250),
	truck_number	varchar(250),
	commodity	string,
	height	integer,
	length	integer,
	quantity	integer,
	ref_numbers	string,
	special_instruction	string,
	status	varchar(250),
	temperature_low	integer,
	temperature_high	integer,
	tord_flag	boolean,
	weight	double,
	width	integer,
	external_load_id	string,
	external_shipper_id	string,
	shipper_name	string,
	booked_date	timestamp,
	miles	double,
	pickup_date	timestamp,
	accessorials	string,
	total_carrier_cost	numeric(12,2),
	total_carrier_rate	numeric(12,5),
	total_fuel_cost	numeric(12,2),
	total_linehaul_cost	numeric(12,2),
	total_shipper_cost	numeric(12,2),
	transport_mode	varchar(100),
	origin_city	varchar(250),
	origin_state	varchar(10),
	origin_kma	varchar(10),
	origin_zip	varchar(10),
	origin_country	string,
	destination_city	varchar(250),
	destination_state	varchar(10),
	destination_kma	varchar(10),
	destination_zip	varchar(10),
	destination_country	string,
	created_date	timestamp,
	last_updated_date	timestamp,
	carrier_name	string,
	carrier_phone	string,
	carrier_account_manager	string,
	covered_date	timestamp,
	shipper_account_manager	string,
	with_extra_stops	boolean,
	stop_count	bigint,
	tms_type	string,
	delivered_date	timestamp,
	office	string,
	transport_type_customer	string,
	transport_type	varchar(100),
	valid	boolean,
	currency	string,
	exchange_rate	numeric(12,7),
	valid_rate	boolean,
	valid_distance	boolean,
	exist_kma	boolean,
	not_tord	boolean,
	valid_weight	boolean,
	valid_distance_with_rate	boolean,
	valid_price	boolean,
	meets_customer_filter	boolean,
	valid_transport_type	boolean,
	valid_country_and_zips	boolean,
	valid_status	boolean,
	valid_pickup_date	boolean,
	with_out_extra_stop	boolean,
	valid_min_rate	boolean,
	valid_max_rate	boolean,
	Active SMALLINT
)

-- COMMAND ----------

