# Databricks notebook source
# MAGIC %md
# MAGIC ## Loads_By_Billing
# MAGIC * **Description:** To extract data from Silver to Gold as delta file
# MAGIC * **Created Date:** 03/07/2025
# MAGIC * **Created By:** Uday
# MAGIC * **Modified Date:** 06/10/2025
# MAGIC * **Modified By:** Uday
# MAGIC * **Changes Made:** Logic Update

# COMMAND ----------

# MAGIC %sql
# MAGIC USE SCHEMA Silver;

# COMMAND ----------

# MAGIC %md
# MAGIC ####Incremental Load View 

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE OR REPLACE VIEW Gold.VW_Fact_Loads_By_Billing AS 
# MAGIC SELECT
# MAGIC   DW_Load_ID,
# MAGIC   Load_Number,
# MAGIC   Admin_Fees_Carrier_USD,
# MAGIC   Admin_Fees_Carrier_CAD,
# MAGIC   Admin_Fees_Customer_USD,
# MAGIC   Admin_Fees_Customer_CAD,
# MAGIC   Billing_Status,
# MAGIC   Actual_Delivered_Date,
# MAGIC   Booking_Type,
# MAGIC   Booked_Date,
# MAGIC   Carrier_Fuel_Surcharge_CAD,
# MAGIC   Carrier_Fuel_Surcharge_USD,
# MAGIC   Carrier_Linehaul_CAD,
# MAGIC   Carrier_Linehaul_USD,
# MAGIC   Carrier_ID,
# MAGIC   Carrier_Name,
# MAGIC   Carrier_New_Office,
# MAGIC   Carrier_Old_Office,
# MAGIC   Carrier_Other_Fees_CAD,
# MAGIC   Carrier_Other_Fees_USD,
# MAGIC   Carrier_Rep_ID,
# MAGIC   Carrier_Rep,
# MAGIC   Combined_Load,
# MAGIC   Consignee_Delivery_Address,
# MAGIC   Consignee_Name,
# MAGIC   Consignee_Pickup_Address,
# MAGIC   Customer_Fuel_Surcharge_USD,
# MAGIC   Customer_Fule_Surcharge_CAD,
# MAGIC   Customer_Linehaul_CAD,
# MAGIC   Customer_Linehaul_USD,
# MAGIC   Customer_Master,
# MAGIC   Customer_ID,
# MAGIC   Customer_Name,
# MAGIC   Customer_New_Office,
# MAGIC   Customer_Old_Office,
# MAGIC   Customer_Other_Fees_CAD,
# MAGIC   Customer_Other_Fees_USD,
# MAGIC   Customer_Rep_ID,
# MAGIC   Customer_Rep,
# MAGIC   Days_Ahead,
# MAGIC   Bounced_Date,
# MAGIC   Cancelled_Date,
# MAGIC   Delivery_Pickup_Charges_Carrier_CAD,
# MAGIC   Delivery_Pickup_Charges_Carrier_USD,
# MAGIC   Delivery_Pickup_Charges_Customer_CAD,
# MAGIC   Delivery_Pickup_Charges_Customer_USD,
# MAGIC   Delivery_Appointment_Date,
# MAGIC   Delivery_EndDate,
# MAGIC   Destination_City,
# MAGIC   Destination_State,
# MAGIC   Destination_Zip,
# MAGIC   DOT_Number,
# MAGIC   Delivery_StartDate,
# MAGIC   Equipment,
# MAGIC   Equipment_Vehicle_Charges_Carrier_CAD,
# MAGIC   Equipment_Vehicle_Charges_Carrier_USD,
# MAGIC   Equipment_Vehicle_Charges_Customer_CAD,
# MAGIC   Equipment_Vehicle_Charges_Customer_USD,
# MAGIC   Expense_CAD,
# MAGIC   Expense_USD,
# MAGIC   Financial_Period_Year,
# MAGIC   GreenScreen_Rate_CAD,
# MAGIC   GreenScreen_Rate_USD,
# MAGIC   Invoice_Amount_CAD,
# MAGIC   Invoice_Amount_USD,
# MAGIC   Invoiced_Date,
# MAGIC   Lawson_ID,
# MAGIC   Load_Currency,
# MAGIC   Load_Flag,
# MAGIC   Load_Lane,
# MAGIC   Load_Status,
# MAGIC   Load_Unload_Charges_Carrier_CAD,
# MAGIC   Load_Unload_Charges_Carrier_USD,
# MAGIC   Load_Unload_Charges_Customer_CAD,
# MAGIC   Load_Unload_Charges_Customer_USD,
# MAGIC   Margin_CAD,
# MAGIC   Margin_USD,
# MAGIC   Market_Buy_Rate_CAD,
# MAGIC   Market_Buy_Rate_USD,
# MAGIC   Market_Destination,
# MAGIC   Market_Lane,
# MAGIC   Market_Origin,
# MAGIC   MC_Number,
# MAGIC   Miles,
# MAGIC   Miscellaneous_Chargers_Carrier_CAD,
# MAGIC   Miscellaneous_Chargers_Carrier_USD,
# MAGIC   Miscellaneous_Chargers_Customers_CAD,
# MAGIC   Miscellaneous_Chargers_Customers_USD,
# MAGIC   Mode,
# MAGIC   On_Time_Delivery,
# MAGIC   On_Time_Pickup,
# MAGIC   Origin_City,
# MAGIC   Origin_State,
# MAGIC   Origin_Zip,
# MAGIC   Permits_Compliance_Charges_Carrier_CAD,
# MAGIC   Permits_Compliance_Charges_Carrier_USD,
# MAGIC   Permits_Compliance_Charges_Customer_CAD,
# MAGIC   Permits_Compliance_Charges_Customer_USD,
# MAGIC   Pickup_Appointment_Date,
# MAGIC   Actual_Pickup_Date,
# MAGIC   Pickup_EndDate,
# MAGIC   Pickup_StartDate,
# MAGIC   PO_Number,
# MAGIC   PreBookStatus,
# MAGIC   Revenue_CAD,
# MAGIC   Revenue_USD,
# MAGIC   Rolled_Date,
# MAGIC   Sales_Rep_ID,
# MAGIC   Sales_Rep,
# MAGIC   Ship_Date,
# MAGIC   Spot_Margin,
# MAGIC   Spot_Revenue,
# MAGIC   Tender_Source_Type,
# MAGIC   Tendered_Date,
# MAGIC   TMS_System,
# MAGIC   Trailer_Number,
# MAGIC   Transit_Routing_Chargers_Carrier_CAD,
# MAGIC   Transit_Routing_Chargers_Carrier_USD,
# MAGIC   Transit_Routing_Chargers_Customer_CAD,
# MAGIC   Transit_Routing_Chargers_Customer_USD,
# MAGIC   Week_Number,
# MAGIC   Hashkey
# MAGIC FROM
# MAGIC
# MAGIC -- Union from silver_aljex
# MAGIC (SELECT
# MAGIC   DW_Load_ID, Load_number, Actual_Delivered_Date, Booked_Date,
# MAGIC   Carrier_Fuel_Surcharge_CAD, Carrier_Fuel_Surcharge_USD,
# MAGIC   Carrier_Linehaul_CAD, Carrier_Linehaul_USD,
# MAGIC   Carrier_Name, Carrier_New_Office, Carrier_Old_Office,
# MAGIC   Carrier_Other_Fees_CAD, Carrier_Other_Fees_USD,
# MAGIC   Carrier_ID, Carrier_Rep_ID, Carrier_Rep, Combined_Load,
# MAGIC   Consignee_Delivery_Address, Consignee_Name, Consignee_Pickup_Address,
# MAGIC   Customer_Fuel_Surcharge_USD, Customer_Fule_Surcharge_CAD,
# MAGIC   Customer_Linehaul_CAD, Customer_Linehaul_USD,
# MAGIC   Customer_ID, Customer_Master, Customer_Name, Customer_New_Office, Customer_Old_Office,
# MAGIC   Customer_Other_Fees_CAD, Customer_Other_Fees_USD,
# MAGIC   Customer_Rep_ID, Customer_Rep, Days_Ahead, Bounced_Date, Cancelled_Date,
# MAGIC   Delivery_Pickup_Charges_Carrier_CAD, Delivery_Pickup_Charges_Carrier_USD,
# MAGIC   Delivery_Pickup_Charges_Customer_CAD, Delivery_Pickup_Charges_Customer_USD,
# MAGIC   Delivery_Appointment_Date, Delivery_EndDate, Destination_City, Destination_State, Destination_Zip,
# MAGIC   DOT_Number, Delivery_StartDate, Equipment,
# MAGIC   Equipment_Vehicle_Charges_Carrier_CAD, Equipment_Vehicle_Charges_Carrier_USD,
# MAGIC   Equipment_Vehicle_Charges_Customer_CAD, Equipment_Vehicle_Charges_Customer_USD,
# MAGIC   Expense_CAD, Expense_USD, Financial_Period_Year,
# MAGIC   GreenScreen_Rate_CAD, GreenScreen_Rate_USD,
# MAGIC   Invoice_Amount_CAD, Invoice_Amount_USD, Invoiced_Date,
# MAGIC   Lawson_ID, Load_Currency, Load_Flag, Load_Lane, Load_Status,
# MAGIC   Load_Unload_Charges_Carrier_CAD, Load_Unload_Charges_Carrier_USD,
# MAGIC   Load_Unload_Charges_Customer_CAD, Load_Unload_Charges_Customer_USD,
# MAGIC   Margin_CAD, Margin_USD, Market_Buy_Rate_CAD, Market_Buy_Rate_USD,
# MAGIC   Market_Destination, Market_Lane, Market_Origin,
# MAGIC   MC_Number, Miles,
# MAGIC   Miscellaneous_Chargers_Carrier_CAD, Miscellaneous_Chargers_Carrier_USD,
# MAGIC   Miscellaneous_Chargers_Customers_CAD, Miscellaneous_Chargers_Customers_USD,
# MAGIC   Mode, On_Time_Delivery, On_Time_Pickup,
# MAGIC   Origin_City, Origin_State, Origin_Zip,
# MAGIC   Permits_Compliance_Charges_Carrier_CAD, Permits_Compliance_Charges_Carrier_USD,
# MAGIC   Permits_Compliance_Charges_Customer_CAD, Permits_Compliance_Charges_Customer_USD,
# MAGIC   Pickup_Appointment_Date, Actual_Pickup_Date, Pickup_EndDate, Pickup_StartDate,
# MAGIC   PO_Number, PreBookStatus, Revenue_CAD, Revenue_USD,
# MAGIC   Rolled_Date, Sales_Rep_ID, Sales_Rep,
# MAGIC   Ship_Date, Spot_Margin, Spot_Revenue,
# MAGIC   Tender_Source_Type, Tendered_Date, TMS_System, Trailer_Number,
# MAGIC   Transit_Routing_Chargers_Carrier_CAD, Transit_Routing_Chargers_Carrier_USD,
# MAGIC   Transit_Routing_Chargers_Customer_CAD, Transit_Routing_Chargers_Customer_USD,
# MAGIC   Week_Number, Carrier_Final_Rate_CAD, Carrier_Final_Rate_USD,
# MAGIC   Hashkey, 
# MAGIC   Admin_Fees_Carrier_USD, Admin_Fees_Carrier_CAD,
# MAGIC   Admin_Fees_Customer_USD, Admin_Fees_Customer_CAD,
# MAGIC   Billing_Status, Booking_Type
# MAGIC FROM silver_aljex  WHERE Last_Modified_Date > (SELECT LastLoadDateValue - INTERVAL 1 DAY FROM metadata.mastermetadata WHERE TableID = 'SL4') AND Is_Deleted = 0
# MAGIC
# MAGIC UNION ALL
# MAGIC
# MAGIC -- Union from silver_relay
# MAGIC SELECT
# MAGIC   DW_Load_ID, Load_ID, Actual_Delivered_Date, Booked_Date,
# MAGIC   Carrier_Fuel_Surcharge_CAD, Carrier_Fuel_Surcharge_USD,
# MAGIC   Carrier_Linehaul_CAD, Carrier_Linehaul_USD,
# MAGIC   Carrier_Name, Carrier_New_Office, Carrier_Old_Office,
# MAGIC   Carrier_Other_Fees_CAD, Carrier_Other_Fees_USD,
# MAGIC   Carrier_ID, Carrier_Rep_ID, Carrier_Rep, Combined_Load,
# MAGIC   Consignee_Delivery_Address, Consignee_Name, Consignee_Pickup_Address,
# MAGIC   Customer_Fuel_Surcharge_USD, Customer_Fule_Surcharge_CAD,
# MAGIC   Customer_Linehaul_CAD, Customer_Linehaul_USD,
# MAGIC   Customer_ID, Customer_Master, Customer_Name, Customer_New_Office, Customer_Old_Office,
# MAGIC   Customer_Other_Fees_CAD, Customer_Other_Fees_USD,
# MAGIC   Customer_Rep_ID, Customer_Rep, Days_Ahead, Bounced_Date, Cancelled_Date,
# MAGIC   Delivery_Pickup_Charges_Carrier_CAD, Delivery_Pickup_Charges_Carrier_USD,
# MAGIC   Delivery_Pickup_Charges_Customer_CAD, Delivery_Pickup_Charges_Customer_USD,
# MAGIC   Delivery_Appointment_Date, Delivery_EndDate, Destination_City, Destination_State, Destination_Zip,
# MAGIC   DOT_Number, Delivery_StartDate, Equipment,
# MAGIC   Equipment_Vehicle_Charges_Carrier_CAD, Equipment_Vehicle_Charges_Carrier_USD,
# MAGIC   Equipment_Vehicle_Charges_Customer_CAD, Equipment_Vehicle_Charges_Customer_USD,
# MAGIC   Expense_CAD, Expense_USD, Financial_Period_Year,
# MAGIC   GreenScreen_Rate_CAD, GreenScreen_Rate_USD,
# MAGIC   Invoice_Amount_CAD, Invoice_Amount_USD, Invoiced_Date,
# MAGIC   Lawson_ID, Load_Currency, Load_Flag, Load_Lane, Load_Status,
# MAGIC   Load_Unload_Charges_Carrier_CAD, Load_Unload_Charges_Carrier_USD,
# MAGIC   Load_Unload_Charges_Customer_CAD, Load_Unload_Charges_Customer_USD,
# MAGIC   Margin_CAD, Margin_USD, Market_Buy_Rate_CAD, Market_Buy_Rate_USD,
# MAGIC   Market_Destination, Market_Lane, Market_Origin,
# MAGIC   MC_Number, Miles,
# MAGIC   Miscellaneous_Chargers_Carrier_CAD, Miscellaneous_Chargers_Carrier_USD,
# MAGIC   Miscellaneous_Chargers_Customers_CAD, Miscellaneous_Chargers_Customers_USD,
# MAGIC   Mode, On_Time_Delivery, On_Time_Pickup,
# MAGIC   Origin_City, Origin_State, Origin_Zip,
# MAGIC   Permits_Compliance_Charges_Carrier_CAD, Permits_Compliance_Charges_Carrier_USD,
# MAGIC   Permits_Compliance_Charges_Customer_CAD, Permits_Compliance_Charges_Customer_USD,
# MAGIC   Pickup_Appointment_Date, Actual_Pickup_Date, Pickup_EndDate, Pickup_StartDate,
# MAGIC   PO_Number, PreBookStatus, Revenue_CAD, Revenue_USD,
# MAGIC   Rolled_Date, Sales_Rep_ID, Sales_Rep,
# MAGIC   Ship_Date, Spot_Margin, Spot_Revenue,
# MAGIC   Tender_Source_Type, Tendered_Date, TMS_System, Trailer_Number,
# MAGIC   Transit_Routing_Chargers_Carrier_CAD, Transit_Routing_Chargers_Carrier_USD,
# MAGIC   Transit_Routing_Chargers_Customer_CAD, Transit_Routing_Chargers_Customer_USD,
# MAGIC   Week_Number, Carrier_Final_Rate_CAD, Carrier_Final_Rate_USD,
# MAGIC   Hashkey, 
# MAGIC   Admin_Fees_Carrier_USD, Admin_Fees_Carrier_CAD,
# MAGIC   Admin_Fees_Customer_USD, Admin_Fees_Customer_CAD,
# MAGIC   Billing_Status, Booking_Type
# MAGIC FROM silver_relay  WHERE Last_Modified_Date > (SELECT LastLoadDateValue - INTERVAL 1 DAY FROM metadata.mastermetadata WHERE TableID = 'SL5') AND Is_Deleted = 0
# MAGIC
# MAGIC UNION ALL
# MAGIC
# MAGIC -- Union from silver_transfix
# MAGIC SELECT
# MAGIC   DW_Load_ID, Load_Number, Actual_Delivered_Date, Booked_Date,
# MAGIC   Carrier_Fuel_Surcharge_CAD, Carrier_Fuel_Surcharge_USD,
# MAGIC   Carrier_Linehaul_CAD AS Carrier_Linehaul_CAD, -- align spelling
# MAGIC   Carrier_Linehaul_USD AS Carrier_Linehaul_USD,
# MAGIC   Carrier_Name, NULL AS Carrier_New_Office, Carrier_Office AS Carrier_Old_Office,
# MAGIC   Carrier_Other_Fees_CAD, Carrier_Other_Fees_USD,
# MAGIC   NULL AS Carrier_ID, NULL AS Carrier_Rep_ID, NULL AS Carrier_Rep, NULL AS Combined_Load,
# MAGIC   NULL AS Consignee_Delivery_Address, NULL AS Consignee_Name, NULL AS Consignee_Pickup_Address,
# MAGIC   Customer_Fuel_Surcharge_USD, Customer_Fule_Surcharge_CAD,
# MAGIC   Customer_Linehaul_CAD AS Customer_Linehaul_CAD, Customer_Linehaul_USD AS Customer_Linehaul_USD,
# MAGIC   NULL AS Customer_ID, Customer_Master, Customer_Name,
# MAGIC   NULL AS Customer_New_Office, Customer_Office AS Customer_Old_Office,
# MAGIC   Customer_Other_Fees_CAD, Customer_Other_Fees_USD,
# MAGIC   NULL AS Customer_Rep_ID, NULL AS Customer_Rep,
# MAGIC   Days_Ahead, Bounced_Date, Cancelled_Date,
# MAGIC   NULL AS Delivery_Pickup_Charges_Carrier_CAD, NULL AS Delivery_Pickup_Charges_Carrier_USD,
# MAGIC   NULL AS Delivery_Pickup_Charges_Customer_CAD, NULL AS Delivery_Pickup_Charges_Customer_USD,
# MAGIC   Delivery_Appointment_Date, Delivery_EndDate, Destination_City, Destination_State, Destination_Zip,
# MAGIC   DOT_Number, Delivery_StartDate, Equipment,
# MAGIC   NULL AS Equipment_Vehicle_Charges_Carrier_CAD, NULL AS Equipment_Vehicle_Charges_Carrier_USD,
# MAGIC   NULL AS Equipment_Vehicle_Charges_Customer_CAD, NULL AS Equipment_Vehicle_Charges_Customer_USD,
# MAGIC   Expense_CAD, Expense_USD, Financial_Period_Year,
# MAGIC   NULL AS GreenScreen_Rate_CAD, NULL AS GreenScreen_Rate_USD,
# MAGIC   NULL AS Invoice_Amount_CAD, NULL AS Invoice_Amount_USD,
# MAGIC   Invoiced_Date, NULL AS Lawson_ID, Load_Currency, Load_Flag, NULL AS Load_Lane, Load_Status,
# MAGIC   NULL AS Load_Unload_Charges_Carrier_CAD, NULL AS Load_Unload_Charges_Carrier_USD,
# MAGIC   NULL AS Load_Unload_Charges_Customer_CAD, NULL AS Load_Unload_Charges_Customer_USD,
# MAGIC   Margin_CAD, Margin_USD,
# MAGIC   NULL AS Market_Buy_Rate_CAD, NULL AS Market_Buy_Rate_USD,
# MAGIC   NULL AS Market_Destination, NULL AS Market_Lane, NULL AS Market_Origin,
# MAGIC   NULL AS MC_Number, Miles,
# MAGIC   NULL AS Miscellaneous_Chargers_Carrier_CAD, NULL AS Miscellaneous_Chargers_Carrier_USD,
# MAGIC   NULL AS Miscellaneous_Chargers_Customers_CAD, NULL AS Miscellaneous_Chargers_Customers_USD,
# MAGIC   Mode, On_Time_Delivery, On_Time_Pickup, Origin_City, Origin_State, Origin_Zip,
# MAGIC   NULL AS Permits_Compliance_Charges_Carrier_CAD, NULL AS Permits_Compliance_Charges_Carrier_USD,
# MAGIC   NULL AS Permits_Compliance_Charges_Customer_CAD, NULL AS Permits_Compliance_Charges_Customer_USD,
# MAGIC   Pickup_Appointment_Date, Actual_Pickup_Date, Pickup_EndDate, Pickup_StartDate,
# MAGIC   NULL AS PO_Number, PreBookStatus, Revenue_CAD, Revenue_USD,
# MAGIC   Rolled_Date, NULL AS Sales_Rep_ID, NULL AS Sales_Rep,
# MAGIC   Ship_Date, NULL AS Spot_Margin, NULL AS Spot_Revenue,
# MAGIC   NULL AS Tender_Source_Type, Tendered_Date, TMS_System,
# MAGIC   NULL AS Trailer_Number,
# MAGIC   NULL AS Transit_Routing_Chargers_Carrier_CAD, NULL AS Transit_Routing_Chargers_Carrier_USD,
# MAGIC   NULL AS Transit_Routing_Chargers_Customer_CAD, NULL AS Transit_Routing_Chargers_Customer_USD,
# MAGIC   Week_Number, Carrier_Final_Rate_CAD, Carrier_Final_Rate_USD, Hashkey,
# MAGIC   NULL AS Admin_Fees_Carrier_USD, NULL AS Admin_Fees_Carrier_CAD,
# MAGIC   NULL AS Admin_Fees_Customer_USD, NULL AS Admin_Fees_Customer_CAD,
# MAGIC   NULL AS Billing_Status, NULL AS Booking_Type
# MAGIC FROM silver_transfix WHERE Last_Modified_Date > (SELECT LastLoadDateValue - INTERVAL 1 DAY FROM metadata.mastermetadata WHERE TableID = 'SL6') AND Is_Deleted = 0)

# COMMAND ----------

# MAGIC %md
# MAGIC ####Full Load View

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE OR REPLACE VIEW Gold.VW_Fact_Loads_By_Billing_Full_Load AS 
# MAGIC SELECT
# MAGIC   DW_Load_ID,
# MAGIC   Load_Number,
# MAGIC   Admin_Fees_Carrier_USD,
# MAGIC   Admin_Fees_Carrier_CAD,
# MAGIC   Admin_Fees_Customer_USD,
# MAGIC   Admin_Fees_Customer_CAD,
# MAGIC   Billing_Status,
# MAGIC   Actual_Delivered_Date,
# MAGIC   Booking_Type,
# MAGIC   Booked_Date,
# MAGIC   Carrier_Fuel_Surcharge_CAD,
# MAGIC   Carrier_Fuel_Surcharge_USD,
# MAGIC   Carrier_Linehaul_CAD,
# MAGIC   Carrier_Linehaul_USD,
# MAGIC   Carrier_ID,
# MAGIC   Carrier_Name,
# MAGIC   Carrier_New_Office,
# MAGIC   Carrier_Old_Office,
# MAGIC   Carrier_Other_Fees_CAD,
# MAGIC   Carrier_Other_Fees_USD,
# MAGIC   Carrier_Rep_ID,
# MAGIC   Carrier_Rep,
# MAGIC   Combined_Load,
# MAGIC   Consignee_Delivery_Address,
# MAGIC   Consignee_Name,
# MAGIC   Consignee_Pickup_Address,
# MAGIC   Customer_Fuel_Surcharge_USD,
# MAGIC   Customer_Fule_Surcharge_CAD,
# MAGIC   Customer_Linehaul_CAD,
# MAGIC   Customer_Linehaul_USD,
# MAGIC   Customer_Master,
# MAGIC   Customer_ID,
# MAGIC   Customer_Name,
# MAGIC   Customer_New_Office,
# MAGIC   Customer_Old_Office,
# MAGIC   Customer_Other_Fees_CAD,
# MAGIC   Customer_Other_Fees_USD,
# MAGIC   Customer_Rep_ID,
# MAGIC   Customer_Rep,
# MAGIC   Days_Ahead,
# MAGIC   Bounced_Date,
# MAGIC   Cancelled_Date,
# MAGIC   Delivery_Pickup_Charges_Carrier_CAD,
# MAGIC   Delivery_Pickup_Charges_Carrier_USD,
# MAGIC   Delivery_Pickup_Charges_Customer_CAD,
# MAGIC   Delivery_Pickup_Charges_Customer_USD,
# MAGIC   Delivery_Appointment_Date,
# MAGIC   Delivery_EndDate,
# MAGIC   Destination_City,
# MAGIC   Destination_State,
# MAGIC   Destination_Zip,
# MAGIC   DOT_Number,
# MAGIC   Delivery_StartDate,
# MAGIC   Equipment,
# MAGIC   Equipment_Vehicle_Charges_Carrier_CAD,
# MAGIC   Equipment_Vehicle_Charges_Carrier_USD,
# MAGIC   Equipment_Vehicle_Charges_Customer_CAD,
# MAGIC   Equipment_Vehicle_Charges_Customer_USD,
# MAGIC   Expense_CAD,
# MAGIC   Expense_USD,
# MAGIC   Financial_Period_Year,
# MAGIC   GreenScreen_Rate_CAD,
# MAGIC   GreenScreen_Rate_USD,
# MAGIC   Invoice_Amount_CAD,
# MAGIC   Invoice_Amount_USD,
# MAGIC   Invoiced_Date,
# MAGIC   Lawson_ID,
# MAGIC   Load_Currency,
# MAGIC   Load_Flag,
# MAGIC   Load_Lane,
# MAGIC   Load_Status,
# MAGIC   Load_Unload_Charges_Carrier_CAD,
# MAGIC   Load_Unload_Charges_Carrier_USD,
# MAGIC   Load_Unload_Charges_Customer_CAD,
# MAGIC   Load_Unload_Charges_Customer_USD,
# MAGIC   Margin_CAD,
# MAGIC   Margin_USD,
# MAGIC   Market_Buy_Rate_CAD,
# MAGIC   Market_Buy_Rate_USD,
# MAGIC   Market_Destination,
# MAGIC   Market_Lane,
# MAGIC   Market_Origin,
# MAGIC   MC_Number,
# MAGIC   Miles,
# MAGIC   Miscellaneous_Chargers_Carrier_CAD,
# MAGIC   Miscellaneous_Chargers_Carrier_USD,
# MAGIC   Miscellaneous_Chargers_Customers_CAD,
# MAGIC   Miscellaneous_Chargers_Customers_USD,
# MAGIC   Mode,
# MAGIC   On_Time_Delivery,
# MAGIC   On_Time_Pickup,
# MAGIC   Origin_City,
# MAGIC   Origin_State,
# MAGIC   Origin_Zip,
# MAGIC   Permits_Compliance_Charges_Carrier_CAD,
# MAGIC   Permits_Compliance_Charges_Carrier_USD,
# MAGIC   Permits_Compliance_Charges_Customer_CAD,
# MAGIC   Permits_Compliance_Charges_Customer_USD,
# MAGIC   Pickup_Appointment_Date,
# MAGIC   Actual_Pickup_Date,
# MAGIC   Pickup_EndDate,
# MAGIC   Pickup_StartDate,
# MAGIC   PO_Number,
# MAGIC   PreBookStatus,
# MAGIC   Revenue_CAD,
# MAGIC   Revenue_USD,
# MAGIC   Rolled_Date,
# MAGIC   Sales_Rep_ID,
# MAGIC   Sales_Rep,
# MAGIC   Ship_Date,
# MAGIC   Spot_Margin,
# MAGIC   Spot_Revenue,
# MAGIC   Tender_Source_Type,
# MAGIC   Tendered_Date,
# MAGIC   TMS_System,
# MAGIC   Trailer_Number,
# MAGIC   Transit_Routing_Chargers_Carrier_CAD,
# MAGIC   Transit_Routing_Chargers_Carrier_USD,
# MAGIC   Transit_Routing_Chargers_Customer_CAD,
# MAGIC   Transit_Routing_Chargers_Customer_USD,
# MAGIC   Week_Number,
# MAGIC   Hashkey
# MAGIC FROM
# MAGIC
# MAGIC -- Union from silver_aljex
# MAGIC (SELECT
# MAGIC   DW_Load_ID, Load_number, Actual_Delivered_Date, Booked_Date,
# MAGIC   Carrier_Fuel_Surcharge_CAD, Carrier_Fuel_Surcharge_USD,
# MAGIC   Carrier_Linehaul_CAD, Carrier_Linehaul_USD,
# MAGIC   Carrier_Name, Carrier_New_Office, Carrier_Old_Office,
# MAGIC   Carrier_Other_Fees_CAD, Carrier_Other_Fees_USD,
# MAGIC   Carrier_ID, Carrier_Rep_ID, Carrier_Rep, Combined_Load,
# MAGIC   Consignee_Delivery_Address, Consignee_Name, Consignee_Pickup_Address,
# MAGIC   Customer_Fuel_Surcharge_USD, Customer_Fule_Surcharge_CAD,
# MAGIC   Customer_Linehaul_CAD, Customer_Linehaul_USD,
# MAGIC   Customer_ID, Customer_Master, Customer_Name, Customer_New_Office, Customer_Old_Office,
# MAGIC   Customer_Other_Fees_CAD, Customer_Other_Fees_USD,
# MAGIC   Customer_Rep_ID, Customer_Rep, Days_Ahead, Bounced_Date, Cancelled_Date,
# MAGIC   Delivery_Pickup_Charges_Carrier_CAD, Delivery_Pickup_Charges_Carrier_USD,
# MAGIC   Delivery_Pickup_Charges_Customer_CAD, Delivery_Pickup_Charges_Customer_USD,
# MAGIC   Delivery_Appointment_Date, Delivery_EndDate, Destination_City, Destination_State, Destination_Zip,
# MAGIC   DOT_Number, Delivery_StartDate, Equipment,
# MAGIC   Equipment_Vehicle_Charges_Carrier_CAD, Equipment_Vehicle_Charges_Carrier_USD,
# MAGIC   Equipment_Vehicle_Charges_Customer_CAD, Equipment_Vehicle_Charges_Customer_USD,
# MAGIC   Expense_CAD, Expense_USD, Financial_Period_Year,
# MAGIC   GreenScreen_Rate_CAD, GreenScreen_Rate_USD,
# MAGIC   Invoice_Amount_CAD, Invoice_Amount_USD, Invoiced_Date,
# MAGIC   Lawson_ID, Load_Currency, Load_Flag, Load_Lane, Load_Status,
# MAGIC   Load_Unload_Charges_Carrier_CAD, Load_Unload_Charges_Carrier_USD,
# MAGIC   Load_Unload_Charges_Customer_CAD, Load_Unload_Charges_Customer_USD,
# MAGIC   Margin_CAD, Margin_USD, Market_Buy_Rate_CAD, Market_Buy_Rate_USD,
# MAGIC   Market_Destination, Market_Lane, Market_Origin,
# MAGIC   MC_Number, Miles,
# MAGIC   Miscellaneous_Chargers_Carrier_CAD, Miscellaneous_Chargers_Carrier_USD,
# MAGIC   Miscellaneous_Chargers_Customers_CAD, Miscellaneous_Chargers_Customers_USD,
# MAGIC   Mode, On_Time_Delivery, On_Time_Pickup,
# MAGIC   Origin_City, Origin_State, Origin_Zip,
# MAGIC   Permits_Compliance_Charges_Carrier_CAD, Permits_Compliance_Charges_Carrier_USD,
# MAGIC   Permits_Compliance_Charges_Customer_CAD, Permits_Compliance_Charges_Customer_USD,
# MAGIC   Pickup_Appointment_Date, Actual_Pickup_Date, Pickup_EndDate, Pickup_StartDate,
# MAGIC   PO_Number, PreBookStatus, Revenue_CAD, Revenue_USD,
# MAGIC   Rolled_Date, Sales_Rep_ID, Sales_Rep,
# MAGIC   Ship_Date, Spot_Margin, Spot_Revenue,
# MAGIC   Tender_Source_Type, Tendered_Date, TMS_System, Trailer_Number,
# MAGIC   Transit_Routing_Chargers_Carrier_CAD, Transit_Routing_Chargers_Carrier_USD,
# MAGIC   Transit_Routing_Chargers_Customer_CAD, Transit_Routing_Chargers_Customer_USD,
# MAGIC   Week_Number, Carrier_Final_Rate_CAD, Carrier_Final_Rate_USD,
# MAGIC   Hashkey, 
# MAGIC   Admin_Fees_Carrier_USD, Admin_Fees_Carrier_CAD,
# MAGIC   Admin_Fees_Customer_USD, Admin_Fees_Customer_CAD,
# MAGIC   Billing_Status, Booking_Type
# MAGIC FROM silver_aljex  WHERE  Is_Deleted = 0
# MAGIC
# MAGIC UNION ALL
# MAGIC
# MAGIC -- Union from silver_relay
# MAGIC SELECT
# MAGIC   DW_Load_ID, Load_ID, Actual_Delivered_Date, Booked_Date,
# MAGIC   Carrier_Fuel_Surcharge_CAD, Carrier_Fuel_Surcharge_USD,
# MAGIC   Carrier_Linehaul_CAD, Carrier_Linehaul_USD,
# MAGIC   Carrier_Name, Carrier_New_Office, Carrier_Old_Office,
# MAGIC   Carrier_Other_Fees_CAD, Carrier_Other_Fees_USD,
# MAGIC   Carrier_ID, Carrier_Rep_ID, Carrier_Rep, Combined_Load,
# MAGIC   Consignee_Delivery_Address, Consignee_Name, Consignee_Pickup_Address,
# MAGIC   Customer_Fuel_Surcharge_USD, Customer_Fule_Surcharge_CAD,
# MAGIC   Customer_Linehaul_CAD, Customer_Linehaul_USD,
# MAGIC   Customer_ID, Customer_Master, Customer_Name, Customer_New_Office, Customer_Old_Office,
# MAGIC   Customer_Other_Fees_CAD, Customer_Other_Fees_USD,
# MAGIC   Customer_Rep_ID, Customer_Rep, Days_Ahead, Bounced_Date, Cancelled_Date,
# MAGIC   Delivery_Pickup_Charges_Carrier_CAD, Delivery_Pickup_Charges_Carrier_USD,
# MAGIC   Delivery_Pickup_Charges_Customer_CAD, Delivery_Pickup_Charges_Customer_USD,
# MAGIC   Delivery_Appointment_Date, Delivery_EndDate, Destination_City, Destination_State, Destination_Zip,
# MAGIC   DOT_Number, Delivery_StartDate, Equipment,
# MAGIC   Equipment_Vehicle_Charges_Carrier_CAD, Equipment_Vehicle_Charges_Carrier_USD,
# MAGIC   Equipment_Vehicle_Charges_Customer_CAD, Equipment_Vehicle_Charges_Customer_USD,
# MAGIC   Expense_CAD, Expense_USD, Financial_Period_Year,
# MAGIC   GreenScreen_Rate_CAD, GreenScreen_Rate_USD,
# MAGIC   Invoice_Amount_CAD, Invoice_Amount_USD, Invoiced_Date,
# MAGIC   Lawson_ID, Load_Currency, Load_Flag, Load_Lane, Load_Status,
# MAGIC   Load_Unload_Charges_Carrier_CAD, Load_Unload_Charges_Carrier_USD,
# MAGIC   Load_Unload_Charges_Customer_CAD, Load_Unload_Charges_Customer_USD,
# MAGIC   Margin_CAD, Margin_USD, Market_Buy_Rate_CAD, Market_Buy_Rate_USD,
# MAGIC   Market_Destination, Market_Lane, Market_Origin,
# MAGIC   MC_Number, Miles,
# MAGIC   Miscellaneous_Chargers_Carrier_CAD, Miscellaneous_Chargers_Carrier_USD,
# MAGIC   Miscellaneous_Chargers_Customers_CAD, Miscellaneous_Chargers_Customers_USD,
# MAGIC   Mode, On_Time_Delivery, On_Time_Pickup,
# MAGIC   Origin_City, Origin_State, Origin_Zip,
# MAGIC   Permits_Compliance_Charges_Carrier_CAD, Permits_Compliance_Charges_Carrier_USD,
# MAGIC   Permits_Compliance_Charges_Customer_CAD, Permits_Compliance_Charges_Customer_USD,
# MAGIC   Pickup_Appointment_Date, Actual_Pickup_Date, Pickup_EndDate, Pickup_StartDate,
# MAGIC   PO_Number, PreBookStatus, Revenue_CAD, Revenue_USD,
# MAGIC   Rolled_Date, Sales_Rep_ID, Sales_Rep,
# MAGIC   Ship_Date, Spot_Margin, Spot_Revenue,
# MAGIC   Tender_Source_Type, Tendered_Date, TMS_System, Trailer_Number,
# MAGIC   Transit_Routing_Chargers_Carrier_CAD, Transit_Routing_Chargers_Carrier_USD,
# MAGIC   Transit_Routing_Chargers_Customer_CAD, Transit_Routing_Chargers_Customer_USD,
# MAGIC   Week_Number, Carrier_Final_Rate_CAD, Carrier_Final_Rate_USD,
# MAGIC   Hashkey, 
# MAGIC   Admin_Fees_Carrier_USD, Admin_Fees_Carrier_CAD,
# MAGIC   Admin_Fees_Customer_USD, Admin_Fees_Customer_CAD,
# MAGIC   Billing_Status, Booking_Type
# MAGIC FROM silver_relay  WHERE Is_Deleted = 0
# MAGIC
# MAGIC UNION ALL
# MAGIC
# MAGIC -- Union from silver_transfix
# MAGIC SELECT
# MAGIC   DW_Load_ID, Load_Number, Actual_Delivered_Date, Booked_Date,
# MAGIC   Carrier_Fuel_Surcharge_CAD, Carrier_Fuel_Surcharge_USD,
# MAGIC   Carrier_Linehaul_CAD AS Carrier_Linehaul_CAD, -- align spelling
# MAGIC   Carrier_Linehaul_USD AS Carrier_Linehaul_USD,
# MAGIC   Carrier_Name, NULL AS Carrier_New_Office, Carrier_Office AS Carrier_Old_Office,
# MAGIC   Carrier_Other_Fees_CAD, Carrier_Other_Fees_USD,
# MAGIC   NULL AS Carrier_ID, NULL AS Carrier_Rep_ID, NULL AS Carrier_Rep, NULL AS Combined_Load,
# MAGIC   NULL AS Consignee_Delivery_Address, NULL AS Consignee_Name, NULL AS Consignee_Pickup_Address,
# MAGIC   Customer_Fuel_Surcharge_USD, Customer_Fule_Surcharge_CAD,
# MAGIC   Customer_Linehaul_CAD AS Customer_Linehaul_CAD, Customer_Linehaul_USD AS Customer_Linehaul_USD,
# MAGIC   NULL AS Customer_ID, Customer_Master, Customer_Name,
# MAGIC   NULL AS Customer_New_Office, Customer_Office AS Customer_Old_Office,
# MAGIC   Customer_Other_Fees_CAD, Customer_Other_Fees_USD,
# MAGIC   NULL AS Customer_Rep_ID, NULL AS Customer_Rep,
# MAGIC   Days_Ahead, Bounced_Date, Cancelled_Date,
# MAGIC   NULL AS Delivery_Pickup_Charges_Carrier_CAD, NULL AS Delivery_Pickup_Charges_Carrier_USD,
# MAGIC   NULL AS Delivery_Pickup_Charges_Customer_CAD, NULL AS Delivery_Pickup_Charges_Customer_USD,
# MAGIC   Delivery_Appointment_Date, Delivery_EndDate, Destination_City, Destination_State, Destination_Zip,
# MAGIC   DOT_Number, Delivery_StartDate, Equipment,
# MAGIC   NULL AS Equipment_Vehicle_Charges_Carrier_CAD, NULL AS Equipment_Vehicle_Charges_Carrier_USD,
# MAGIC   NULL AS Equipment_Vehicle_Charges_Customer_CAD, NULL AS Equipment_Vehicle_Charges_Customer_USD,
# MAGIC   Expense_CAD, Expense_USD, Financial_Period_Year,
# MAGIC   NULL AS GreenScreen_Rate_CAD, NULL AS GreenScreen_Rate_USD,
# MAGIC   NULL AS Invoice_Amount_CAD, NULL AS Invoice_Amount_USD,
# MAGIC   Invoiced_Date, NULL AS Lawson_ID, Load_Currency, Load_Flag, NULL AS Load_Lane, Load_Status,
# MAGIC   NULL AS Load_Unload_Charges_Carrier_CAD, NULL AS Load_Unload_Charges_Carrier_USD,
# MAGIC   NULL AS Load_Unload_Charges_Customer_CAD, NULL AS Load_Unload_Charges_Customer_USD,
# MAGIC   Margin_CAD, Margin_USD,
# MAGIC   NULL AS Market_Buy_Rate_CAD, NULL AS Market_Buy_Rate_USD,
# MAGIC   NULL AS Market_Destination, NULL AS Market_Lane, NULL AS Market_Origin,
# MAGIC   NULL AS MC_Number, Miles,
# MAGIC   NULL AS Miscellaneous_Chargers_Carrier_CAD, NULL AS Miscellaneous_Chargers_Carrier_USD,
# MAGIC   NULL AS Miscellaneous_Chargers_Customers_CAD, NULL AS Miscellaneous_Chargers_Customers_USD,
# MAGIC   Mode, On_Time_Delivery, On_Time_Pickup, Origin_City, Origin_State, Origin_Zip,
# MAGIC   NULL AS Permits_Compliance_Charges_Carrier_CAD, NULL AS Permits_Compliance_Charges_Carrier_USD,
# MAGIC   NULL AS Permits_Compliance_Charges_Customer_CAD, NULL AS Permits_Compliance_Charges_Customer_USD,
# MAGIC   Pickup_Appointment_Date, Actual_Pickup_Date, Pickup_EndDate, Pickup_StartDate,
# MAGIC   NULL AS PO_Number, PreBookStatus, Revenue_CAD, Revenue_USD,
# MAGIC   Rolled_Date, NULL AS Sales_Rep_ID, NULL AS Sales_Rep,
# MAGIC   Ship_Date, NULL AS Spot_Margin, NULL AS Spot_Revenue,
# MAGIC   NULL AS Tender_Source_Type, Tendered_Date, TMS_System,
# MAGIC   NULL AS Trailer_Number,
# MAGIC   NULL AS Transit_Routing_Chargers_Carrier_CAD, NULL AS Transit_Routing_Chargers_Carrier_USD,
# MAGIC   NULL AS Transit_Routing_Chargers_Customer_CAD, NULL AS Transit_Routing_Chargers_Customer_USD,
# MAGIC   Week_Number, Carrier_Final_Rate_CAD, Carrier_Final_Rate_USD, Hashkey,
# MAGIC   NULL AS Admin_Fees_Carrier_USD, NULL AS Admin_Fees_Carrier_CAD,
# MAGIC   NULL AS Admin_Fees_Customer_USD, NULL AS Admin_Fees_Customer_CAD,
# MAGIC   NULL AS Billing_Status, NULL AS Booking_Type
# MAGIC FROM silver_transfix WHERE Is_Deleted = 0)

# COMMAND ----------

# MAGIC %md
# MAGIC #### DDL 
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE OR REPLACE TABLE Gold.Fact_Loads_By_Billing (
# MAGIC     DW_Load_ID VARCHAR(255) NOT NULL PRIMARY KEY,
# MAGIC     Load_Number BIGINT,
# MAGIC     Admin_Fees_Carrier_USD DECIMAL(10,2),
# MAGIC     Admin_Fees_Carrier_CAD DECIMAL(10,2),
# MAGIC     Admin_Fees_Customer_USD DECIMAL(10,2),
# MAGIC     Admin_Fees_Customer_CAD DECIMAL(10,2),
# MAGIC     Billing_Status VARCHAR(255),
# MAGIC     Actual_Delivered_Date TIMESTAMP_NTZ,
# MAGIC     Booking_Type VARCHAR(255),
# MAGIC     Booked_Date TIMESTAMP_NTZ,
# MAGIC     Carrier_Fuel_Surcharge_CAD DECIMAL(10,2),
# MAGIC     Carrier_Fuel_Surcharge_USD DECIMAL(10,2),
# MAGIC     Carrier_Linehaul_CAD DECIMAL(10,2),
# MAGIC     Carrier_Linehaul_USD DECIMAL(10,2),
# MAGIC     Carrier_ID VARCHAR(255),
# MAGIC     Carrier_Name VARCHAR(255),
# MAGIC     Carrier_New_Office VARCHAR(255),
# MAGIC     Carrier_Old_Office VARCHAR(255),
# MAGIC     Carrier_Other_Fees_CAD DECIMAL(10,2),
# MAGIC     Carrier_Other_Fees_USD DECIMAL(10,2),
# MAGIC     Carrier_Rep_ID VARCHAR(255),
# MAGIC     Carrier_Rep VARCHAR(255),
# MAGIC     Combined_Load VARCHAR(255),
# MAGIC     Consignee_Delivery_Address VARCHAR(255),
# MAGIC     Consignee_Name VARCHAR(255),
# MAGIC     Consignee_Pickup_Address VARCHAR(255),
# MAGIC     Customer_Fuel_Surcharge_USD DECIMAL(10,2),
# MAGIC     Customer_Fule_Surcharge_CAD DECIMAL(10,2),
# MAGIC     Customer_Linehaul_CAD DECIMAL(10,2),
# MAGIC     Customer_Linehaul_USD DECIMAL(10,2),
# MAGIC     Customer_Master VARCHAR(255),
# MAGIC     Customer_ID VARCHAR(255),
# MAGIC     Customer_Name VARCHAR(255),
# MAGIC     Customer_New_Office VARCHAR(255),
# MAGIC     Customer_Old_Office VARCHAR(255),
# MAGIC     Customer_Other_Fees_CAD DECIMAL(10,2),
# MAGIC     Customer_Other_Fees_USD DECIMAL(10,2),
# MAGIC     Customer_Rep_ID VARCHAR(255),
# MAGIC     Customer_Rep VARCHAR(255),
# MAGIC     Days_Ahead VARCHAR(255),
# MAGIC     Bounced_Date TIMESTAMP_NTZ,
# MAGIC     Cancelled_Date TIMESTAMP_NTZ,
# MAGIC     Delivery_Pickup_Charges_Carrier_CAD DECIMAL(10,2),
# MAGIC     Delivery_Pickup_Charges_Carrier_USD DECIMAL(10,2),
# MAGIC     Delivery_Pickup_Charges_Customer_CAD DECIMAL(10,2),
# MAGIC     Delivery_Pickup_Charges_Customer_USD DECIMAL(10,2),
# MAGIC     Delivery_Appointment_Date TIMESTAMP_NTZ,
# MAGIC     Delivery_EndDate TIMESTAMP_NTZ,
# MAGIC     Destination_City VARCHAR(255),
# MAGIC     Destination_State VARCHAR(255),
# MAGIC     Destination_Zip VARCHAR(255),
# MAGIC     DOT_Number VARCHAR(255),
# MAGIC     Delivery_StartDate TIMESTAMP_NTZ,
# MAGIC     Equipment VARCHAR(255),
# MAGIC     Equipment_Vehicle_Charges_Carrier_CAD DECIMAL(10,2),
# MAGIC     Equipment_Vehicle_Charges_Carrier_USD DECIMAL(10,2),
# MAGIC     Equipment_Vehicle_Charges_Customer_CAD DECIMAL(10,2),
# MAGIC     Equipment_Vehicle_Charges_Customer_USD DECIMAL(10,2),
# MAGIC     Expense_CAD DECIMAL(10,2),
# MAGIC     Expense_USD DECIMAL(10,2),
# MAGIC     Financial_Period_Year VARCHAR(255),
# MAGIC     GreenScreen_Rate_CAD DECIMAL(10,2),
# MAGIC     GreenScreen_Rate_USD DECIMAL(10,2),
# MAGIC     Invoice_Amount_CAD DECIMAL(10,2),
# MAGIC     Invoice_Amount_USD DECIMAL(10,2),
# MAGIC     Invoiced_Date TIMESTAMP_NTZ,
# MAGIC     Lawson_ID VARCHAR(50),
# MAGIC     Load_Currency VARCHAR(255),
# MAGIC     Load_Flag VARCHAR(255),
# MAGIC     Load_Lane VARCHAR(255),
# MAGIC     Load_Status VARCHAR(255),
# MAGIC     Load_Unload_Charges_Carrier_CAD DECIMAL(10,2),
# MAGIC     Load_Unload_Charges_Carrier_USD DECIMAL(10,2),
# MAGIC     Load_Unload_Charges_Customer_CAD DECIMAL(10,2),
# MAGIC     Load_Unload_Charges_Customer_USD DECIMAL(10,2),
# MAGIC     Margin_CAD DECIMAL(10,2),
# MAGIC     Margin_USD DECIMAL(10,2),
# MAGIC     Market_Buy_Rate_CAD DECIMAL(10,2),
# MAGIC     Market_Buy_Rate_USD DECIMAL(10,2),
# MAGIC     Market_Destination VARCHAR(255),
# MAGIC     Market_Lane VARCHAR(255),
# MAGIC     Market_Origin VARCHAR(255),
# MAGIC     MC_Number VARCHAR(255),
# MAGIC     Miles VARCHAR(255),
# MAGIC     Miscellaneous_Chargers_Carrier_CAD DECIMAL(10,2),
# MAGIC     Miscellaneous_Chargers_Carrier_USD DECIMAL(10,2),
# MAGIC     Miscellaneous_Chargers_Customers_CAD DECIMAL(10,2),
# MAGIC     Miscellaneous_Chargers_Customers_USD DECIMAL(10,2),
# MAGIC     Mode VARCHAR(255),
# MAGIC     On_Time_Delivery VARCHAR(255),
# MAGIC     On_Time_Pickup VARCHAR(255),
# MAGIC     Origin_City VARCHAR(255),
# MAGIC     Origin_State VARCHAR(255),
# MAGIC     Origin_Zip VARCHAR(255),
# MAGIC     Permits_Compliance_Charges_Carrier_CAD DECIMAL(10,2),
# MAGIC     Permits_Compliance_Charges_Carrier_USD DECIMAL(10,2),
# MAGIC     Permits_Compliance_Charges_Customer_CAD DECIMAL(10,2),
# MAGIC     Permits_Compliance_Charges_Customer_USD DECIMAL(10,2),
# MAGIC     Pickup_Appointment_Date TIMESTAMP_NTZ,
# MAGIC     Actual_Pickup_Date TIMESTAMP_NTZ,
# MAGIC     Pickup_EndDate TIMESTAMP_NTZ,
# MAGIC     Pickup_StartDate TIMESTAMP_NTZ,
# MAGIC     PO_Number VARCHAR(255),
# MAGIC     PreBookStatus VARCHAR(255),
# MAGIC     Revenue_CAD DECIMAL(10,2),
# MAGIC     Revenue_USD DECIMAL(10,2),
# MAGIC     Rolled_Date TIMESTAMP_NTZ,
# MAGIC     Sales_Rep_ID VARCHAR(255),
# MAGIC     Sales_Rep VARCHAR(255),
# MAGIC     Ship_Date TIMESTAMP_NTZ,
# MAGIC     Spot_Margin VARCHAR(255),
# MAGIC     Spot_Revenue VARCHAR(255),
# MAGIC     Tender_Source_Type VARCHAR(255),
# MAGIC     Tendered_Date TIMESTAMP_NTZ,
# MAGIC     TMS_System VARCHAR(50),
# MAGIC     Trailer_Number VARCHAR(255),
# MAGIC     Transit_Routing_Chargers_Carrier_CAD DECIMAL(10,2),
# MAGIC     Transit_Routing_Chargers_Carrier_USD DECIMAL(10,2),
# MAGIC     Transit_Routing_Chargers_Customer_CAD DECIMAL(10,2),
# MAGIC     Transit_Routing_Chargers_Customer_USD DECIMAL(10,2),
# MAGIC     Week_Number VARCHAR(10),
# MAGIC     Hashkey VARCHAR(255) NOT NULL,
# MAGIC     Created_Date TIMESTAMP_NTZ NOT NULL,
# MAGIC     Created_By VARCHAR(50) NOT NULL,
# MAGIC     Last_Modified_Date TIMESTAMP_NTZ NOT NULL,
# MAGIC     Last_Modified_By VARCHAR(50) NOT NULL,
# MAGIC     Is_Deleted SMALLINT NOT NULL
# MAGIC );
# MAGIC