-- Databricks notebook source
-- MAGIC %md
-- MAGIC #### Bronze

-- COMMAND ----------

CREATE OR REPLACE TABLE Bronze.NFI_Awards (
    DW_Award_ID BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    Hashkey STRING NOT NULL,
    RFP_Name VARCHAR(255),
    Customer_Master VARCHAR(255),
    Customer_Slug VARCHAR(255),
    SAM_Name VARCHAR(255),
    Lane_Description VARCHAR(255),
    Origin_Facility VARCHAR(255),
    Origin_Address VARCHAR(255),
    Origin_City VARCHAR(255),
    Origin_State VARCHAR(255),
    Origin_Zip VARCHAR(255),
    Origin_Country VARCHAR(255),
    Destination_Facility VARCHAR(255),
    Destination_Address VARCHAR(255),
    Destination_City VARCHAR(255),
    Destination_State VARCHAR(255),
    Destination_Zip VARCHAR(255),
    Destination_Country VARCHAR(255),
    Origin_Live_Drop VARCHAR(255),
    Destination_Live_Drop VARCHAR(255),
    Equipment_Type VARCHAR(255),
    Estimated_Volume INT,
    Estimated_Miles FLOAT,
    Linehaul FLOAT,
    RPM FLOAT,
    Flat_Rate FLOAT,
    Min_Rate FLOAT,
    Max_Rate FLOAT,
    Validation_Criteria VARCHAR(255),
    Award_Type VARCHAR(255),
    Award_Notes VARCHAR(255),
    Periodic_Start_Date DATE,
    Periodic_End_Date DATE,
    Shipper_Recurrence VARCHAR(255),
    Updated_By VARCHAR(255),
    Updated_Date DATE,
    Contract_Type VARCHAR(255),
    Expected_Margin VARCHAR(255),
    Status CHAR(1),
    Sourcesystem_Name VARCHAR(255) NOT NULL,
    Sourcesystem_ID SMALLINT NOT NULL,
    Created_Date TIMESTAMP_NTZ NOT NULL,
    Created_By VARCHAR(255) NOT NULL,
    Last_Modified_Date TIMESTAMP_NTZ NOT NULL,
    Last_Modified_By VARCHAR(255) NOT NULL,
    CONSTRAINT NFI_Awards_Pkey PRIMARY KEY (DW_Award_ID)
);

-- COMMAND ----------

-- MAGIC %md
-- MAGIC #### Silver

-- COMMAND ----------

CREATE OR REPLACE TABLE Silver.Silver_NFI_Awards_Filtered (
    DW_Award_ID BIGINT NOT NULL,
    Hashkey STRING NOT NULL,
    RFP_Name VARCHAR(255),
    Customer_Master VARCHAR(255),
    Customer_Slug VARCHAR(255),
    SAM_Name VARCHAR(255),
    Origin VARCHAR(255),
    Origin_Country VARCHAR(255),
    Destination VARCHAR(255),
    Destination_Country VARCHAR(255),
    Equipment_Type VARCHAR(255),
    Estimated_Volume INT,
    Estimated_Miles FLOAT,
    Linehaul FLOAT,
    RPM FLOAT,
    Flat_Rate FLOAT,
    Min_Rate FLOAT,
    Max_Rate FLOAT,
    Validation_Criteria VARCHAR(255),
    Award_Type VARCHAR(255),
    Award_Notes VARCHAR(255),
    Periodic_Start_Date DATE,
    Periodic_End_Date DATE,
    Shipper_Recurrence VARCHAR(255),
    Updated_By VARCHAR(255),
    Updated_Date DATE,
    Contract_Type VARCHAR(255),
    Expected_Margin VARCHAR(255),
    Mergekey STRING NOT NULL,
    Is_Deleted SMALLINT NOT NULL, 
    Sourcesystem_Name VARCHAR(255) NOT NULL,
    Sourcesystem_ID SMALLINT NOT NULL,
    Created_Date TIMESTAMP_NTZ NOT NULL,
    Created_By VARCHAR(255) NOT NULL,
    Last_Modified_Date TIMESTAMP_NTZ NOT NULL,
    Last_Modified_By VARCHAR(255) NOT NULL,
    CONSTRAINT NFI_Awards_Filtered_PK PRIMARY KEY (DW_Award_ID)
    );

-- COMMAND ----------

CREATE OR REPLACE TABLE silver.Silver_NFI_Awards_Validated (
    DW_Validated_Award_ID BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    RFP_Name VARCHAR(255),
    Customer_Slug VARCHAR(255),
    Customer_Master VARCHAR(255),
    SAM_Name VARCHAR(255),
    Origin VARCHAR(255),
    Origin_Country VARCHAR(255),
    Destination VARCHAR(255),
    Destination_Country VARCHAR(255),
    Equipment_Type VARCHAR(255),
    Estimated_Volume INT,
    Estimated_Miles FLOAT,
    Linehaul FLOAT,
    RPM FLOAT,
    Flat_Rate FLOAT,
    Min_Rate FLOAT,
    Max_Rate FLOAT,
    Validation_Criteria VARCHAR(255),
    Award_Type VARCHAR(255),
    Award_Notes VARCHAR(255),
    Periodic_Start_Date DATE,
    Periodic_End_Date DATE,
    Shipper_Recurrence VARCHAR(255),
    Updated_By VARCHAR(255),
    Updated_Date DATE,
    Contract_Type VARCHAR(255),
    Expected_Margin VARCHAR(255),
    Mergekey STRING NOT NULL,
    Hashkey STRING NOT NULL,
    Sourcesystem_Name VARCHAR(255) NOT NULL,
    Sourcesystem_ID SMALLINT NOT NULL,
    Created_Date TIMESTAMP_NTZ NOT NULL,
    Created_By VARCHAR(255) NOT NULL,
    Last_Modified_Date TIMESTAMP_NTZ NOT NULL,
    Last_Modified_By VARCHAR(255) NOT NULL,
    Is_Deleted SMALLINT NOT NULL,
    CONSTRAINT Silver_NFI_Awards_Validated_Pk PRIMARY KEY (DW_Validated_Award_ID)
);

-- COMMAND ----------

CREATE OR REPLACE TABLE Silver.Silver_NFI_Awards_Exceptions (
    DW_Exception_ID BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    DW_Award_ID BIGINT NOT NULL,
    RFP_Name VARCHAR(255),
    Customer_Slug VARCHAR(255),
    Customer_Master VARCHAR(255),
    SAM_Name VARCHAR(255),
    Origin VARCHAR(255),
    Origin_Country VARCHAR(255),
    Destination VARCHAR(255),
    Destination_Country VARCHAR(255),
    Equipment_Type VARCHAR(255),
    Estimated_Volume INT,
    Estimated_Miles FLOAT,
    Linehaul FLOAT,
    RPM FLOAT,
    Flat_Rate FLOAT,
    Min_Rate FLOAT,
    Max_Rate FLOAT,
    Validation_Criteria VARCHAR(255),
    Award_Type VARCHAR(255),
    Award_Notes VARCHAR(255),
    Periodic_Start_Date DATE,
    Periodic_End_Date DATE,
    Shipper_Recurrence VARCHAR(255),
    Updated_By VARCHAR(255),
    Updated_Date DATE,
    Exception_Type VARCHAR(255),
    Contract_Type VARCHAR(255),
    Expected_Margin VARCHAR(255),
    Hashkey STRING NOT NULL,
    Sourcesystem_Name VARCHAR(255) NOT NULL,
    Sourcesystem_ID SMALLINT NOT NULL,
    Created_Date TIMESTAMP_NTZ NOT NULL,
    Created_By VARCHAR(255) NOT NULL,
    Last_Modified_Date TIMESTAMP_NTZ NOT NULL,
    Last_Modified_By VARCHAR(255) NOT NULL,
    Is_Deleted SMALLINT NOT NULL,
    CONSTRAINT Silver_NFI_Awards_Exception_PK PRIMARY KEY (DW_Exception_ID),
    CONSTRAINT Silver_NFI_Awards_Exception_FK FOREIGN KEY (DW_Award_ID) REFERENCES Silver.Silver_NFI_Awards_Filtered (DW_Award_ID)
);

-- COMMAND ----------

CREATE OR REPLACE TABLE Silver.Silver_NFI_Awards_Time_Table (
    DW_Award_Time_Table_ID BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    DW_Validated_Award_ID BIGINT NOT NULL,
    RFP_Name VARCHAR(255),
    Customer_Slug VARCHAR(255),
    Customer_Master VARCHAR(255),
    SAM_Name VARCHAR(255),
    Origin VARCHAR(255),
    Origin_Country VARCHAR(255),
    Destination VARCHAR(255),
    Destination_Country VARCHAR(255),
    Equipment_Type VARCHAR(255),
    Estimated_Volume INT,
    Estimated_Miles FLOAT,
    Linehaul FLOAT,
    RPM FLOAT,
    Flat_Rate FLOAT,
    Min_Rate FLOAT,
    Max_Rate FLOAT,
    Period_Count INT,
    Periodical_Volume FLOAT,
    Periodical_Revenue FLOAT,
    Validation_Criteria VARCHAR(255),
    Award_Type VARCHAR(255),
    Award_Notes VARCHAR(255),
    Periodic_Start_Date DATE,
    Periodic_End_Date DATE,
    Shipper_Recurrence VARCHAR(255),
    Updated_By VARCHAR(255),
    Updated_Date DATE,
    Period_Year VARCHAR(10),
    Start_Month SMALLINT,
    Start_Year SMALLINT,
    Start_Period_Year VARCHAR(10),
    End_Month SMALLINT,
    End_Year SMALLINT,
    End_Period_Year VARCHAR(10),
    Month SMALLINT,
    Year SMALLINT,
    Contract_Type VARCHAR(255),
    Expected_Margin VARCHAR(255),
    Awardkey STRING,
    Agingkey STRING,
    Mergekey STRING NOT NULL,
    Hashkey STRING NOT NULL,
    Sourcesystem_Name VARCHAR(255) NOT NULL,
    Sourcesystem_ID SMALLINT NOT NULL,
    Created_Date TIMESTAMP_NTZ NOT NULL,
    Created_By VARCHAR(255) NOT NULL,
    Last_Modified_Date TIMESTAMP_NTZ NOT NULL,
    Last_Modified_By VARCHAR(255) NOT NULL,
    Is_Deleted SMALLINT NOT NULL,
    CONSTRAINT Silver_NFI_Awards_Time_Table_PK PRIMARY KEY (DW_Award_Time_Table_ID),
    CONSTRAINT Silver_NFI_Awards_Time_Table_FK FOREIGN KEY (DW_Validated_Award_ID) REFERENCES Silver.Silver_NFI_Awards_Validated(DW_Validated_Award_ID)
);

-- COMMAND ----------

CREATE OR REPLACE TABLE Silver.Silver_NFI_Awards_Zips (
    DW_Awards_Zips_ID BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    DW_Validated_Award_ID BIGINT NOT NULL,
    RFP_Name VARCHAR(255),
    Customer_Slug VARCHAR(255),
    Customer_Master VARCHAR(255),
    SAM_Name VARCHAR(255),
    Origin VARCHAR(255),
    Origin_Country VARCHAR(255),
    Destination VARCHAR(255),
    Destination_Country VARCHAR(255),
    Equipment_Type VARCHAR(255),
    Estimated_Volume INT,
    Estimated_Miles FLOAT,
    Linehaul FLOAT,
    RPM FLOAT,
    Flat_Rate FLOAT,
    Min_Rate FLOAT,
    Max_Rate FLOAT,
    Validation_Criteria VARCHAR(255),
    Award_Type VARCHAR(255),
    Award_Notes VARCHAR(255),
    Periodic_Start_Date DATE,
    Periodic_End_Date DATE,
    Shipper_Recurrence VARCHAR(255),
    Updated_By VARCHAR(255),
    Updated_Date DATE,
    Expanded_Origin_Zips VARCHAR(255),
    Expanded_Origin_Cities VARCHAR(255),
    Expanded_Origin_States VARCHAR(255),
    Expanded_Origin_Countries VARCHAR(255),
    Expanded_Destination_Zips VARCHAR(255),
    Expanded_Destination_Cities VARCHAR(255),
    Expanded_Destination_States VARCHAR(255),
    Expanded_Destination_Countries VARCHAR(255),
    Contract_Type VARCHAR(255),
    Expected_Margin VARCHAR(255),
    Mergekey STRING NOT NULL,
    Hashkey STRING NOT NULL,
    Sourcesystem_Name VARCHAR(255) NOT NULL,
    Sourcesystem_ID SMALLINT NOT NULL,
    Created_Date TIMESTAMP_NTZ NOT NULL,
    Created_By VARCHAR(255) NOT NULL,
    Last_Modified_Date TIMESTAMP_NTZ NOT NULL,
    Last_Modified_By VARCHAR(255) NOT NULL,
    Is_Deleted SMALLINT NOT NULL,
    CONSTRAINT Silver_NFI_Awards_Zips_PK PRIMARY KEY (DW_Awards_Zips_ID),
    CONSTRAINT Silver_NFI_Awards_Zips_FK FOREIGN KEY (DW_Validated_Award_ID) REFERENCES Silver.Silver_NFI_Awards_Validated(DW_Validated_Award_ID)
);

-- COMMAND ----------

-- MAGIC %md #### Gold

-- COMMAND ----------

CREATE OR REPLACE TABLE Gold.Fact_Awards_Consolidated (
    DW_Awards_Consolidated_ID BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    DW_Validated_Award_ID BIGINT NOT NULL,
    RFP_Name VARCHAR(255),
    Customer_Slug VARCHAR(255),
    Customer_Master VARCHAR(255),
    SAM_Name VARCHAR(255),
    Origin VARCHAR(255),
    Origin_Country VARCHAR(255),
    Destination VARCHAR(255),
    Destination_Country VARCHAR(255),
    Equipment_Type VARCHAR(255),
    Estimated_Volume INT,
    Estimated_Miles FLOAT,
    Linehaul FLOAT,
    RPM FLOAT,
    Flat_Rate FLOAT,
    Min_Rate FLOAT,
    Max_Rate FLOAT,
    Period_Count INT,
    Periodical_Volume FLOAT,
    Periodical_Revenue FLOAT,
    Expanded_Origin_Zips VARCHAR(255),
    Expanded_Origin_Cities VARCHAR(255),
    Expanded_Origin_States VARCHAR(255),
    Expanded_Origin_Countries VARCHAR(255),
    Expanded_Destination_Zips VARCHAR(255),
    Expanded_Destination_Cities VARCHAR(255),
    Expanded_Destination_States VARCHAR(255),
    Expanded_Destination_Countries VARCHAR(255),
    Validation_Criteria VARCHAR(255),
    Award_Type VARCHAR(255),
    Award_Notes VARCHAR(255),
    Periodic_Start_Date DATE,
    Periodic_End_Date DATE,
    Shipper_Recurrence VARCHAR(255),
    Updated_By VARCHAR(255),
    Updated_Date DATE,
    Period_Year VARCHAR(10),
    Start_Month SMALLINT,
    Start_Year SMALLINT,
    Start_Period_Year VARCHAR(10),
    End_Month SMALLINT,
    End_Year SMALLINT,
    End_Period_Year VARCHAR(10),
    Month SMALLINT,
    Year SMALLINT,
    Contract_Type VARCHAR(255),
    Expected_Margin VARCHAR(255),
    Awardkey STRING,
    Agingkey STRING,
    Mergekey STRING NOT NULL,
    Hashkey STRING NOT NULL,
    Sourcesystem_Name VARCHAR(255) NOT NULL,
    Sourcesystem_ID SMALLINT NOT NULL,
    Created_Date TIMESTAMP_NTZ NOT NULL,
    Created_By VARCHAR(255) NOT NULL,
    Last_Modified_Date TIMESTAMP_NTZ NOT NULL,
    Last_Modified_By VARCHAR(255) NOT NULL,
    Is_Deleted SMALLINT NOT NULL,
    CONSTRAINT NFI_Awards_Consolidated_PK PRIMARY KEY (DW_Awards_Consolidated_ID),
    CONSTRAINT NFI_Awards_Consolidated_FK FOREIGN KEY (DW_Validated_Award_ID) REFERENCES Silver.Silver_NFI_Awards_Validated(DW_Validated_Award_ID)
);

-- COMMAND ----------

CREATE OR REPLACE TABLE Gold.Fact_Awards_Summary (
    DW_Awards_Summary_ID BIGINT GENERATED ALWAYS AS IDENTITY,
    DW_Validated_Award_ID BIGINT,
    Customer_Master VARCHAR(255),
    SAM_Name VARCHAR(255),
    Load_ID DOUBLE,
    RFP_Name VARCHAR(255),
    Validation_Criteria VARCHAR(255),
    Lane VARCHAR(255),
    Origin_State VARCHAR(255),
    Origin_City VARCHAR(255),
    Origin_Zip VARCHAR(255),
    Origin_Country VARCHAR(255),
    Dest_State VARCHAR(255),
    Dest_City VARCHAR(255),
    Dest_Zip VARCHAR(255),
    Destination_Country VARCHAR(255),
    TMS_SourceSystem_Name VARCHAR(255),
    Carrier_Rep VARCHAR(255),
    Customer_Name VARCHAR(255),
    Ship_Date DATE,
    Customer_Office STRING,
    Load_Status STRING,
    Carrier_Office STRING,
    Load_Lane STRING,
    Equipment_Type STRING,
    Mode STRING,
    DOT_Num STRING,
    Carrier_Name STRING,
    Total_Expense DOUBLE,
    Total_Margin DOUBLE,
    Market_Origin VARCHAR(255),
    Market_Dest VARCHAR(255),
    Customer_Rep STRING,
    Delivery_Date DATE,
    Invoice_Date DATE,
    Booking_Type STRING,
    Load_Flag INT,
    Total_Miles INT,
    Sum_Revenue DOUBLE,
    Financial_Period_Number SMALLINT,
    Financial_Year SMALLINT,
    Period_Year VARCHAR(10),
    Award_Type VARCHAR(255),
    Periodical_Volume FLOAT,
    Periodical_Revenue DOUBLE,
    Periodic_Start_Date DATE,
    Periodic_End_Date DATE,
    Is_Awarded VARCHAR(255),
    Criteria_Description VARCHAR(255),
    Awardkey VARCHAR(255),
    Agingkey VARCHAR(255),
    Filled_SAM_Name VARCHAR(255),
    Dim_Customer_Rep STRING,
    Contract_Type VARCHAR(255),
    Mergekey STRING NOT NULL,
    Hashkey STRING NOT NULL,
    Sourcesystem_Name VARCHAR(255) NOT NULL,
    Sourcesystem_ID SMALLINT NOT NULL,
    Created_Date TIMESTAMP_NTZ NOT NULL,
    Created_By VARCHAR(255) NOT NULL,
    Last_Modified_Date TIMESTAMP_NTZ NOT NULL,
    Last_Modified_By VARCHAR(255) NOT NULL,
    Is_Deleted SMALLINT NOT NULL,
    CONSTRAINT Fact_Awards_Summary_PK PRIMARY KEY (DW_Awards_Summary_ID),
    CONSTRAINT Fact_Awards_Summary_FK FOREIGN KEY (DW_Validated_Award_ID) REFERENCES Silver.Silver_NFI_Awards_Validated(DW_Validated_Award_ID)
);

-- COMMAND ----------

