# Databricks notebook source
# MAGIC %md
# MAGIC ## Transfix
# MAGIC * **Description:** To incrementally load the data from Bronze to Silver as delta file
# MAGIC * **Created Date:** 03/07/2025
# MAGIC * **Created By:** Uday
# MAGIC * **Modified Date:** 06/10/2025
# MAGIC * **Modified By:** Uday
# MAGIC * **Changes Made:** Logic Update

# COMMAND ----------

# MAGIC %sql
# MAGIC UPDATE metadata.mastermetadata 
# MAGIC SET PipelineStartTime = current_timestamp()
# MAGIC WHERE TableID = 'SL6'

# COMMAND ----------

# MAGIC %sql
# MAGIC MERGE INTO Silver.Silver_Transfix AS target
# MAGIC USING Silver.vw_silver_transfix AS source
# MAGIC ON target.DW_Load_ID = source.DW_Load_ID
# MAGIC
# MAGIC WHEN MATCHED AND target.HashKey != source.HashKey THEN
# MAGIC   UPDATE SET
# MAGIC     target.Load_Number = source.Load_Number,
# MAGIC     target.Actual_Delivered_Date = source.Actual_Delivered_Date,
# MAGIC     target.Booked_Date = source.Booked_Date,
# MAGIC     target.Carrier_Fuel_Surcharge_CAD = source.Carrier_Fuel_Surcharge_CAD,
# MAGIC     target.Carrier_Fuel_Surcharge_USD = source.Carrier_Fuel_Surcharge_USD,
# MAGIC     target.Carrier_Linehaul_CAD = source.Carrier_Linehaul_CAD,
# MAGIC     target.Carrier_Linehaul_USD = source.Carrier_Linehaul_USD,
# MAGIC     target.Carrier_Name = source.Carrier_Name,
# MAGIC     target.Carrier_Office = source.Carrier_Office,
# MAGIC     target.Carrier_Other_Fees_CAD = source.Carrier_Other_Fees_CAD,
# MAGIC     target.Carrier_Other_Fees_USD = source.Carrier_Other_Fees_USD,
# MAGIC     target.Customer_Fuel_Surcharge_USD = source.Customer_Fuel_Surcharge_USD,
# MAGIC     target.Customer_Fule_Surcharge_CAD = source.Customer_Fule_Surcharge_CAD,
# MAGIC     target.Customer_Linehaul_CAD = source.Customer_Linehaul_CAD,
# MAGIC     target.Customer_Linehaul_USD = source.Customer_Linehaul_USD,
# MAGIC     target.Customer_Master = source.Customer_Master,
# MAGIC     target.Customer_Name = source.Customer_Name,
# MAGIC     target.Customer_Office = source.Customer_Office,
# MAGIC     target.Customer_Other_Fees_CAD = source.Customer_Other_Fees_CAD,
# MAGIC     target.Customer_Other_Fees_USD = source.Customer_Other_Fees_USD,
# MAGIC     target.Days_Ahead = source.Days_Ahead,
# MAGIC     target.Bounced_Date = source.Bounced_Date,
# MAGIC     target.Cancelled_Date = source.Cancelled_Date,
# MAGIC     target.Delivery_Appointment_Date = source.Delivery_Appointment_Date,
# MAGIC     target.Delivery_EndDate = source.Delivery_EndDate,
# MAGIC     target.Destination_City = source.Destination_City,
# MAGIC     target.Destination_State = source.Destination_State,
# MAGIC     target.Destination_Zip = source.Destination_Zip,
# MAGIC     target.DOT_Number = source.DOT_Number,
# MAGIC     target.Delivery_StartDate = source.Delivery_StartDate,
# MAGIC     target.Equipment = source.Equipment,
# MAGIC     target.Expense_CAD = source.Expense_CAD,
# MAGIC     target.Expense_USD = source.Expense_USD,
# MAGIC     target.Financial_Period_Year = source.Financial_Period_Year,
# MAGIC     target.Invoiced_Date = source.Invoiced_Date,
# MAGIC     target.Load_Currency = source.Load_Currency,
# MAGIC     target.Load_Flag = source.Load_Flag,
# MAGIC     target.Load_Status = source.Load_Status,
# MAGIC     target.Margin_CAD = source.Margin_CAD,
# MAGIC     target.Margin_USD = source.Margin_USD,
# MAGIC     target.Miles = source.Miles,
# MAGIC     target.Mode = source.Mode,
# MAGIC     target.On_Time_Delivery = source.On_Time_Delivery,
# MAGIC     target.On_Time_Pickup = source.On_Time_Pickup,
# MAGIC     target.Origin_City = source.Origin_City,
# MAGIC     target.Origin_State = source.Origin_State,
# MAGIC     target.Origin_Zip = source.Origin_Zip,
# MAGIC     target.Pickup_Appointment_Date = source.Pickup_Appointment_Date,
# MAGIC     target.Actual_Pickup_Date = source.Actual_Pickup_Date,
# MAGIC     target.Pickup_EndDate = source.Pickup_EndDate,
# MAGIC     target.Pickup_StartDate = source.Pickup_StartDate,
# MAGIC     target.PreBookStatus = source.PreBookStatus,
# MAGIC     target.Revenue_CAD = source.Revenue_CAD,
# MAGIC     target.Revenue_USD = source.Revenue_USD,
# MAGIC     target.Rolled_Date = source.Rolled_Date,
# MAGIC     target.Ship_Date = source.Ship_Date,
# MAGIC     target.Tendered_Date = source.Tendered_Date,
# MAGIC     target.TMS_System = source.TMS_System,
# MAGIC     target.Week_Number = source.Week_Number,
# MAGIC     target.Carrier_Final_Rate_USD = source.Carrier_Final_Rate_USD,
# MAGIC     target.Carrier_Final_Rate_CAD = source.Carrier_Final_Rate_CAD,
# MAGIC     target.HashKey = source.HashKey,
# MAGIC     target.Last_Modified_Date = current_timestamp(),
# MAGIC     target.Last_Modified_By = 'Databricks',
# MAGIC     target.Is_Deleted = 0
# MAGIC
# MAGIC WHEN NOT MATCHED THEN
# MAGIC   INSERT (
# MAGIC     DW_Load_ID,
# MAGIC     Load_Number,
# MAGIC     Actual_Delivered_Date,
# MAGIC     Booked_Date,
# MAGIC     Carrier_Fuel_Surcharge_CAD,
# MAGIC     Carrier_Fuel_Surcharge_USD,
# MAGIC     Carrier_Linehaul_CAD,
# MAGIC     Carrier_Linehaul_USD,
# MAGIC     Carrier_Name,
# MAGIC     Carrier_Office,
# MAGIC     Carrier_Other_Fees_CAD,
# MAGIC     Carrier_Other_Fees_USD,
# MAGIC     Customer_Fuel_Surcharge_USD,
# MAGIC     Customer_Fule_Surcharge_CAD,
# MAGIC     Customer_Linehaul_CAD,
# MAGIC     Customer_Linehaul_USD,
# MAGIC     Customer_Master,
# MAGIC     Customer_Name,
# MAGIC     Customer_Office,
# MAGIC     Customer_Other_Fees_CAD,
# MAGIC     Customer_Other_Fees_USD,
# MAGIC     Days_Ahead,
# MAGIC     Bounced_Date,
# MAGIC     Cancelled_Date,
# MAGIC     Delivery_Appointment_Date,
# MAGIC     Delivery_EndDate,
# MAGIC     Destination_City,
# MAGIC     Destination_State,
# MAGIC     Destination_Zip,
# MAGIC     DOT_Number,
# MAGIC     Delivery_StartDate,
# MAGIC     Equipment,
# MAGIC     Expense_CAD,
# MAGIC     Expense_USD,
# MAGIC     Financial_Period_Year,
# MAGIC     Invoiced_Date,
# MAGIC     Load_Currency,
# MAGIC     Load_Flag,
# MAGIC     Load_Status,
# MAGIC     Margin_CAD,
# MAGIC     Margin_USD,
# MAGIC     Miles,
# MAGIC     Mode,
# MAGIC     On_Time_Delivery,
# MAGIC     On_Time_Pickup,
# MAGIC     Origin_City,
# MAGIC     Origin_State,
# MAGIC     Origin_Zip,
# MAGIC     Pickup_Appointment_Date,
# MAGIC     Actual_Pickup_Date,
# MAGIC     Pickup_EndDate,
# MAGIC     Pickup_StartDate,
# MAGIC     PreBookStatus,
# MAGIC     Revenue_CAD,
# MAGIC     Revenue_USD,
# MAGIC     Rolled_Date,
# MAGIC     Ship_Date,
# MAGIC     Tendered_Date,
# MAGIC     TMS_System,
# MAGIC     Week_Number,
# MAGIC     Carrier_Final_Rate_USD,
# MAGIC     Carrier_Final_Rate_CAD,
# MAGIC     HashKey,
# MAGIC     Created_Date,
# MAGIC     Created_By,
# MAGIC     Last_Modified_Date,
# MAGIC     Last_Modified_By,
# MAGIC     Is_Deleted
# MAGIC   )
# MAGIC   VALUES (
# MAGIC     source.DW_Load_ID,
# MAGIC     source.Load_Number,
# MAGIC     source.Actual_Delivered_Date,
# MAGIC     source.Booked_Date,
# MAGIC     source.Carrier_Fuel_Surcharge_CAD,
# MAGIC     source.Carrier_Fuel_Surcharge_USD,
# MAGIC     source.Carrier_Linehaul_CAD,
# MAGIC     source.Carrier_Linehaul_USD,
# MAGIC     source.Carrier_Name,
# MAGIC     source.Carrier_Office,
# MAGIC     source.Carrier_Other_Fees_CAD,
# MAGIC     source.Carrier_Other_Fees_USD,
# MAGIC     source.Customer_Fuel_Surcharge_USD,
# MAGIC     source.Customer_Fule_Surcharge_CAD,
# MAGIC     source.Customer_Linehaul_CAD,
# MAGIC     source.Customer_Linehaul_USD,
# MAGIC     source.Customer_Master,
# MAGIC     source.Customer_Name,
# MAGIC     source.Customer_Office,
# MAGIC     source.Customer_Other_Fees_CAD,
# MAGIC     source.Customer_Other_Fees_USD,
# MAGIC     source.Days_Ahead,
# MAGIC     source.Bounced_Date,
# MAGIC     source.Cancelled_Date,
# MAGIC     source.Delivery_Appointment_Date,
# MAGIC     source.Delivery_EndDate,
# MAGIC     source.Destination_City,
# MAGIC     source.Destination_State,
# MAGIC     source.Destination_Zip,
# MAGIC     source.DOT_Number,
# MAGIC     source.Delivery_StartDate,
# MAGIC     source.Equipment,
# MAGIC     source.Expense_CAD,
# MAGIC     source.Expense_USD,
# MAGIC     source.Financial_Period_Year,
# MAGIC     source.Invoiced_Date,
# MAGIC     source.Load_Currency,
# MAGIC     source.Load_Flag,
# MAGIC     source.Load_Status,
# MAGIC     source.Margin_CAD,
# MAGIC     source.Margin_USD,
# MAGIC     source.Miles,
# MAGIC     source.Mode,
# MAGIC     source.On_Time_Delivery,
# MAGIC     source.On_Time_Pickup,
# MAGIC     source.Origin_City,
# MAGIC     source.Origin_State,
# MAGIC     source.Origin_Zip,
# MAGIC     source.Pickup_Appointment_Date,
# MAGIC     source.Actual_Pickup_Date,
# MAGIC     source.Pickup_EndDate,
# MAGIC     source.Pickup_StartDate,
# MAGIC     source.PreBookStatus,
# MAGIC     source.Revenue_CAD,
# MAGIC     source.Revenue_USD,
# MAGIC     source.Rolled_Date,
# MAGIC     source.Ship_Date,
# MAGIC     source.Tendered_Date,
# MAGIC     source.TMS_System,
# MAGIC     source.Week_Number,
# MAGIC     source.Carrier_Final_Rate_USD,
# MAGIC     source.Carrier_Final_Rate_CAD,
# MAGIC     source.HashKey,
# MAGIC     current_timestamp(),         -- Created_Date
# MAGIC     'Databricks',                       -- Created_By
# MAGIC     current_timestamp(),         -- Last_Modified_Date
# MAGIC     'Databricks',                       -- Last_Modified_By
# MAGIC     0                            -- Is_Deleted
# MAGIC   );
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC UPDATE metadata.mastermetadata 
# MAGIC SET PipelineEndTime = current_timestamp(),
# MAGIC LastLoadDateValue = (SELECT MAX(Last_Modified_Date) FROM silver.silver_relay_customer_money WHERE Is_Deleted=0),
# MAGIC PipelineRunStatus = 'Success'
# MAGIC WHERE TableID = 'SL6'