# Databricks notebook source
# MAGIC %md
# MAGIC %md
# MAGIC ## Aljex
# MAGIC * **Description:** To incrementally load the data from Bronze to Silver as delta file
# MAGIC * **Created Date:** 03/07/2025
# MAGIC * **Created By:** Uday
# MAGIC * **Modified Date:** 06/10/2025
# MAGIC * **Modified By:** Uday
# MAGIC * **Changes Made:** Logic Update

# COMMAND ----------

# MAGIC %md
# MAGIC #### Update the Pipeline Start Time

# COMMAND ----------

# MAGIC %sql
# MAGIC UPDATE metadata.mastermetadata 
# MAGIC SET PipelineStartTime = current_timestamp()
# MAGIC WHERE TableID = 'SL2'

# COMMAND ----------

# MAGIC %md
# MAGIC ####Load the data into Target Table

# COMMAND ----------

# MAGIC %sql
# MAGIC MERGE INTO Silver.Silver_Aljex AS target
# MAGIC USING Silver.VW_Silver_Aljex AS source
# MAGIC ON target.DW_Load_ID = source.DW_Load_ID
# MAGIC WHEN MATCHED AND target.Hashkey <> source.Hashkey THEN
# MAGIC   UPDATE SET
# MAGIC     target.Admin_Fees_Carrier_USD = source.Admin_Fees_Carrier_USD,
# MAGIC     target.Admin_Fees_Carrier_CAD = source.Admin_Fees_Carrier_CAD,
# MAGIC     target.Admin_Fees_Customer_USD = source.Admin_Fees_Customer_USD,
# MAGIC     target.Admin_Fees_Customer_CAD = source.Admin_Fees_Customer_CAD,
# MAGIC     target.Billing_Status = source.Billing_Status,
# MAGIC     target.Actual_Delivered_Date = source.Actual_Delivered_Date,
# MAGIC     target.Booking_Type = source.Booking_Type,
# MAGIC     target.Booked_Date = source.Booked_Date,
# MAGIC     target.Carrier_Fuel_Surcharge_CAD = source.Carrier_Fuel_Surcharge_CAD,
# MAGIC     target.Carrier_Fuel_Surcharge_USD = source.Carrier_Fuel_Surcharge_USD,
# MAGIC     target.Carrier_linehaul_CAD = source.Carrier_Linehaul_CAD,
# MAGIC     target.Carrier_linehaul_USD = source.Carrier_Linehaul_USD,
# MAGIC     target.Carrier_Name = source.Carrier_Name,
# MAGIC     target.Carrier_New_Office = source.Carrier_New_Office,
# MAGIC     target.Carrier_Old_Office = source.Carrier_Old_Office,
# MAGIC     target.Carrier_Other_Fees_CAD = source.Carrier_Other_Fees_CAD,
# MAGIC     target.Carrier_Other_Fees_USD = source.Carrier_Other_Fees_USD,
# MAGIC     target.Carrier_ID = source.Carrier_ID,
# MAGIC     target.Carrier_Rep_ID = source.Carrier_Rep_ID,
# MAGIC     target.Carrier_Rep = source.Carrier_Rep,
# MAGIC     target.Combined_Load = source.Combined_Load,
# MAGIC     target.Consignee_Delivery_Address = source.Consignee_Delivery_Address,
# MAGIC     target.Consignee_Name = source.Consignee_Name,
# MAGIC     target.Consignee_Pickup_Address = source.Consignee_Pickup_Address,
# MAGIC     target.Customer_Fuel_Surcharge_USD = source.Customer_Fuel_Surcharge_USD,
# MAGIC     target.Customer_Fule_Surcharge_CAD = source.Customer_Fule_Surcharge_CAD,
# MAGIC     target.Customer_linehaul_CAD = source.Customer_Linehaul_CAD,
# MAGIC     target.Customer_linehaul_USD = source.Customer_Linehaul_USD,
# MAGIC     target.Customer_ID = source.Customer_ID,
# MAGIC     target.Customer_Master = source.Customer_Master,
# MAGIC     target.Customer_Name = source.Customer_Name,
# MAGIC     target.Customer_New_Office = source.Customer_New_Office,
# MAGIC     target.Customer_Old_Office = source.Customer_Old_Office,
# MAGIC     target.Customer_Other_Fees_CAD = source.Customer_Other_Fees_CAD,
# MAGIC     target.Customer_Other_Fees_USD = source.Customer_Other_Fees_USD,
# MAGIC     target.Customer_Rep_ID = source.Customer_Rep_ID,
# MAGIC     target.Customer_Rep = source.Customer_Rep,
# MAGIC     target.Days_Ahead = source.Days_Ahead,
# MAGIC     target.Bounced_Date = source.Bounced_Date,
# MAGIC     target.Cancelled_Date = source.Cancelled_Date,
# MAGIC     target.Delivery_Pickup_Charges_Carrier_CAD = source.Delivery_Pickup_Charges_Carrier_CAD,
# MAGIC     target.Delivery_Pickup_Charges_Carrier_USD = source.Delivery_Pickup_Charges_Carrier_USD,
# MAGIC     target.Delivery_Pickup_Charges_Customer_CAD = source.Delivery_Pickup_Charges_Customer_CAD,
# MAGIC     target.Delivery_Pickup_Charges_Customer_USD = source.Delivery_Pickup_Charges_Customer_USD,
# MAGIC     target.Delivery_Appointment_Date = source.Delivery_Appointment_Date,
# MAGIC     target.Delivery_EndDate = source.Delivery_EndDate,
# MAGIC     target.Destination_City = source.Destination_City,
# MAGIC     target.Destination_State = source.Destination_State,
# MAGIC     target.Destination_Zip = source.Destination_Zip,
# MAGIC     target.DOT_Number = source.DOT_Number,
# MAGIC     target.Delivery_StartDate = source.Delivery_StartDate,
# MAGIC     target.Equipment = source.Equipment,
# MAGIC     target.Equipment_Vehicle_Charges_Carrier_CAD = source.Equipment_Vehicle_Charges_Carrier_CAD,
# MAGIC     target.Equipment_Vehicle_Charges_Carrier_USD = source.Equipment_Vehicle_Charges_Carrier_USD,
# MAGIC     target.Equipment_Vehicle_Charges_Customer_CAD = source.Equipment_Vehicle_Charges_Customer_CAD,
# MAGIC     target.Equipment_Vehicle_Charges_Customer_USD = source.Equipment_Vehicle_Charges_Customer_USD,
# MAGIC     target.Expense_CAD = source.Expense_CAD,
# MAGIC     target.Expense_USD = source.Expense_USD,
# MAGIC     target.Financial_Period_Year = source.Financial_Period_Year,
# MAGIC     target.GreenScreen_Rate_CAD = source.GreenScreen_Rate_CAD,
# MAGIC     target.GreenScreen_Rate_USD = source.GreenScreen_Rate_USD,
# MAGIC     target.Invoice_Amount_CAD = source.Invoice_Amount_CAD,
# MAGIC     target.Invoice_Amount_USD = source.Invoice_Amount_USD,
# MAGIC     target.Invoiced_Date = source.Invoiced_Date,
# MAGIC     target.Lawson_ID = source.Lawson_ID,
# MAGIC     target.Load_Currency = source.Load_Currency,
# MAGIC     target.Load_Flag = source.Load_Flag,
# MAGIC     target.Load_Lane = source.Load_Lane,
# MAGIC     target.Load_Status = source.Load_Status,
# MAGIC     target.Load_Unload_Charges_Carrier_CAD = source.Load_Unload_Charges_Carrier_CAD,
# MAGIC     target.Load_Unload_Charges_Carrier_USD = source.Load_Unload_Charges_Carrier_USD,
# MAGIC     target.Load_Unload_Charges_Customer_CAD = source.Load_Unload_Charges_Customer_CAD,
# MAGIC     target.Load_Unload_Charges_Customer_USD = source.Load_Unload_Charges_Customer_USD,
# MAGIC     target.Margin_CAD = source.Margin_CAD,
# MAGIC     target.Margin_USD = source.Margin_USD,
# MAGIC     target.Market_Buy_Rate_CAD = source.Market_Buy_Rate_CAD,
# MAGIC     target.Market_Buy_Rate_USD = source.Market_Buy_Rate_USD,
# MAGIC     target.Market_Destination = source.Market_Destination,
# MAGIC     target.Market_Lane = source.Market_Lane,
# MAGIC     target.Market_Origin = source.Market_Origin,
# MAGIC     target.MC_Number = source.MC_Number,
# MAGIC     target.Miles = source.Miles,
# MAGIC     target.Miscellaneous_Chargers_Carrier_CAD = source.Miscellaneous_Chargers_Carrier_CAD,
# MAGIC     target.Miscellaneous_Chargers_Carrier_USD = source.Miscellaneous_Chargers_Carrier_USD,
# MAGIC     target.Miscellaneous_Chargers_Customers_CAD = source.Miscellaneous_Chargers_Customers_CAD,
# MAGIC     target.Miscellaneous_Chargers_Customers_USD = source.Miscellaneous_Chargers_Customers_USD,
# MAGIC     target.Mode = source.Mode,
# MAGIC     target.On_Time_Delivery = source.On_Time_Delivery,
# MAGIC     target.On_Time_Pickup = source.On_Time_Pickup,
# MAGIC     target.Origin_City = source.Origin_City,
# MAGIC     target.Origin_State = source.Origin_State,
# MAGIC     target.Origin_Zip = source.Origin_Zip,
# MAGIC     target.Permits_Compliance_Charges_Carrier_CAD = source.Permits_Compliance_Charges_Carrier_CAD,
# MAGIC     target.Permits_Compliance_Charges_Carrier_USD = source.Permits_Compliance_Charges_Carrier_USD,
# MAGIC     target.Permits_Compliance_Charges_Customer_CAD = source.Permits_Compliance_Charges_Customer_CAD,
# MAGIC     target.Permits_Compliance_Charges_Customer_USD = source.Permits_Compliance_Charges_Customer_USD,
# MAGIC     target.Pickup_Appointment_Date = source.Pickup_Appointment_Date,
# MAGIC     target.Actual_Pickup_Date = source.Actual_Pickup_Date,
# MAGIC     target.Pickup_EndDate = source.Pickup_EndDate,
# MAGIC     target.Pickup_StartDate = source.Pickup_StartDate,
# MAGIC     target.PO_Number = source.PO_Number,
# MAGIC     target.PreBookStatus = source.PreBookStatus,
# MAGIC     target.Revenue_CAD = source.Revenue_CAD,
# MAGIC     target.Revenue_USD = source.Revenue_USD,
# MAGIC     target.Rolled_Date = source.Rolled_Date,
# MAGIC     target.Sales_Rep_ID = source.Sales_Rep_ID,
# MAGIC     target.Sales_Rep = source.Sales_Rep,
# MAGIC     target.Ship_Date = source.Ship_Date,
# MAGIC     target.Spot_Margin = source.Spot_Margin,
# MAGIC     target.Spot_Revenue = source.Spot_Revenue,
# MAGIC     target.Tender_Source_Type = source.Tender_Source_Type,
# MAGIC     target.Tendered_Date = source.Tendered_Date,
# MAGIC     target.TMS_System = source.TMS_System,
# MAGIC     target.Trailer_Number = source.Trailer_Number,
# MAGIC     target.Transit_Routing_Chargers_Carrier_CAD = source.Transit_Routing_Chargers_Carrier_CAD,
# MAGIC     target.Transit_Routing_Chargers_Carrier_USD = source.Transit_Routing_Chargers_Carrier_USD,
# MAGIC     target.Transit_Routing_Chargers_Customer_CAD = source.Transit_Routing_Chargers_Customer_CAD,
# MAGIC     target.Transit_Routing_Chargers_Customer_USD = source.Transit_Routing_Chargers_Customer_USD,
# MAGIC     target.Week_Number = source.Week_Number,
# MAGIC     target.Carrier_Final_Rate_CAD = source.Carrier_Final_Rate_CAD,
# MAGIC     target.Carrier_Final_Rate_USD = source.Carrier_Final_Rate_USD,
# MAGIC     target.Hashkey = source.Hashkey,
# MAGIC     target.Last_Modified_Date = current_timestamp(),
# MAGIC     target.Last_Modified_By = 'Databricks',
# MAGIC     target.Is_Deleted = 0
# MAGIC
# MAGIC WHEN NOT MATCHED THEN
# MAGIC   INSERT (
# MAGIC     DW_Load_ID,
# MAGIC     Load_Number,
# MAGIC     Admin_Fees_Carrier_USD,
# MAGIC     Admin_Fees_Carrier_CAD,
# MAGIC     Admin_Fees_Customer_USD,
# MAGIC     Admin_Fees_Customer_CAD,
# MAGIC     Billing_Status,
# MAGIC     Actual_Delivered_Date,
# MAGIC     Booking_Type,
# MAGIC     Booked_Date,
# MAGIC     Carrier_Fuel_Surcharge_CAD,
# MAGIC     Carrier_Fuel_Surcharge_USD,
# MAGIC     Carrier_linehaul_CAD,
# MAGIC     Carrier_linehaul_USD,
# MAGIC     Carrier_Name,
# MAGIC     Carrier_New_Office,
# MAGIC     Carrier_Old_Office,
# MAGIC     Carrier_Other_Fees_CAD,
# MAGIC     Carrier_Other_Fees_USD,
# MAGIC     Carrier_ID,
# MAGIC     Carrier_Rep_ID,
# MAGIC     Carrier_Rep,
# MAGIC     Combined_Load,
# MAGIC     Consignee_Delivery_Address,
# MAGIC     Consignee_Name,
# MAGIC     Consignee_Pickup_Address,
# MAGIC     Customer_Fuel_Surcharge_USD,
# MAGIC     Customer_Fule_Surcharge_CAD,
# MAGIC     Customer_linehaul_CAD,
# MAGIC     Customer_linehaul_USD,
# MAGIC     Customer_ID,
# MAGIC     Customer_Master,
# MAGIC     Customer_Name,
# MAGIC     Customer_New_Office,
# MAGIC     Customer_Old_Office,
# MAGIC     Customer_Other_Fees_CAD,
# MAGIC     Customer_Other_Fees_USD,
# MAGIC     Customer_Rep_ID,
# MAGIC     Customer_Rep,
# MAGIC     Days_Ahead,
# MAGIC     Bounced_Date,
# MAGIC     Cancelled_Date,
# MAGIC     Delivery_Pickup_Charges_Carrier_CAD,
# MAGIC     Delivery_Pickup_Charges_Carrier_USD,
# MAGIC     Delivery_Pickup_Charges_Customer_CAD,
# MAGIC     Delivery_Pickup_Charges_Customer_USD,
# MAGIC     Delivery_Appointment_Date,
# MAGIC     Delivery_EndDate,
# MAGIC     Destination_City,
# MAGIC     Destination_State,
# MAGIC     Destination_Zip,
# MAGIC     DOT_Number,
# MAGIC     Delivery_StartDate,
# MAGIC     Equipment,
# MAGIC     Equipment_Vehicle_Charges_Carrier_CAD,
# MAGIC     Equipment_Vehicle_Charges_Carrier_USD,
# MAGIC     Equipment_Vehicle_Charges_Customer_CAD,
# MAGIC     Equipment_Vehicle_Charges_Customer_USD,
# MAGIC     Expense_CAD,
# MAGIC     Expense_USD,
# MAGIC     Financial_Period_Year,
# MAGIC     GreenScreen_Rate_CAD,
# MAGIC     GreenScreen_Rate_USD,
# MAGIC     Invoice_Amount_CAD,
# MAGIC     Invoice_Amount_USD,
# MAGIC     Invoiced_Date,
# MAGIC     Lawson_ID,
# MAGIC     Load_Currency,
# MAGIC     Load_Flag,
# MAGIC     Load_Lane,
# MAGIC     Load_Status,
# MAGIC     Load_Unload_Charges_Carrier_CAD,
# MAGIC     Load_Unload_Charges_Carrier_USD,
# MAGIC     Load_Unload_Charges_Customer_CAD,
# MAGIC     Load_Unload_Charges_Customer_USD,
# MAGIC     Margin_CAD,
# MAGIC     Margin_USD,
# MAGIC     Market_Buy_Rate_CAD,
# MAGIC     Market_Buy_Rate_USD,
# MAGIC     Market_Destination,
# MAGIC     Market_Lane,
# MAGIC     Market_Origin,
# MAGIC     MC_Number,
# MAGIC     Miles,
# MAGIC     Miscellaneous_Chargers_Carrier_CAD,
# MAGIC     Miscellaneous_Chargers_Carrier_USD,
# MAGIC     Miscellaneous_Chargers_Customers_CAD,
# MAGIC     Miscellaneous_Chargers_Customers_USD,
# MAGIC     Mode,
# MAGIC     On_Time_Delivery,
# MAGIC     On_Time_Pickup,
# MAGIC     Origin_City,
# MAGIC     Origin_State,
# MAGIC     Origin_Zip,
# MAGIC     Permits_Compliance_Charges_Carrier_CAD,
# MAGIC     Permits_Compliance_Charges_Carrier_USD,
# MAGIC     Permits_Compliance_Charges_Customer_CAD,
# MAGIC     Permits_Compliance_Charges_Customer_USD,
# MAGIC     Pickup_Appointment_Date,
# MAGIC     Actual_Pickup_Date,
# MAGIC     Pickup_EndDate,
# MAGIC     Pickup_StartDate,
# MAGIC     PO_Number,
# MAGIC     PreBookStatus,
# MAGIC     Revenue_CAD,
# MAGIC     Revenue_USD,
# MAGIC     Rolled_Date,
# MAGIC     Sales_Rep_ID,
# MAGIC     Sales_Rep,
# MAGIC     Ship_Date,
# MAGIC     Spot_Margin,
# MAGIC     Spot_Revenue,
# MAGIC     Tender_Source_Type,
# MAGIC     Tendered_Date,
# MAGIC     TMS_System,
# MAGIC     Trailer_Number,
# MAGIC     Transit_Routing_Chargers_Carrier_CAD,
# MAGIC     Transit_Routing_Chargers_Carrier_USD,
# MAGIC     Transit_Routing_Chargers_Customer_CAD,
# MAGIC     Transit_Routing_Chargers_Customer_USD,
# MAGIC     Week_Number,
# MAGIC     Carrier_Final_Rate_CAD,
# MAGIC     Carrier_Final_Rate_USD,
# MAGIC     Hashkey,
# MAGIC     Created_Date,
# MAGIC     Created_By,
# MAGIC     Last_Modified_Date,
# MAGIC     Last_Modified_By,
# MAGIC     Is_Deleted
# MAGIC   )
# MAGIC   VALUES (
# MAGIC     source.DW_Load_ID,
# MAGIC     source.Load_ID,
# MAGIC     source.Admin_Fees_Carrier_USD,
# MAGIC     source.Admin_Fees_Carrier_CAD,
# MAGIC     source.Admin_Fees_Customer_USD,
# MAGIC     source.Admin_Fees_Customer_CAD,
# MAGIC     source.Billing_Status,
# MAGIC     source.Actual_Delivered_Date,
# MAGIC     source.Booking_Type,
# MAGIC     source.Booked_Date,
# MAGIC     source.Carrier_Fuel_Surcharge_CAD,
# MAGIC     source.Carrier_Fuel_Surcharge_USD,
# MAGIC     source.Carrier_Linehaul_CAD,
# MAGIC     source.Carrier_Linehaul_USD,
# MAGIC     source.Carrier_Name,
# MAGIC     source.Carrier_New_Office,
# MAGIC     source.Carrier_Old_Office,
# MAGIC     source.Carrier_Other_Fees_CAD,
# MAGIC     source.Carrier_Other_Fees_USD,
# MAGIC     source.Carrier_ID,
# MAGIC     source.Carrier_Rep_ID,
# MAGIC     source.Carrier_Rep,
# MAGIC     source.Combined_Load,
# MAGIC     source.Consignee_Delivery_Address,
# MAGIC     source.Consignee_Name,
# MAGIC     source.Consignee_Pickup_Address,
# MAGIC     source.Customer_Fuel_Surcharge_USD,
# MAGIC     source.Customer_Fule_Surcharge_CAD,
# MAGIC     source.Customer_Linehaul_CAD,
# MAGIC     source.Customer_Linehaul_USD,
# MAGIC     source.Customer_ID,
# MAGIC     source.Customer_Master,
# MAGIC     source.Customer_Name,
# MAGIC     source.Customer_New_Office,
# MAGIC     source.Customer_Old_Office,
# MAGIC     source.Customer_Other_Fees_CAD,
# MAGIC     source.Customer_Other_Fees_USD,
# MAGIC     source.Customer_Rep_ID,
# MAGIC     source.Customer_Rep,
# MAGIC     source.Days_Ahead,
# MAGIC     source.Bounced_Date,
# MAGIC     source.Cancelled_Date,
# MAGIC     source.Delivery_Pickup_Charges_Carrier_CAD,
# MAGIC     source.Delivery_Pickup_Charges_Carrier_USD,
# MAGIC     source.Delivery_Pickup_Charges_Customer_CAD,
# MAGIC     source.Delivery_Pickup_Charges_Customer_USD,
# MAGIC     source.Delivery_Appointment_Date,
# MAGIC     source.Delivery_EndDate,
# MAGIC     source.Destination_City,
# MAGIC     source.Destination_State,
# MAGIC     source.Destination_Zip,
# MAGIC     source.DOT_Number,
# MAGIC     source.Delivery_StartDate,
# MAGIC     source.Equipment,
# MAGIC     source.Equipment_Vehicle_Charges_Carrier_CAD,
# MAGIC     source.Equipment_Vehicle_Charges_Carrier_USD,
# MAGIC     source.Equipment_Vehicle_Charges_Customer_CAD,
# MAGIC     source.Equipment_Vehicle_Charges_Customer_USD,
# MAGIC     source.Expense_CAD,
# MAGIC     source.Expense_USD,
# MAGIC     source.Financial_Period_Year,
# MAGIC     source.GreenScreen_Rate_CAD,
# MAGIC     source.GreenScreen_Rate_USD,
# MAGIC     source.Invoice_Amount_CAD,
# MAGIC     source.Invoice_Amount_USD,
# MAGIC     source.Invoiced_Date,
# MAGIC     source.Lawson_ID,
# MAGIC     source.Load_Currency,
# MAGIC     source.Load_Flag,
# MAGIC     source.Load_Lane,
# MAGIC     source.Load_Status,
# MAGIC     source.Load_Unload_Charges_Carrier_CAD,
# MAGIC     source.Load_Unload_Charges_Carrier_USD,
# MAGIC     source.Load_Unload_Charges_Customer_CAD,
# MAGIC     source.Load_Unload_Charges_Customer_USD,
# MAGIC     source.Margin_CAD,
# MAGIC     source.Margin_USD,
# MAGIC     source.Market_Buy_Rate_CAD,
# MAGIC     source.Market_Buy_Rate_USD,
# MAGIC     source.Market_Destination,
# MAGIC     source.Market_Lane,
# MAGIC     source.Market_Origin,
# MAGIC     source.MC_Number,
# MAGIC     source.Miles,
# MAGIC     source.Miscellaneous_Chargers_Carrier_CAD,
# MAGIC     source.Miscellaneous_Chargers_Carrier_USD,
# MAGIC     source.Miscellaneous_Chargers_Customers_CAD,
# MAGIC     source.Miscellaneous_Chargers_Customers_USD,
# MAGIC     source.Mode,
# MAGIC     source.On_Time_Delivery,
# MAGIC     source.On_Time_Pickup,
# MAGIC     source.Origin_City,
# MAGIC     source.Origin_State,
# MAGIC     source.Origin_Zip,
# MAGIC     source.Permits_Compliance_Charges_Carrier_CAD,
# MAGIC     source.Permits_Compliance_Charges_Carrier_USD,
# MAGIC     source.Permits_Compliance_Charges_Customer_CAD,
# MAGIC     source.Permits_Compliance_Charges_Customer_USD,
# MAGIC     source.Pickup_Appointment_Date,
# MAGIC     source.Actual_Pickup_Date,
# MAGIC     source.Pickup_EndDate,
# MAGIC     source.Pickup_StartDate,
# MAGIC     source.PO_Number,
# MAGIC     source.PreBookStatus,
# MAGIC     source.Revenue_CAD,
# MAGIC     source.Revenue_USD,
# MAGIC     source.Rolled_Date,
# MAGIC     source.Sales_Rep_ID,
# MAGIC     source.Sales_Rep,
# MAGIC     source.Ship_Date,
# MAGIC     source.Spot_Margin,
# MAGIC     source.Spot_Revenue,
# MAGIC     source.Tender_Source_Type,
# MAGIC     source.Tendered_Date,
# MAGIC     source.TMS_System,
# MAGIC     source.Trailer_Number,
# MAGIC     source.Transit_Routing_Chargers_Carrier_CAD,
# MAGIC     source.Transit_Routing_Chargers_Carrier_USD,
# MAGIC     source.Transit_Routing_Chargers_Customer_CAD,
# MAGIC     source.Transit_Routing_Chargers_Customer_USD,
# MAGIC     source.Week_Number,
# MAGIC     source.Carrier_Final_Rate_CAD,
# MAGIC     source.Carrier_Final_Rate_USD,
# MAGIC     source.Hashkey,
# MAGIC     current_timestamp(),
# MAGIC     'Databricks',
# MAGIC     current_timestamp(),
# MAGIC     'Databricks',
# MAGIC     0
# MAGIC   );
# MAGIC

# COMMAND ----------

# MAGIC %md
# MAGIC #### Update the Run Status

# COMMAND ----------

# MAGIC %sql
# MAGIC UPDATE metadata.mastermetadata 
# MAGIC SET PipelineEndTime = current_timestamp(),
# MAGIC LastLoadDateValue = (SELECT MAX(Last_Modified_Date) FROM silver.silver_aljex WHERE Is_Deleted=0),
# MAGIC PipelineRunStatus = 'Success'
# MAGIC WHERE TableID = 'SL2'