-- Databricks notebook source
-- MAGIC %md
-- MAGIC ##DDL Scripts

-- COMMAND ----------

CREATE OR REPLACE TABLE Bronze.Finance_GLSummary(
	OBJ_ID 	INTEGER	,
	COMPANY	INTEGER		,
	ACCT_UNIT	INTEGER		,
	ACCT_UNIT_DESCR	VARCHAR(255)		,
	ACCT_SUB	VARCHAR(255)		,
	ACCOUNT_DESC	VARCHAR(255)		,
	ACCT_PERIOD	INTEGER		,
	FISCAL_YEAR	SMALLINT		,
	CURRENCY_CODE	VARCHAR(255)		,
	TRAN_AMOUNT	DECIMAL(18,2)		,
	BASE_AMOUNT	DECIMAL(18,2)		,
	RPT_AMOUNT_1	DECIMAL(18,2)		,
	UNITS_AMOUNT	DECIMAL(18,2)		,
	HASHKEY	STRING	NOT NULL	,
	SOURCE_FILE_NAME	VARCHAR(255)	NOT NULL	,
	SOURCESYSTEM_ID	SMALLINT	NOT NULL	,
	SOURCESYSTEM_NAME	VARCHAR(255)	NOT NULL	,
	CREATED_BY	VARCHAR(255)	NOT NULL	,
	CREATED_DATE	TIMESTAMP_NTZ	NOT NULL	,
	LAST_MODIFIED_BY	VARCHAR(255)	NOT NULL	,
	LAST_MODIFIED_DATE	TIMESTAMP_NTZ	NOT NULL	,
	IS_DELETED	SMALLINT	NOT NULL	,
		CONSTRAINT  PK_GLSummary
		PRIMARY KEY (OBJ_ID)
);

-- COMMAND ----------

--Details
CREATE OR REPLACE TABLE Bronze.Finance_GLDetail(
  OBJ_ID 	INTEGER,
	COMPANY	INTEGER,
	FISCAL_YEAR	SMALLINT,
	ACCT_PERIOD	INTEGER,
	JE_NUMBER	INTEGER,
	SOURCE_SYSTEM	VARCHAR(255),
	JE_TYPE	VARCHAR(255),
	ACCT_UNIT	INTEGER,
	ACCT_UNIT_DESCR	VARCHAR(255),
	ACCT_SUB	VARCHAR(255),
	ACCOUNT_DESC	VARCHAR(255),
	SOURCE_CODE	VARCHAR(255),
	REFERENCE	VARCHAR(255),
	SOURCE_DESC	VARCHAR(255),
	AUTO_REV	VARCHAR(255),
	POSTING_DATE	TIMESTAMP_NTZ,
	TRAN_AMOUNT DECIMAL(18,2),
	BASE_AMOUNT	DECIMAL(18,2),
	RPT_AMOUNT_1	DECIMAL(18,2),
	UNITS_AMOUNT	DECIMAL(18,2),
 	TRANS_DESC VARCHAR(255),
 	CURRENCY_CODE VARCHAR(255),
 	HASHKEY STRING	NOT NULL,
	SOURCE_FILE_NAME VARCHAR(255) NOT NULL,
	SOURCESYSTEM_ID SMALLINT	NOT NULL,
	SOURCESYSTEM_NAME VARCHAR(255)	NOT NULL,
	CREATED_BY VARCHAR(255)	NOT NULL,
	CREATED_DATE TIMESTAMP_NTZ	NOT NULL,
	LAST_MODIFIED_BY VARCHAR(255)	NOT NULL,
	LAST_MODIFIED_DATE TIMESTAMP_NTZ	NOT NULL,
 	IS_DELETED SMALLINT NOT NULL,
	CONSTRAINT  PK_GLDetail
	PRIMARY KEY (OBJ_ID) 
	
);

-- COMMAND ----------

