# Databricks notebook source
# MAGIC %sql
# MAGIC SELECT COUNT(*) FROM bronze.finance_credits WHERE IS_DELETED = 0 

# COMMAND ----------



# COMMAND ----------

# MAGIC %sql
# MAGIC SELECT 
# MAGIC     COUNT(CASE WHEN CREDIT_KEY IS NULL THEN 1 END) AS NULL_CREDIT_KEY,
# MAGIC     COUNT(CASE WHEN CUSTOMER IS NULL THEN 1 END) AS NULL_CUSTOMER,
# MAGIC     COUNT(CASE WHEN SEARCH_NAME IS NULL THEN 1 END) AS NULL_SEARCH_NAME,
# MAGIC     COUNT(CASE WHEN COMPANY IS NULL THEN 1 END) AS NULL_COMPANY,
# MAGIC     COUNT(CASE WHEN ADDR1 IS NULL THEN 1 END) AS NULL_ADDR1,
# MAGIC     COUNT(CASE WHEN ADDR2 IS NULL THEN 1 END) AS NULL_ADDR2,
# MAGIC     COUNT(CASE WHEN CITY IS NULL THEN 1 END) AS NULL_CITY,
# MAGIC     COUNT(CASE WHEN STATE IS NULL THEN 1 END) AS NULL_STATE,
# MAGIC     COUNT(CASE WHEN COUNTRY_CODE IS NULL THEN 1 END) AS NULL_COUNTRY_CODE,
# MAGIC     COUNT(CASE WHEN ZIP IS NULL THEN 1 END) AS NULL_ZIP,
# MAGIC     COUNT(CASE WHEN START_DATE IS NULL THEN 1 END) AS NULL_START_DATE,
# MAGIC     COUNT(CASE WHEN ACTIVE_STATUS IS NULL THEN 1 END) AS NULL_ACTIVE_STATUS,
# MAGIC     COUNT(CASE WHEN CREDIT_LIM IS NULL THEN 1 END) AS NULL_CREDIT_LIM,
# MAGIC     COUNT(CASE WHEN CURRENCY_CD IS NULL THEN 1 END) AS NULL_CURRENCY_CD,
# MAGIC     COUNT(CASE WHEN TERMS_CD IS NULL THEN 1 END) AS NULL_TERMS_CD,
# MAGIC     COUNT(CASE WHEN TERM_RDESC_01 IS NULL THEN 1 END) AS NULL_TERM_RDESC_01,
# MAGIC     COUNT(CASE WHEN HASHKEY IS NULL THEN 1 END) AS NULL_HASHKEY,
# MAGIC     COUNT(CASE WHEN SOURCE_FILE_NAME IS NULL THEN 1 END) AS NULL_SOURCE_FILE_NAME,
# MAGIC     COUNT(CASE WHEN SOURCESYSTEM_ID IS NULL THEN 1 END) AS NULL_SOURCESYSTEM_ID,
# MAGIC     COUNT(CASE WHEN SOURCESYSTEM_NAME IS NULL THEN 1 END) AS NULL_SOURCESYSTEM_NAME,
# MAGIC     COUNT(CASE WHEN CREATED_BY IS NULL THEN 1 END) AS NULL_CREATED_BY,
# MAGIC     COUNT(CASE WHEN CREATED_DATE IS NULL THEN 1 END) AS NULL_CREATED_DATE,
# MAGIC     COUNT(CASE WHEN LAST_MODIFIED_BY IS NULL THEN 1 END) AS NULL_LAST_MODIFIED_BY,
# MAGIC     COUNT(CASE WHEN LAST_MODIFIED_DATE IS NULL THEN 1 END) AS NULL_LAST_MODIFIED_DATE,
# MAGIC     COUNT(CASE WHEN IS_DELETED IS NULL THEN 1 END) AS NULL_IS_DELETED
# MAGIC FROM 
# MAGIC     Bronze.Finance_Credits WHERE IS_DELETED = 0;
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC SELECT DISTINCT COMPANY FROM bronze.FINANCE_CREDITS

# COMMAND ----------

# MAGIC %sql
# MAGIC SELECT * FROM Bronze.Finance_Credits WHERE CUSTOMER IN ('100115999',
# MAGIC "200192338",
# MAGIC 610100002
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC SELECT * FROM metadata.mastermetadata WHERE tableid = 'F15'

# COMMAND ----------

# MAGIC %sql
# MAGIC SELECT * FROM Bronze.finance_credits WHERE Is_Deleted = 1

# COMMAND ----------

# MAGIC %sql
# MAGIC SELECT * FROM metadata.error_log_table WHERE Table_ID = 'F15'