# Databricks notebook source
# MAGIC %md
# MAGIC ###DDL

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE OR REPLACE TABLE Bronze.Finance_Credits (
# MAGIC     CREDIT_KEY STRING NOT NULL PRIMARY KEY	,
# MAGIC     CUSTOMER	VARCHAR(9),
# MAGIC     SEARCH_NAME	VARCHAR(30),
# MAGIC     COMPANY	SMALLINT,
# MAGIC     ADDR1	VARCHAR(30),
# MAGIC     ADDR2	VARCHAR(30),
# MAGIC     CITY	VARCHAR(18),
# MAGIC     STATE	VARCHAR(2),
# MAGIC     COUNTRY_CODE	VARCHAR(2),
# MAGIC     ZIP	VARCHAR(10),
# MAGIC     START_DATE	DATE,
# MAGIC     ACTIVE_STATUS	VARCHAR(1),
# MAGIC     CREDIT_LIM	DECIMAL(18,2),
# MAGIC     CURRENCY_CD	VARCHAR(5),
# MAGIC     TERMS_CD	VARCHAR(5),
# MAGIC     TERM_RDESC_01	VARCHAR(30),
# MAGIC     HASHKEY	STRING	NOT NULL	,
# MAGIC     SOURCE_FILE_NAME	VARCHAR(100)	NOT NULL	,
# MAGIC     SOURCESYSTEM_ID	SMALLINT	NOT NULL	,
# MAGIC     SOURCESYSTEM_NAME	VARCHAR(50)	NOT NULL	,
# MAGIC     CREATED_BY	VARCHAR(50)	NOT NULL	,
# MAGIC     CREATED_DATE	TIMESTAMP_NTZ	NOT NULL	,
# MAGIC     LAST_MODIFIED_BY	VARCHAR(50)	NOT NULL	,
# MAGIC     LAST_MODIFIED_DATE	TIMESTAMP_NTZ	NOT NULL	,
# MAGIC     IS_DELETED	SMALLINT	NOT NULL	)
# MAGIC