-- Databricks notebook source
-- MAGIC %md
-- MAGIC ## Aljex
-- MAGIC * **Description:** Full Load from Bronze to Silver as delta file
-- MAGIC * **Created Date:** 03/07/2025
-- MAGIC * **Created By:** Uday
-- MAGIC * **Modified Date:** 06/10/2025
-- MAGIC * **Modified By:** Uday
-- MAGIC * **Changes Made:** Logic Update

-- COMMAND ----------

-- MAGIC %md
-- MAGIC #### Update Pipeline Start Time

-- COMMAND ----------

UPDATE metadata.mastermetadata 
SET PipelineStartTime = current_timestamp()
WHERE TableID = 'SL2'

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ####Load the Data to Target Table

-- COMMAND ----------

MERGE INTO Silver.Silver_Aljex AS target
USING Silver.VW_Silver_Aljex_Full_Load AS source
ON target.DW_Load_ID = source.DW_Load_ID
WHEN MATCHED AND target.Hashkey <> source.Hashkey THEN
  UPDATE SET
    target.Admin_Fees_Carrier_USD = source.Admin_Fees_Carrier_USD,
    target.Admin_Fees_Carrier_CAD = source.Admin_Fees_Carrier_CAD,
    target.Admin_Fees_Customer_USD = source.Admin_Fees_Customer_USD,
    target.Admin_Fees_Customer_CAD = source.Admin_Fees_Customer_CAD,
    target.Billing_Status = source.Billing_Status,
    target.Actual_Delivered_Date = source.Actual_Delivered_Date,
    target.Booking_Type = source.Booking_Type,
    target.Booked_Date = source.Booked_Date,
    target.Carrier_Fuel_Surcharge_CAD = source.Carrier_Fuel_Surcharge_CAD,
    target.Carrier_Fuel_Surcharge_USD = source.Carrier_Fuel_Surcharge_USD,
    target.Carrier_linehaul_CAD = source.Carrier_Linehaul_CAD,
    target.Carrier_linehaul_USD = source.Carrier_Linehaul_USD,
    target.Carrier_Name = source.Carrier_Name,
    target.Carrier_New_Office = source.Carrier_New_Office,
    target.Carrier_Old_Office = source.Carrier_Old_Office,
    target.Carrier_Other_Fees_CAD = source.Carrier_Other_Fees_CAD,
    target.Carrier_Other_Fees_USD = source.Carrier_Other_Fees_USD,
    target.Carrier_ID = source.Carrier_ID,
    target.Carrier_Rep_ID = source.Carrier_Rep_ID,
    target.Carrier_Rep = source.Carrier_Rep,
    target.Combined_Load = source.Combined_Load,
    target.Consignee_Delivery_Address = source.Consignee_Delivery_Address,
    target.Consignee_Name = source.Consignee_Name,
    target.Consignee_Pickup_Address = source.Consignee_Pickup_Address,
    target.Customer_Fuel_Surcharge_USD = source.Customer_Fuel_Surcharge_USD,
    target.Customer_Fule_Surcharge_CAD = source.Customer_Fule_Surcharge_CAD,
    target.Customer_linehaul_CAD = source.Customer_Linehaul_CAD,
    target.Customer_linehaul_USD = source.Customer_Linehaul_USD,
    target.Customer_ID = source.Customer_ID,
    target.Customer_Master = source.Customer_Master,
    target.Customer_Name = source.Customer_Name,
    target.Customer_New_Office = source.Customer_New_Office,
    target.Customer_Old_Office = source.Customer_Old_Office,
    target.Customer_Other_Fees_CAD = source.Customer_Other_Fees_CAD,
    target.Customer_Other_Fees_USD = source.Customer_Other_Fees_USD,
    target.Customer_Rep_ID = source.Customer_Rep_ID,
    target.Customer_Rep = source.Customer_Rep,
    target.Days_Ahead = source.Days_Ahead,
    target.Bounced_Date = source.Bounced_Date,
    target.Cancelled_Date = source.Cancelled_Date,
    target.Delivery_Pickup_Charges_Carrier_CAD = source.Delivery_Pickup_Charges_Carrier_CAD,
    target.Delivery_Pickup_Charges_Carrier_USD = source.Delivery_Pickup_Charges_Carrier_USD,
    target.Delivery_Pickup_Charges_Customer_CAD = source.Delivery_Pickup_Charges_Customer_CAD,
    target.Delivery_Pickup_Charges_Customer_USD = source.Delivery_Pickup_Charges_Customer_USD,
    target.Delivery_Appointment_Date = source.Delivery_Appointment_Date,
    target.Delivery_EndDate = source.Delivery_EndDate,
    target.Destination_City = source.Destination_City,
    target.Destination_State = source.Destination_State,
    target.Destination_Zip = source.Destination_Zip,
    target.DOT_Number = source.DOT_Number,
    target.Delivery_StartDate = source.Delivery_StartDate,
    target.Equipment = source.Equipment,
    target.Equipment_Vehicle_Charges_Carrier_CAD = source.Equipment_Vehicle_Charges_Carrier_CAD,
    target.Equipment_Vehicle_Charges_Carrier_USD = source.Equipment_Vehicle_Charges_Carrier_USD,
    target.Equipment_Vehicle_Charges_Customer_CAD = source.Equipment_Vehicle_Charges_Customer_CAD,
    target.Equipment_Vehicle_Charges_Customer_USD = source.Equipment_Vehicle_Charges_Customer_USD,
    target.Expense_CAD = source.Expense_CAD,
    target.Expense_USD = source.Expense_USD,
    target.Financial_Period_Year = source.Financial_Period_Year,
    target.GreenScreen_Rate_CAD = source.GreenScreen_Rate_CAD,
    target.GreenScreen_Rate_USD = source.GreenScreen_Rate_USD,
    target.Invoice_Amount_CAD = source.Invoice_Amount_CAD,
    target.Invoice_Amount_USD = source.Invoice_Amount_USD,
    target.Invoiced_Date = source.Invoiced_Date,
    target.Lawson_ID = source.Lawson_ID,
    target.Load_Currency = source.Load_Currency,
    target.Load_Flag = source.Load_Flag,
    target.Load_Lane = source.Load_Lane,
    target.Load_Status = source.Load_Status,
    target.Load_Unload_Charges_Carrier_CAD = source.Load_Unload_Charges_Carrier_CAD,
    target.Load_Unload_Charges_Carrier_USD = source.Load_Unload_Charges_Carrier_USD,
    target.Load_Unload_Charges_Customer_CAD = source.Load_Unload_Charges_Customer_CAD,
    target.Load_Unload_Charges_Customer_USD = source.Load_Unload_Charges_Customer_USD,
    target.Margin_CAD = source.Margin_CAD,
    target.Margin_USD = source.Margin_USD,
    target.Market_Buy_Rate_CAD = source.Market_Buy_Rate_CAD,
    target.Market_Buy_Rate_USD = source.Market_Buy_Rate_USD,
    target.Market_Destination = source.Market_Destination,
    target.Market_Lane = source.Market_Lane,
    target.Market_Origin = source.Market_Origin,
    target.MC_Number = source.MC_Number,
    target.Miles = source.Miles,
    target.Miscellaneous_Chargers_Carrier_CAD = source.Miscellaneous_Chargers_Carrier_CAD,
    target.Miscellaneous_Chargers_Carrier_USD = source.Miscellaneous_Chargers_Carrier_USD,
    target.Miscellaneous_Chargers_Customers_CAD = source.Miscellaneous_Chargers_Customers_CAD,
    target.Miscellaneous_Chargers_Customers_USD = source.Miscellaneous_Chargers_Customers_USD,
    target.Mode = source.Mode,
    target.On_Time_Delivery = source.On_Time_Delivery,
    target.On_Time_Pickup = source.On_Time_Pickup,
    target.Origin_City = source.Origin_City,
    target.Origin_State = source.Origin_State,
    target.Origin_Zip = source.Origin_Zip,
    target.Permits_Compliance_Charges_Carrier_CAD = source.Permits_Compliance_Charges_Carrier_CAD,
    target.Permits_Compliance_Charges_Carrier_USD = source.Permits_Compliance_Charges_Carrier_USD,
    target.Permits_Compliance_Charges_Customer_CAD = source.Permits_Compliance_Charges_Customer_CAD,
    target.Permits_Compliance_Charges_Customer_USD = source.Permits_Compliance_Charges_Customer_USD,
    target.Pickup_Appointment_Date = source.Pickup_Appointment_Date,
    target.Actual_Pickup_Date = source.Actual_Pickup_Date,
    target.Pickup_EndDate = source.Pickup_EndDate,
    target.Pickup_StartDate = source.Pickup_StartDate,
    target.PO_Number = source.PO_Number,
    target.PreBookStatus = source.PreBookStatus,
    target.Revenue_CAD = source.Revenue_CAD,
    target.Revenue_USD = source.Revenue_USD,
    target.Rolled_Date = source.Rolled_Date,
    target.Sales_Rep_ID = source.Sales_Rep_ID,
    target.Sales_Rep = source.Sales_Rep,
    target.Ship_Date = source.Ship_Date,
    target.Spot_Margin = source.Spot_Margin,
    target.Spot_Revenue = source.Spot_Revenue,
    target.Tender_Source_Type = source.Tender_Source_Type,
    target.Tendered_Date = source.Tendered_Date,
    target.TMS_System = source.TMS_System,
    target.Trailer_Number = source.Trailer_Number,
    target.Transit_Routing_Chargers_Carrier_CAD = source.Transit_Routing_Chargers_Carrier_CAD,
    target.Transit_Routing_Chargers_Carrier_USD = source.Transit_Routing_Chargers_Carrier_USD,
    target.Transit_Routing_Chargers_Customer_CAD = source.Transit_Routing_Chargers_Customer_CAD,
    target.Transit_Routing_Chargers_Customer_USD = source.Transit_Routing_Chargers_Customer_USD,
    target.Week_Number = source.Week_Number,
    target.Carrier_Final_Rate_CAD = source.Carrier_Final_Rate_CAD,
    target.Carrier_Final_Rate_USD = source.Carrier_Final_Rate_USD,
    target.Hashkey = source.Hashkey,
    target.Last_Modified_Date = current_timestamp(),
    target.Last_Modified_By = 'Databricks',
    target.Is_Deleted = 0

WHEN NOT MATCHED THEN
  INSERT (
    DW_Load_ID,
    Load_Number,
    Admin_Fees_Carrier_USD,
    Admin_Fees_Carrier_CAD,
    Admin_Fees_Customer_USD,
    Admin_Fees_Customer_CAD,
    Billing_Status,
    Actual_Delivered_Date,
    Booking_Type,
    Booked_Date,
    Carrier_Fuel_Surcharge_CAD,
    Carrier_Fuel_Surcharge_USD,
    Carrier_linehaul_CAD,
    Carrier_linehaul_USD,
    Carrier_Name,
    Carrier_New_Office,
    Carrier_Old_Office,
    Carrier_Other_Fees_CAD,
    Carrier_Other_Fees_USD,
    Carrier_ID,
    Carrier_Rep_ID,
    Carrier_Rep,
    Combined_Load,
    Consignee_Delivery_Address,
    Consignee_Name,
    Consignee_Pickup_Address,
    Customer_Fuel_Surcharge_USD,
    Customer_Fule_Surcharge_CAD,
    Customer_linehaul_CAD,
    Customer_linehaul_USD,
    Customer_ID,
    Customer_Master,
    Customer_Name,
    Customer_New_Office,
    Customer_Old_Office,
    Customer_Other_Fees_CAD,
    Customer_Other_Fees_USD,
    Customer_Rep_ID,
    Customer_Rep,
    Days_Ahead,
    Bounced_Date,
    Cancelled_Date,
    Delivery_Pickup_Charges_Carrier_CAD,
    Delivery_Pickup_Charges_Carrier_USD,
    Delivery_Pickup_Charges_Customer_CAD,
    Delivery_Pickup_Charges_Customer_USD,
    Delivery_Appointment_Date,
    Delivery_EndDate,
    Destination_City,
    Destination_State,
    Destination_Zip,
    DOT_Number,
    Delivery_StartDate,
    Equipment,
    Equipment_Vehicle_Charges_Carrier_CAD,
    Equipment_Vehicle_Charges_Carrier_USD,
    Equipment_Vehicle_Charges_Customer_CAD,
    Equipment_Vehicle_Charges_Customer_USD,
    Expense_CAD,
    Expense_USD,
    Financial_Period_Year,
    GreenScreen_Rate_CAD,
    GreenScreen_Rate_USD,
    Invoice_Amount_CAD,
    Invoice_Amount_USD,
    Invoiced_Date,
    Lawson_ID,
    Load_Currency,
    Load_Flag,
    Load_Lane,
    Load_Status,
    Load_Unload_Charges_Carrier_CAD,
    Load_Unload_Charges_Carrier_USD,
    Load_Unload_Charges_Customer_CAD,
    Load_Unload_Charges_Customer_USD,
    Margin_CAD,
    Margin_USD,
    Market_Buy_Rate_CAD,
    Market_Buy_Rate_USD,
    Market_Destination,
    Market_Lane,
    Market_Origin,
    MC_Number,
    Miles,
    Miscellaneous_Chargers_Carrier_CAD,
    Miscellaneous_Chargers_Carrier_USD,
    Miscellaneous_Chargers_Customers_CAD,
    Miscellaneous_Chargers_Customers_USD,
    Mode,
    On_Time_Delivery,
    On_Time_Pickup,
    Origin_City,
    Origin_State,
    Origin_Zip,
    Permits_Compliance_Charges_Carrier_CAD,
    Permits_Compliance_Charges_Carrier_USD,
    Permits_Compliance_Charges_Customer_CAD,
    Permits_Compliance_Charges_Customer_USD,
    Pickup_Appointment_Date,
    Actual_Pickup_Date,
    Pickup_EndDate,
    Pickup_StartDate,
    PO_Number,
    PreBookStatus,
    Revenue_CAD,
    Revenue_USD,
    Rolled_Date,
    Sales_Rep_ID,
    Sales_Rep,
    Ship_Date,
    Spot_Margin,
    Spot_Revenue,
    Tender_Source_Type,
    Tendered_Date,
    TMS_System,
    Trailer_Number,
    Transit_Routing_Chargers_Carrier_CAD,
    Transit_Routing_Chargers_Carrier_USD,
    Transit_Routing_Chargers_Customer_CAD,
    Transit_Routing_Chargers_Customer_USD,
    Week_Number,
    Carrier_Final_Rate_CAD,
    Carrier_Final_Rate_USD,
    Hashkey,
    Created_Date,
    Created_By,
    Last_Modified_Date,
    Last_Modified_By,
    Is_Deleted
  )
  VALUES (
    source.DW_Load_ID,
    source.Load_ID,
    source.Admin_Fees_Carrier_USD,
    source.Admin_Fees_Carrier_CAD,
    source.Admin_Fees_Customer_USD,
    source.Admin_Fees_Customer_CAD,
    source.Billing_Status,
    source.Actual_Delivered_Date,
    source.Booking_Type,
    source.Booked_Date,
    source.Carrier_Fuel_Surcharge_CAD,
    source.Carrier_Fuel_Surcharge_USD,
    source.Carrier_Linehaul_CAD,
    source.Carrier_Linehaul_USD,
    source.Carrier_Name,
    source.Carrier_New_Office,
    source.Carrier_Old_Office,
    source.Carrier_Other_Fees_CAD,
    source.Carrier_Other_Fees_USD,
    source.Carrier_ID,
    source.Carrier_Rep_ID,
    source.Carrier_Rep,
    source.Combined_Load,
    source.Consignee_Delivery_Address,
    source.Consignee_Name,
    source.Consignee_Pickup_Address,
    source.Customer_Fuel_Surcharge_USD,
    source.Customer_Fule_Surcharge_CAD,
    source.Customer_Linehaul_CAD,
    source.Customer_Linehaul_USD,
    source.Customer_ID,
    source.Customer_Master,
    source.Customer_Name,
    source.Customer_New_Office,
    source.Customer_Old_Office,
    source.Customer_Other_Fees_CAD,
    source.Customer_Other_Fees_USD,
    source.Customer_Rep_ID,
    source.Customer_Rep,
    source.Days_Ahead,
    source.Bounced_Date,
    source.Cancelled_Date,
    source.Delivery_Pickup_Charges_Carrier_CAD,
    source.Delivery_Pickup_Charges_Carrier_USD,
    source.Delivery_Pickup_Charges_Customer_CAD,
    source.Delivery_Pickup_Charges_Customer_USD,
    source.Delivery_Appointment_Date,
    source.Delivery_EndDate,
    source.Destination_City,
    source.Destination_State,
    source.Destination_Zip,
    source.DOT_Number,
    source.Delivery_StartDate,
    source.Equipment,
    source.Equipment_Vehicle_Charges_Carrier_CAD,
    source.Equipment_Vehicle_Charges_Carrier_USD,
    source.Equipment_Vehicle_Charges_Customer_CAD,
    source.Equipment_Vehicle_Charges_Customer_USD,
    source.Expense_CAD,
    source.Expense_USD,
    source.Financial_Period_Year,
    source.GreenScreen_Rate_CAD,
    source.GreenScreen_Rate_USD,
    source.Invoice_Amount_CAD,
    source.Invoice_Amount_USD,
    source.Invoiced_Date,
    source.Lawson_ID,
    source.Load_Currency,
    source.Load_Flag,
    source.Load_Lane,
    source.Load_Status,
    source.Load_Unload_Charges_Carrier_CAD,
    source.Load_Unload_Charges_Carrier_USD,
    source.Load_Unload_Charges_Customer_CAD,
    source.Load_Unload_Charges_Customer_USD,
    source.Margin_CAD,
    source.Margin_USD,
    source.Market_Buy_Rate_CAD,
    source.Market_Buy_Rate_USD,
    source.Market_Destination,
    source.Market_Lane,
    source.Market_Origin,
    source.MC_Number,
    source.Miles,
    source.Miscellaneous_Chargers_Carrier_CAD,
    source.Miscellaneous_Chargers_Carrier_USD,
    source.Miscellaneous_Chargers_Customers_CAD,
    source.Miscellaneous_Chargers_Customers_USD,
    source.Mode,
    source.On_Time_Delivery,
    source.On_Time_Pickup,
    source.Origin_City,
    source.Origin_State,
    source.Origin_Zip,
    source.Permits_Compliance_Charges_Carrier_CAD,
    source.Permits_Compliance_Charges_Carrier_USD,
    source.Permits_Compliance_Charges_Customer_CAD,
    source.Permits_Compliance_Charges_Customer_USD,
    source.Pickup_Appointment_Date,
    source.Actual_Pickup_Date,
    source.Pickup_EndDate,
    source.Pickup_StartDate,
    source.PO_Number,
    source.PreBookStatus,
    source.Revenue_CAD,
    source.Revenue_USD,
    source.Rolled_Date,
    source.Sales_Rep_ID,
    source.Sales_Rep,
    source.Ship_Date,
    source.Spot_Margin,
    source.Spot_Revenue,
    source.Tender_Source_Type,
    source.Tendered_Date,
    source.TMS_System,
    source.Trailer_Number,
    source.Transit_Routing_Chargers_Carrier_CAD,
    source.Transit_Routing_Chargers_Carrier_USD,
    source.Transit_Routing_Chargers_Customer_CAD,
    source.Transit_Routing_Chargers_Customer_USD,
    source.Week_Number,
    source.Carrier_Final_Rate_CAD,
    source.Carrier_Final_Rate_USD,
    source.Hashkey,
    current_timestamp(),
    'Databricks',
    current_timestamp(),
    'Databricks',
    0
  );

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ####Update the Deeleted Records

-- COMMAND ----------

UPDATE Silver.silver_aljex 
SET Is_Deleted = 1, Last_Modified_Date = current_timestamp()
WHERE DW_Load_ID NOT IN (SELECT DW_Load_ID FROM Silver.vw_silver_aljex_full_load)

-- COMMAND ----------

-- MAGIC %md
-- MAGIC #### Update the Run Status

-- COMMAND ----------

UPDATE metadata.mastermetadata 
SET PipelineEndTime = current_timestamp(),
LastLoadDateValue = (SELECT MAX(Last_Modified_Date) FROM silver.silver_aljex WHERE Is_Deleted=0),
PipelineRunStatus = 'Success'
WHERE TableID = 'SL2'